INSERT INTO EventDefinition (applicationId, displayName, hidden, name, type) VALUES ('Document', 'documentImpressionMade', false, 'documentImpressionMade', 'DEFAULT') ON CONFLICT DO NOTHING;

INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='canonicalUrl'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='fileEntryId'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='fileEntryUUID'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='groupId'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='pageDescription'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='pageKeywords'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='pageTitle'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='referrer'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='url'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition (eventAttributeDefinitionId, eventDefinitionId) VALUES ((SELECT id from EventAttributeDefinition WHERE name='version'), (SELECT id from EventDefinition WHERE name='documentImpressionMade')) ON CONFLICT DO NOTHING;
