test.batch.run.property.query[functional-bundle-tomcat-mysql56-jdk8][test-portal-hotfix-release]=\
    ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Navigation") OR \
        (testray.main.component.name ~ "Breadcrumb") OR \
        (testray.main.component.name ~ "Navigation") OR \
        (testray.main.component.name ~ "Sitemap")\
    )

testray.main.component.name=Navigation