dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation project(":apps:archived:portal-security-wedeploy-auth-api")
	testIntegrationImplementation project(":apps:archived:portal-security-wedeploy-auth-service")
}