/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.subscription.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SubscriptionEntry service. Represents a row in the &quot;Provisioning_SubscriptionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.provisioning.subscription.model.impl.SubscriptionEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.provisioning.subscription.model.impl.SubscriptionEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubscriptionEntry
 * @generated
 */
@ProviderType
public interface SubscriptionEntryModel
	extends AttachedModel, BaseModel<SubscriptionEntry>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subscription entry model instance should use the {@link SubscriptionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this subscription entry.
	 *
	 * @return the primary key of this subscription entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subscription entry.
	 *
	 * @param primaryKey the primary key of this subscription entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this subscription entry.
	 *
	 * @return the mvcc version of this subscription entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this subscription entry.
	 *
	 * @param mvccVersion the mvcc version of this subscription entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the subscription entry ID of this subscription entry.
	 *
	 * @return the subscription entry ID of this subscription entry
	 */
	public long getSubscriptionEntryId();

	/**
	 * Sets the subscription entry ID of this subscription entry.
	 *
	 * @param subscriptionEntryId the subscription entry ID of this subscription entry
	 */
	public void setSubscriptionEntryId(long subscriptionEntryId);

	/**
	 * Returns the create date of this subscription entry.
	 *
	 * @return the create date of this subscription entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this subscription entry.
	 *
	 * @param createDate the create date of this subscription entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the fully qualified class name of this subscription entry.
	 *
	 * @return the fully qualified class name of this subscription entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this subscription entry.
	 *
	 * @return the class name ID of this subscription entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this subscription entry.
	 *
	 * @param classNameId the class name ID of this subscription entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this subscription entry.
	 *
	 * @return the class pk of this subscription entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this subscription entry.
	 *
	 * @param classPK the class pk of this subscription entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the contact uuid of this subscription entry.
	 *
	 * @return the contact uuid of this subscription entry
	 */
	@AutoEscape
	public String getContactUuid();

	/**
	 * Sets the contact uuid of this subscription entry.
	 *
	 * @param contactUuid the contact uuid of this subscription entry
	 */
	public void setContactUuid(String contactUuid);

}