import java.util.jar.Attributes
import java.util.jar.JarFile

import org.gradle.util.VersionNumber

task writeReleases

baseline {
	onlyIf {
		Properties properties = new Properties()

		File bndBndFile = project.file("bnd.bnd")

		bndBndFile.withInputStream {
			properties.load it
		}

		return VersionNumber.parse(properties["Bundle-Version"]) > VersionNumber.parse("2.0.0")
	}
}

classes {
	dependsOn writeReleases
}

dependencies {
	api group: "com.liferay.portal", name: "com.liferay.util.java", version: "default"
	api group: "javax.portlet", name: "portlet-api", transitive: false, version: "3.0.1"
	api project(":apps:asset:asset-entry-rel-service")
	api project(":apps:asset:asset-tag-stats-service")
	api project(":apps:blogs:blogs-api")
	api project(":apps:blogs:blogs-service")
	api project(":apps:document-library:document-library-api")
	api project(":apps:dynamic-data-lists:dynamic-data-lists-api")
	api project(":apps:dynamic-data-lists:dynamic-data-lists-service")
	api project(":apps:dynamic-data-mapping:dynamic-data-mapping-api")
	api project(":apps:dynamic-data-mapping:dynamic-data-mapping-service")
	api project(":apps:dynamic-data-mapping:dynamic-data-mapping-web")
	api project(":apps:friendly-url:friendly-url-api")
	api project(":apps:friendly-url:friendly-url-service")
	api project(":apps:journal:journal-api")
	api project(":apps:journal:journal-service")
	api project(":apps:message-boards:message-boards-api")
	api project(":apps:message-boards:message-boards-service")
	api project(":apps:subscription:subscription-api")
	api project(":apps:subscription:subscription-service")
	api project(":apps:wiki:wiki-api")
	api project(":apps:wiki:wiki-service")

	compileOnly group: "com.liferay", name: "com.liferay.petra.reflect", version: "3.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "3.0.0"
	compileOnly group: "com.liferay", name: "org.freemarker", version: "2.3.30.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"

	testImplementation classifier: "jdk8", group: "org.hsqldb", name: "hsqldb", version: "2.7.1"
	testImplementation group: "com.liferay", name: "com.ibm.icu4j", version: "54.1.1.LIFERAY-PATCHED-2"
	testImplementation group: "com.liferay", name: "com.sun.syndication", version: "1.0.LIFERAY-PATCHED-1"
	testImplementation group: "com.liferay", name: "org.jabsorb", version: "1.3.2.LIFERAY-PATCHED-2"
	testImplementation group: "log4j", name: "apache-log4j-extras", version: "1.1"
	testImplementation project(":apps:petra:petra-log4j")
}

writeReleases {
	dependsOn configurations.compileClasspath

	doLast {
		File releasesTxtFile = new File(processResources.destinationDir, "com/liferay/portal/tools/sample/sql/builder/dependencies/releases.txt")

		releasesTxtFile.withWriter("UTF-8") {
			Writer writer ->

			configurations.compileClasspath.each {
				println "Adding release information from ${it} into ${releasesTxtFile}"

				JarFile jarFile = new JarFile(it)

				Attributes mainAttributes = jarFile.manifest.mainAttributes

				String schemaVersion = mainAttributes.getValue("Liferay-Require-SchemaVersion")

				if (!schemaVersion) {
					return
				}

				String symbolicName = mainAttributes.getValue("Bundle-SymbolicName")

				writer.writeLine "${symbolicName}:${schemaVersion}"
			}
		}
	}
}