import java.util.jar.Attributes
import java.util.jar.JarFile

import org.gradle.util.VersionNumber

task writeReleases

baseline {
	onlyIf {
		Properties properties = new Properties()

		File bndBndFile = project.file("bnd.bnd")

		bndBndFile.withInputStream {
			properties.load it
		}

		return VersionNumber.parse(properties["Bundle-Version"]) > VersionNumber.parse("2.0.0")
	}
}

classes {
	dependsOn writeReleases
}

dependencies {
	api group: "com.liferay.portal", name: "com.liferay.util.java", version: "default"
	api group: "javax.portlet", name: "portlet-api", transitive: false, version: "3.0.1"
	api project(":apps:asset:asset-entry-rel-service")
	api project(":apps:blogs:blogs-api")
	api project(":apps:blogs:blogs-service")
	api project(":apps:commerce:commerce-currency-api")
	api project(":apps:commerce:commerce-currency-service")
	api project(":apps:commerce:commerce-product-api")
	api project(":apps:commerce:commerce-product-service")
	api project(":apps:document-library:document-library-api")
	api project(":apps:dynamic-data-lists:dynamic-data-lists-api")
	api project(":apps:dynamic-data-lists:dynamic-data-lists-service")
	api project(":apps:dynamic-data-mapping:dynamic-data-mapping-api")
	api project(":apps:dynamic-data-mapping:dynamic-data-mapping-service")
	api project(":apps:dynamic-data-mapping:dynamic-data-mapping-web")
	api project(":apps:fragment:fragment-api")
	api project(":apps:fragment:fragment-service")
	api project(":apps:friendly-url:friendly-url-api")
	api project(":apps:friendly-url:friendly-url-service")
	api project(":apps:hello-world:hello-world-web")
	api project(":apps:journal:journal-api")
	api project(":apps:journal:journal-service")
	api project(":apps:layout:layout-api")
	api project(":apps:layout:layout-page-template-api")
	api project(":apps:layout:layout-page-template-service")
	api project(":apps:login:login-web-api")
	api project(":apps:message-boards:message-boards-api")
	api project(":apps:message-boards:message-boards-service")
	api project(":apps:subscription:subscription-api")
	api project(":apps:subscription:subscription-service")
	api project(":apps:view-count:view-count-api")
	api project(":apps:view-count:view-count-service")
	api project(":apps:wiki:wiki-api")
	api project(":apps:wiki:wiki-service")

	compileOnly group: "com.liferay", name: "org.freemarker", version: "2.3.30.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-io")
	compileOnly project(":core:petra:petra-reflect")
	compileOnly project(":core:petra:petra-string")

	testImplementation group: "com.rometools", name: "rome", version: "1.16.0"
	testImplementation group: "log4j", name: "apache-log4j-extras", version: "1.2.17"
	testImplementation project(":apps:petra:petra-log4j")
}

writeReleases {
	dependsOn configurations.compileClasspath

	doLast {
		File releasesTxtFile = new File(processResources.destinationDir, "com/liferay/portal/tools/sample/sql/builder/dependencies/releases.txt")

		List<String> lines = []

		(configurations.compileClasspath + configurations.compileInclude).each {
			JarFile jarFile = new JarFile(it)

			Attributes mainAttributes = jarFile.manifest.mainAttributes

			String schemaVersion = mainAttributes.getValue("Liferay-Require-SchemaVersion")

			if (!schemaVersion) {
				return
			}

			logger.lifecycle "Adding release information from {} into {}.", it, releasesTxtFile

			String symbolicName = mainAttributes.getValue("Bundle-SymbolicName")

			lines.add("${symbolicName}:${schemaVersion}")
		}

		lines.sort()

		if (!releasesTxtFile.exists()) {
			mkdir releasesTxtFile.getParentFile()

			releasesTxtFile.createNewFile()
		}

		releasesTxtFile.setText lines.join('\n'), "UTF-8"
	}
}