dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype")
	compileOnly project(":core:petra:petra-string")
	testImplementation group: "org.apache.chemistry.opencmis", name: "chemistry-opencmis-client-api", version: "0.14.0"
	testImplementation group: "org.apache.lucene", name: "lucene-analyzers-common", version: "7.1.0"
	testImplementation group: "org.apache.lucene", name: "lucene-core", version: "7.1.0"
	testImplementation group: "org.apache.lucene", name: "lucene-queries", version: "7.1.0"
	testImplementation group: "org.apache.lucene", name: "lucene-queryparser", version: "7.1.0"
	testImplementation group: "org.apache.lucene", name: "lucene-sandbox", version: "7.1.0"
	testImplementation project(":apps:collaboration:document-library:document-library-repository-search")
}