/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.license.service.base;

import com.liferay.osb.provisioning.license.model.CommonLicenseKey;
import com.liferay.osb.provisioning.license.service.CommonLicenseKeyLocalService;
import com.liferay.osb.provisioning.license.service.CommonLicenseKeyLocalServiceUtil;
import com.liferay.osb.provisioning.license.service.persistence.CommonLicenseKeyPersistence;
import com.liferay.osb.provisioning.license.service.persistence.LicenseEntryPersistence;
import com.liferay.osb.provisioning.license.service.persistence.LicenseKeyFinder;
import com.liferay.osb.provisioning.license.service.persistence.LicenseKeyPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the common license key local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.provisioning.license.service.impl.CommonLicenseKeyLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.provisioning.license.service.impl.CommonLicenseKeyLocalServiceImpl
 * @generated
 */
public abstract class CommonLicenseKeyLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CommonLicenseKeyLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommonLicenseKeyLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommonLicenseKeyLocalServiceUtil</code>.
	 */

	/**
	 * Adds the common license key to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommonLicenseKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commonLicenseKey the common license key
	 * @return the common license key that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommonLicenseKey addCommonLicenseKey(
		CommonLicenseKey commonLicenseKey) {

		commonLicenseKey.setNew(true);

		return commonLicenseKeyPersistence.update(commonLicenseKey);
	}

	/**
	 * Creates a new common license key with the primary key. Does not add the common license key to the database.
	 *
	 * @param commonLicenseKeyId the primary key for the new common license key
	 * @return the new common license key
	 */
	@Override
	@Transactional(enabled = false)
	public CommonLicenseKey createCommonLicenseKey(long commonLicenseKeyId) {
		return commonLicenseKeyPersistence.create(commonLicenseKeyId);
	}

	/**
	 * Deletes the common license key with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommonLicenseKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commonLicenseKeyId the primary key of the common license key
	 * @return the common license key that was removed
	 * @throws PortalException if a common license key with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommonLicenseKey deleteCommonLicenseKey(long commonLicenseKeyId)
		throws PortalException {

		return commonLicenseKeyPersistence.remove(commonLicenseKeyId);
	}

	/**
	 * Deletes the common license key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommonLicenseKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commonLicenseKey the common license key
	 * @return the common license key that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommonLicenseKey deleteCommonLicenseKey(
		CommonLicenseKey commonLicenseKey) {

		return commonLicenseKeyPersistence.remove(commonLicenseKey);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CommonLicenseKey.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return commonLicenseKeyPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.provisioning.license.model.impl.CommonLicenseKeyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return commonLicenseKeyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.provisioning.license.model.impl.CommonLicenseKeyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return commonLicenseKeyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return commonLicenseKeyPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return commonLicenseKeyPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CommonLicenseKey fetchCommonLicenseKey(long commonLicenseKeyId) {
		return commonLicenseKeyPersistence.fetchByPrimaryKey(
			commonLicenseKeyId);
	}

	/**
	 * Returns the common license key with the matching UUID and company.
	 *
	 * @param uuid the common license key's UUID
	 * @param companyId the primary key of the company
	 * @return the matching common license key, or <code>null</code> if a matching common license key could not be found
	 */
	@Override
	public CommonLicenseKey fetchCommonLicenseKeyByUuidAndCompanyId(
		String uuid, long companyId) {

		return commonLicenseKeyPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the common license key with the primary key.
	 *
	 * @param commonLicenseKeyId the primary key of the common license key
	 * @return the common license key
	 * @throws PortalException if a common license key with the primary key could not be found
	 */
	@Override
	public CommonLicenseKey getCommonLicenseKey(long commonLicenseKeyId)
		throws PortalException {

		return commonLicenseKeyPersistence.findByPrimaryKey(commonLicenseKeyId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			commonLicenseKeyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CommonLicenseKey.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("commonLicenseKeyId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			commonLicenseKeyLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CommonLicenseKey.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"commonLicenseKeyId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			commonLicenseKeyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CommonLicenseKey.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("commonLicenseKeyId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return commonLicenseKeyLocalService.deleteCommonLicenseKey(
			(CommonLicenseKey)persistedModel);
	}

	public BasePersistence<CommonLicenseKey> getBasePersistence() {
		return commonLicenseKeyPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commonLicenseKeyPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the common license key with the matching UUID and company.
	 *
	 * @param uuid the common license key's UUID
	 * @param companyId the primary key of the company
	 * @return the matching common license key
	 * @throws PortalException if a matching common license key could not be found
	 */
	@Override
	public CommonLicenseKey getCommonLicenseKeyByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return commonLicenseKeyPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the common license keies.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.provisioning.license.model.impl.CommonLicenseKeyModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of common license keies
	 * @param end the upper bound of the range of common license keies (not inclusive)
	 * @return the range of common license keies
	 */
	@Override
	public List<CommonLicenseKey> getCommonLicenseKeies(int start, int end) {
		return commonLicenseKeyPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of common license keies.
	 *
	 * @return the number of common license keies
	 */
	@Override
	public int getCommonLicenseKeiesCount() {
		return commonLicenseKeyPersistence.countAll();
	}

	/**
	 * Updates the common license key in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommonLicenseKeyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commonLicenseKey the common license key
	 * @return the common license key that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommonLicenseKey updateCommonLicenseKey(
		CommonLicenseKey commonLicenseKey) {

		return commonLicenseKeyPersistence.update(commonLicenseKey);
	}

	@Deactivate
	protected void deactivate() {
		CommonLicenseKeyLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CommonLicenseKeyLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		commonLicenseKeyLocalService = (CommonLicenseKeyLocalService)aopProxy;

		CommonLicenseKeyLocalServiceUtil.setService(
			commonLicenseKeyLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommonLicenseKeyLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommonLicenseKey.class;
	}

	protected String getModelClassName() {
		return CommonLicenseKey.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = commonLicenseKeyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CommonLicenseKeyLocalService commonLicenseKeyLocalService;

	@Reference
	protected CommonLicenseKeyPersistence commonLicenseKeyPersistence;

	@Reference
	protected LicenseEntryPersistence licenseEntryPersistence;

	@Reference
	protected LicenseKeyPersistence licenseKeyPersistence;

	@Reference
	protected LicenseKeyFinder licenseKeyFinder;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CommonLicenseKeyLocalServiceBaseImpl.class);

}