import com.liferay.gradle.util.FileUtil

import org.apache.tools.ant.filters.FixCrLfFilter

apply plugin: "antlr"
apply plugin: "com.liferay.spring.boot.defaults"
apply plugin: "io.spring.dependency-management"

sourceCompatibility = "1.8"
targetCompatibility = "1.8"

String parserDirName = "com/liferay/osb/asah/common/filter/expression/parser"
List<String> startParameterTaskNames = gradle.startParameter.taskNames

bootJar {
	enabled = false
}

dependencies {
	annotationProcessor group: "org.antlr", name: "antlr4-annotations", version: "4.3"

	antlr group: "org.antlr", name: "antlr4", version: "4.5.3"

	api group: "org.antlr", name: "antlr4-runtime", version: "4.5.3"
}

generateGrammarSource {
	setActions([])

	File grammarFile = file("src/main/antlr/${parserDirName}/FilterExpression.g4")

	dependsOn cleanGenerateGrammarSource

	doFirst {
		delete fileTree("src/main/java/" + parserDirName) {
			exclude "**/source_formatter.ignore"
		}

		delete fileTree("src/main/resources/" + parserDirName) {
			exclude "**/source_formatter.ignore"
		}

		javaexec {
			args "-o", FileUtil.relativize(generateGrammarSource.outputDirectory, grammarFile.parentFile)
			args grammarFile.name
			args "-visitor"

			classpath = generateGrammarSource.antlrClasspath
			main = "org.antlr.v4.Tool"
			maxHeapSize = generateGrammarSource.maxHeapSize
			workingDir = grammarFile.parentFile
		}
	}

	doLast {
		copy {
			filter(FixCrLfFilter, javafiles: true, tab: FixCrLfFilter.AddAsisRemove.newInstance("add"))

			from outputDirectory
			include "**/*.java"
			into "src/main/java/" + parserDirName
		}

		copy {
			from outputDirectory
			exclude "**/*.java"
			into "src/main/resources/" + parserDirName
		}
	}

	ext {
		autoClean = false
	}

	enabled = startParameterTaskNames.contains("generateGrammarSource")
	maxHeapSize = "1512m"
	outputDirectory = new File(temporaryDir, "generated")
}

jar {
	enabled = true
}