/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.adaptive.media.handler;

import com.liferay.adaptive.media.AdaptiveMedia;

import java.io.IOException;

import java.util.Optional;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 * Handles upcoming requests for a particular kind of media (i.e., media
 * generated by one type of processor).
 *
 * @author Adolfo Pérez
 */
public interface AMRequestHandler<T> {

	/**
	 * Returns the requested {@link AdaptiveMedia} instance wrapped in an {@link
	 * Optional} instance. If no media is found matching the request, or an
	 * application error is raised while fetching the media, an empty {@link
	 * Optional} is returned.
	 *
	 * @param  httpServletRequest the request to process
	 * @return a non-<code>null</code> {@link Optional} instance containing the
	 *         value (if any).
	 * @throws IOException if an IO error occurred while processing the request
	 * @throws ServletException if any other processing error occurred
	 */
	public Optional<AdaptiveMedia<T>> handleRequest(
			HttpServletRequest httpServletRequest)
		throws IOException, ServletException;

}