dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation project(":apps:asset:asset-auto-tagger-api")
	testIntegrationImplementation project(":apps:portal-configuration:portal-configuration-test-util")
	testIntegrationImplementation project(":core:registry-api")
}