dependencies {
	testIntegrationImplementation group: "com.github.everit-org.json-schema", name: "org.everit.json.schema", version: "1.11.1"
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay", name: "org.freemarker", version: "2.3.30.LIFERAY-PATCHED-2"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	testIntegrationImplementation group: "org.jsoup", name: "jsoup", version: "1.15.3"
	testIntegrationImplementation project (":apps:fragment:fragment-api")
	testIntegrationImplementation project (":apps:fragment:fragment-service")
	testIntegrationImplementation project(":apps:journal:journal-api")
	testIntegrationImplementation project(":apps:journal:journal-test-util")
}