test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
    ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
    (\
        (test.class.method.name == "AssetPublisherUseCase#ViewBlogsEntriesViaRelatedAssets") OR \
        (test.class.method.name == "SiteMemberships#AddMember") OR \
        (test.class.method.name == "WebContentDisplay#ChangeTemplate")\
    ) OR \
    (\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Item Selector") OR \
            (testray.main.component.name ~ "Item Selector")\
        )\
    )

testray.main.component.name=Item Selector