apply plugin: "com.liferay.spring.boot.defaults"
apply plugin: "io.spring.dependency-management"

ext {
	set("junit-jupiter.version", "5.8.2")
	set("log4j2.version", "2.17.0")
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"

bootJar {
	classifier = "application"
}

configurations.all {
	exclude group: "org.apache.geronimo.bundles", module: "json"
	exclude group: "org.nd4j", module: "nd4j-native-platform"
	exclude group: "org.slf4j", module: "slf4j-log4j12"
}

dependencies {
	api group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jdk8", version: "2.13.5"
	api group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-json-org", version: "2.13.5"
	api group: "com.graphql-java", name: "graphql-java", version: "20.7"
	api group: "com.liferay", name: "com.liferay.petra.lang", version: "1.0.0"
	api group: "com.liferay", name: "com.liferay.petra.string", version: "1.0.0"
	api group: "io.improbable", name: "keanu", version: "0.0.26"
	api group: "org.everit.json", name: "org.everit.json.schema", version: "1.5.1"
	api group: "org.springframework.boot", name: "spring-boot-starter-hateoas"
	api project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-common")

	testImplementation group: "nl.jqno.equalsverifier", name: "equalsverifier", version: "2.5.1"
	testImplementation project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-test-util")

	testIntegrationImplementation group: "io.rest-assured", name: "json-schema-validator", version: "3.2.0"
	testIntegrationImplementation group: "io.rest-assured", name: "rest-assured", version: "3.2.0"
	testIntegrationImplementation project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-batch-curator")
}

jar {
	enabled = true
}