apply plugin: "io.spring.dependency-management"
apply plugin: "org.springframework.boot"

ext {
	set("junit-jupiter.version", "5.8.2")
	set("log4j2.version", "2.17.0")
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

bootJar {
	archiveClassifier = "application"
}

configurations.all {
	exclude group: "org.apache.geronimo.bundles", module: "json"
	exclude group: "org.nd4j", module: "nd4j-native-platform"
	exclude group: "org.slf4j", module: "slf4j-log4j12"
}

dependencies {
	api group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jdk8", version: "2.18.2"
	api group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-json-org", version: "2.18.2"
	api group: "com.github.erosb", name: "everit-json-schema", version: "1.14.4"
	api group: "com.graphql-java", name: "graphql-java", version: "22.3"
	api group: "io.improbable", name: "keanu", version: "0.0.26"
	api group: "org.jooq", name: "jooq", version: "3.19.18"
	api group: "org.springframework.boot", name: "spring-boot-starter-hateoas"
	api project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-common")
	testImplementation group: "net.bytebuddy", name: "byte-buddy", version: "1.16.1"
	testImplementation group: "nl.jqno.equalsverifier", name: "equalsverifier", version: "3.18.1"
	testImplementation project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-test-util")
	testIntegrationImplementation group: "io.rest-assured", name: "json-schema-validator", version: "3.2.0"
	testIntegrationImplementation group: "io.rest-assured", name: "rest-assured", version: "3.2.0"
	testIntegrationImplementation project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-batch-curator")
}

jar {
	enabled = true
}