##
## Jenkins
##

    jenkins.private.property.names=\
        email.address.1,\
        email.address.2,\
        email.address.3,\
        email.address.4,\
        email.address.5,\
        email.password.1,\
        email.password.2,\
        email.password.3,\
        email.password.4,\
        email.password.5

##
## Poshi
##

    component.names=\
        loop,\
        loop-acceptance,\
        loop-feed,\
        loop-groups,\
        loop-known-issues,\
        loop-navigation,\
        loop-notifications,\
        loop-people,\
        loop-search,\
        loop-smoke,\
        loop-topics,\
        loop-upgrade,\
        loop-view-data

    database.bare.enabled=true

    osgi.app.includes=osb-loop,push-notifications

    test.case.available.property.names=\
        ${test.case.required.property.names},\
        \
        elasticsearch.single.shard.enabled,\
        hook.plugins.includes,\
        loop.acceptance,\
        loop.enabled,\
        osgi.module.configuration.file.names,\
        osgi.module.configurations,\
        portlet.plugins.includes,\
        portlet.properties.elasticsearch-web,\
        portlet.properties.loop-portlet,\
        portlet.properties.osb-loop-web,\
        remote.elasticsearch.enabled,\
        skip.clean-app-server-deploy-dir,\
        test.run.environment,\
        test.smtp.server.enabled,\
        testray.main.component.name,\
        theme.plugins.includes,\
        web.plugins.includes

    test.case.available.property.values[testray.main.component.name]=\
        ${testray.team.loop.component.names},\
        Loop

    test.case.required.property.names=testray.main.component.name

    testray.team.loop.component.names=Loop

    testray.team.names=loop

##
## Test Batch
##

    test.batch.bundle.version[subrepository-functional-bundle-tomcat80-mysql56-jdk8]=7.0.10.6
    test.batch.names=subrepository-functional-bundle-tomcat80-mysql56-jdk8

    test.batch.run.property.query[subrepository-functional-bundle-tomcat80-mysql56-jdk8]=\
        loop.acceptance == true

##
## Test Fix Pack
##

    test.build.fix.pack.zip.url=http://mirrors.lax.liferay.com/files.liferay.com/private/ee/fix-packs/7.0.10/hotfix/liferay-hotfix-2260-7010.zip
    test.fix.pack.base.url=https://files.liferay.com/private/ee/fix-packs/

##
## Utilities
##

    test.smtp.server.dir=${project.dir}/lib/development
    test.smtp.server.url=http://mirrors.lax.liferay.com/repository-cdn.liferay.com/nexus/content/repositories/third-party/com/liferay/com.mockmock/1.4.0/com.mockmock-1.4.0.jar