/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.license.model.impl;

import com.liferay.osb.provisioning.license.model.CommonLicenseKey;
import com.liferay.osb.provisioning.license.service.CommonLicenseKeyLocalServiceUtil;

/**
 * The extended model base implementation for the CommonLicenseKey service. Represents a row in the &quot;Provisioning_CommonLicenseKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommonLicenseKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommonLicenseKeyImpl
 * @see CommonLicenseKey
 * @generated
 */
public abstract class CommonLicenseKeyBaseImpl
	extends CommonLicenseKeyModelImpl implements CommonLicenseKey {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a common license key model instance should use the <code>CommonLicenseKey</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommonLicenseKeyLocalServiceUtil.addCommonLicenseKey(this);
		}
		else {
			CommonLicenseKeyLocalServiceUtil.updateCommonLicenseKey(this);
		}
	}

}