/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.license.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.provisioning.license.model.CommonLicenseKey;
import com.liferay.osb.provisioning.license.model.CommonLicenseKeyModel;
import com.liferay.osb.provisioning.license.model.CommonLicenseKeySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommonLicenseKey service. Represents a row in the &quot;Provisioning_CommonLicenseKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommonLicenseKeyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommonLicenseKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommonLicenseKeyImpl
 * @generated
 */
@JSON(strict = true)
public class CommonLicenseKeyModelImpl
	extends BaseModelImpl<CommonLicenseKey> implements CommonLicenseKeyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a common license key model instance should use the <code>CommonLicenseKey</code> interface instead.
	 */
	public static final String TABLE_NAME = "Provisioning_CommonLicenseKey";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"commonLicenseKeyId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"productGroup", Types.VARCHAR},
		{"productEnvironment", Types.VARCHAR},
		{"productVersion", Types.VARCHAR}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}, {"fileName", Types.VARCHAR},
		{"fileSize", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commonLicenseKeyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("productGroup", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productEnvironment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileSize", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Provisioning_CommonLicenseKey (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,commonLicenseKeyId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,productGroup VARCHAR(75) null,productEnvironment VARCHAR(75) null,productVersion VARCHAR(75) null,startDate DATE null,endDate DATE null,fileName VARCHAR(75) null,fileSize LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table Provisioning_CommonLicenseKey";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commonLicenseKey.endDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Provisioning_CommonLicenseKey.endDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long ENDDATE_COLUMN_BITMASK = 2L;

	public static final long FILENAME_COLUMN_BITMASK = 4L;

	public static final long PRODUCTENVIRONMENT_COLUMN_BITMASK = 8L;

	public static final long PRODUCTGROUP_COLUMN_BITMASK = 16L;

	public static final long PRODUCTVERSION_COLUMN_BITMASK = 32L;

	public static final long STARTDATE_COLUMN_BITMASK = 64L;

	public static final long UUID_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommonLicenseKey toModel(CommonLicenseKeySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CommonLicenseKey model = new CommonLicenseKeyImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setCommonLicenseKeyId(soapModel.getCommonLicenseKeyId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setProductGroup(soapModel.getProductGroup());
		model.setProductEnvironment(soapModel.getProductEnvironment());
		model.setProductVersion(soapModel.getProductVersion());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());
		model.setFileName(soapModel.getFileName());
		model.setFileSize(soapModel.getFileSize());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommonLicenseKey> toModels(
		CommonLicenseKeySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommonLicenseKey> models = new ArrayList<CommonLicenseKey>(
			soapModels.length);

		for (CommonLicenseKeySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CommonLicenseKeyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commonLicenseKeyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommonLicenseKeyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commonLicenseKeyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommonLicenseKey.class;
	}

	@Override
	public String getModelClassName() {
		return CommonLicenseKey.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommonLicenseKey, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommonLicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommonLicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommonLicenseKey)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommonLicenseKey, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommonLicenseKey, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommonLicenseKey)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommonLicenseKey, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommonLicenseKey, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CommonLicenseKey, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<CommonLicenseKey, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<CommonLicenseKey, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", CommonLicenseKey::getMvccVersion);
		attributeGetterFunctions.put("uuid", CommonLicenseKey::getUuid);
		attributeGetterFunctions.put(
			"commonLicenseKeyId", CommonLicenseKey::getCommonLicenseKeyId);
		attributeGetterFunctions.put(
			"companyId", CommonLicenseKey::getCompanyId);
		attributeGetterFunctions.put("userId", CommonLicenseKey::getUserId);
		attributeGetterFunctions.put("userName", CommonLicenseKey::getUserName);
		attributeGetterFunctions.put(
			"createDate", CommonLicenseKey::getCreateDate);
		attributeGetterFunctions.put(
			"productGroup", CommonLicenseKey::getProductGroup);
		attributeGetterFunctions.put(
			"productEnvironment", CommonLicenseKey::getProductEnvironment);
		attributeGetterFunctions.put(
			"productVersion", CommonLicenseKey::getProductVersion);
		attributeGetterFunctions.put(
			"startDate", CommonLicenseKey::getStartDate);
		attributeGetterFunctions.put("endDate", CommonLicenseKey::getEndDate);
		attributeGetterFunctions.put("fileName", CommonLicenseKey::getFileName);
		attributeGetterFunctions.put("fileSize", CommonLicenseKey::getFileSize);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<CommonLicenseKey, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<CommonLicenseKey, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CommonLicenseKey, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<CommonLicenseKey, Long>)
				CommonLicenseKey::setMvccVersion);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<CommonLicenseKey, String>)CommonLicenseKey::setUuid);
		attributeSetterBiConsumers.put(
			"commonLicenseKeyId",
			(BiConsumer<CommonLicenseKey, Long>)
				CommonLicenseKey::setCommonLicenseKeyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CommonLicenseKey, Long>)CommonLicenseKey::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CommonLicenseKey, Long>)CommonLicenseKey::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CommonLicenseKey, String>)
				CommonLicenseKey::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CommonLicenseKey, Date>)
				CommonLicenseKey::setCreateDate);
		attributeSetterBiConsumers.put(
			"productGroup",
			(BiConsumer<CommonLicenseKey, String>)
				CommonLicenseKey::setProductGroup);
		attributeSetterBiConsumers.put(
			"productEnvironment",
			(BiConsumer<CommonLicenseKey, String>)
				CommonLicenseKey::setProductEnvironment);
		attributeSetterBiConsumers.put(
			"productVersion",
			(BiConsumer<CommonLicenseKey, String>)
				CommonLicenseKey::setProductVersion);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<CommonLicenseKey, Date>)CommonLicenseKey::setStartDate);
		attributeSetterBiConsumers.put(
			"endDate",
			(BiConsumer<CommonLicenseKey, Date>)CommonLicenseKey::setEndDate);
		attributeSetterBiConsumers.put(
			"fileName",
			(BiConsumer<CommonLicenseKey, String>)
				CommonLicenseKey::setFileName);
		attributeSetterBiConsumers.put(
			"fileSize",
			(BiConsumer<CommonLicenseKey, Long>)CommonLicenseKey::setFileSize);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCommonLicenseKeyId() {
		return _commonLicenseKeyId;
	}

	@Override
	public void setCommonLicenseKeyId(long commonLicenseKeyId) {
		_commonLicenseKeyId = commonLicenseKeyId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public String getProductGroup() {
		if (_productGroup == null) {
			return "";
		}
		else {
			return _productGroup;
		}
	}

	@Override
	public void setProductGroup(String productGroup) {
		_columnBitmask |= PRODUCTGROUP_COLUMN_BITMASK;

		if (_originalProductGroup == null) {
			_originalProductGroup = _productGroup;
		}

		_productGroup = productGroup;
	}

	public String getOriginalProductGroup() {
		return GetterUtil.getString(_originalProductGroup);
	}

	@JSON
	@Override
	public String getProductEnvironment() {
		if (_productEnvironment == null) {
			return "";
		}
		else {
			return _productEnvironment;
		}
	}

	@Override
	public void setProductEnvironment(String productEnvironment) {
		_columnBitmask |= PRODUCTENVIRONMENT_COLUMN_BITMASK;

		if (_originalProductEnvironment == null) {
			_originalProductEnvironment = _productEnvironment;
		}

		_productEnvironment = productEnvironment;
	}

	public String getOriginalProductEnvironment() {
		return GetterUtil.getString(_originalProductEnvironment);
	}

	@JSON
	@Override
	public String getProductVersion() {
		if (_productVersion == null) {
			return "";
		}
		else {
			return _productVersion;
		}
	}

	@Override
	public void setProductVersion(String productVersion) {
		_columnBitmask |= PRODUCTVERSION_COLUMN_BITMASK;

		if (_originalProductVersion == null) {
			_originalProductVersion = _productVersion;
		}

		_productVersion = productVersion;
	}

	public String getOriginalProductVersion() {
		return GetterUtil.getString(_originalProductVersion);
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_columnBitmask |= STARTDATE_COLUMN_BITMASK;

		if (_originalStartDate == null) {
			_originalStartDate = _startDate;
		}

		_startDate = startDate;
	}

	public Date getOriginalStartDate() {
		return _originalStartDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_columnBitmask = -1L;

		if (_originalEndDate == null) {
			_originalEndDate = _endDate;
		}

		_endDate = endDate;
	}

	public Date getOriginalEndDate() {
		return _originalEndDate;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_columnBitmask |= FILENAME_COLUMN_BITMASK;

		if (_originalFileName == null) {
			_originalFileName = _fileName;
		}

		_fileName = fileName;
	}

	public String getOriginalFileName() {
		return GetterUtil.getString(_originalFileName);
	}

	@JSON
	@Override
	public long getFileSize() {
		return _fileSize;
	}

	@Override
	public void setFileSize(long fileSize) {
		_fileSize = fileSize;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommonLicenseKey.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommonLicenseKey toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommonLicenseKey>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommonLicenseKeyImpl commonLicenseKeyImpl = new CommonLicenseKeyImpl();

		commonLicenseKeyImpl.setMvccVersion(getMvccVersion());
		commonLicenseKeyImpl.setUuid(getUuid());
		commonLicenseKeyImpl.setCommonLicenseKeyId(getCommonLicenseKeyId());
		commonLicenseKeyImpl.setCompanyId(getCompanyId());
		commonLicenseKeyImpl.setUserId(getUserId());
		commonLicenseKeyImpl.setUserName(getUserName());
		commonLicenseKeyImpl.setCreateDate(getCreateDate());
		commonLicenseKeyImpl.setProductGroup(getProductGroup());
		commonLicenseKeyImpl.setProductEnvironment(getProductEnvironment());
		commonLicenseKeyImpl.setProductVersion(getProductVersion());
		commonLicenseKeyImpl.setStartDate(getStartDate());
		commonLicenseKeyImpl.setEndDate(getEndDate());
		commonLicenseKeyImpl.setFileName(getFileName());
		commonLicenseKeyImpl.setFileSize(getFileSize());

		commonLicenseKeyImpl.resetOriginalValues();

		return commonLicenseKeyImpl;
	}

	@Override
	public int compareTo(CommonLicenseKey commonLicenseKey) {
		int value = 0;

		value = DateUtil.compareTo(getEndDate(), commonLicenseKey.getEndDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommonLicenseKey)) {
			return false;
		}

		CommonLicenseKey commonLicenseKey = (CommonLicenseKey)object;

		long primaryKey = commonLicenseKey.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalProductGroup = _productGroup;

		_originalProductEnvironment = _productEnvironment;

		_originalProductVersion = _productVersion;

		_originalStartDate = _startDate;

		_originalEndDate = _endDate;

		_originalFileName = _fileName;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommonLicenseKey> toCacheModel() {
		CommonLicenseKeyCacheModel commonLicenseKeyCacheModel =
			new CommonLicenseKeyCacheModel();

		commonLicenseKeyCacheModel.mvccVersion = getMvccVersion();

		commonLicenseKeyCacheModel.uuid = getUuid();

		String uuid = commonLicenseKeyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commonLicenseKeyCacheModel.uuid = null;
		}

		commonLicenseKeyCacheModel.commonLicenseKeyId = getCommonLicenseKeyId();

		commonLicenseKeyCacheModel.companyId = getCompanyId();

		commonLicenseKeyCacheModel.userId = getUserId();

		commonLicenseKeyCacheModel.userName = getUserName();

		String userName = commonLicenseKeyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commonLicenseKeyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commonLicenseKeyCacheModel.createDate = createDate.getTime();
		}
		else {
			commonLicenseKeyCacheModel.createDate = Long.MIN_VALUE;
		}

		commonLicenseKeyCacheModel.productGroup = getProductGroup();

		String productGroup = commonLicenseKeyCacheModel.productGroup;

		if ((productGroup != null) && (productGroup.length() == 0)) {
			commonLicenseKeyCacheModel.productGroup = null;
		}

		commonLicenseKeyCacheModel.productEnvironment = getProductEnvironment();

		String productEnvironment =
			commonLicenseKeyCacheModel.productEnvironment;

		if ((productEnvironment != null) &&
			(productEnvironment.length() == 0)) {

			commonLicenseKeyCacheModel.productEnvironment = null;
		}

		commonLicenseKeyCacheModel.productVersion = getProductVersion();

		String productVersion = commonLicenseKeyCacheModel.productVersion;

		if ((productVersion != null) && (productVersion.length() == 0)) {
			commonLicenseKeyCacheModel.productVersion = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			commonLicenseKeyCacheModel.startDate = startDate.getTime();
		}
		else {
			commonLicenseKeyCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			commonLicenseKeyCacheModel.endDate = endDate.getTime();
		}
		else {
			commonLicenseKeyCacheModel.endDate = Long.MIN_VALUE;
		}

		commonLicenseKeyCacheModel.fileName = getFileName();

		String fileName = commonLicenseKeyCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			commonLicenseKeyCacheModel.fileName = null;
		}

		commonLicenseKeyCacheModel.fileSize = getFileSize();

		return commonLicenseKeyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommonLicenseKey, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommonLicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommonLicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommonLicenseKey)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommonLicenseKey, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommonLicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommonLicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CommonLicenseKey)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CommonLicenseKey>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CommonLicenseKey.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _commonLicenseKeyId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private String _productGroup;
	private String _originalProductGroup;
	private String _productEnvironment;
	private String _originalProductEnvironment;
	private String _productVersion;
	private String _originalProductVersion;
	private Date _startDate;
	private Date _originalStartDate;
	private Date _endDate;
	private Date _originalEndDate;
	private String _fileName;
	private String _originalFileName;
	private long _fileSize;
	private long _columnBitmask;
	private CommonLicenseKey _escapedModel;

}