/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.license.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.osb.provisioning.license.model.LicenseKey;
import com.liferay.osb.provisioning.license.model.LicenseKeyModel;
import com.liferay.osb.provisioning.license.model.LicenseKeySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LicenseKey service. Represents a row in the &quot;Provisioning_LicenseKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LicenseKeyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeyImpl
 * @generated
 */
@JSON(strict = true)
public class LicenseKeyModelImpl
	extends BaseModelImpl<LicenseKey> implements LicenseKeyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license key model instance should use the <code>LicenseKey</code> interface instead.
	 */
	public static final String TABLE_NAME = "Provisioning_LicenseKey";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"licenseKeyId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userUuid", Types.VARCHAR}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedUserUuid", Types.VARCHAR},
		{"modifiedUserName", Types.VARCHAR}, {"modifiedDate", Types.TIMESTAMP},
		{"assetReceiptLicenseUuid", Types.VARCHAR},
		{"accountKey", Types.VARCHAR}, {"productPurchaseKey", Types.VARCHAR},
		{"licenseEntryId", Types.BIGINT}, {"productKey", Types.VARCHAR},
		{"accountName", Types.VARCHAR}, {"licenseEntryName", Types.VARCHAR},
		{"licenseEntryType", Types.VARCHAR}, {"licenseVersion", Types.INTEGER},
		{"productName", Types.VARCHAR}, {"productId", Types.VARCHAR},
		{"productVersion", Types.VARCHAR}, {"clusterId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"owner", Types.VARCHAR},
		{"maxClusterNodes", Types.INTEGER}, {"maxServers", Types.INTEGER},
		{"maxConcurrentUsers", Types.BIGINT}, {"maxUsers", Types.BIGINT},
		{"maxHttpSessions", Types.INTEGER}, {"sizing", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"hostName", Types.VARCHAR},
		{"ipAddresses", Types.VARCHAR}, {"macAddresses", Types.VARCHAR},
		{"serverId", Types.VARCHAR}, {"key_", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"expirationDate", Types.TIMESTAMP},
		{"additionalInfo", Types.VARCHAR}, {"complimentary", Types.BOOLEAN},
		{"active_", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseKeyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedUserUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("assetReceiptLicenseUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productPurchaseKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseEntryName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseEntryType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenseVersion", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("productName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clusterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("owner", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("maxClusterNodes", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("maxServers", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("maxConcurrentUsers", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("maxUsers", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("maxHttpSessions", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sizing", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hostName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ipAddresses", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("macAddresses", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serverId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("key_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("additionalInfo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("complimentary", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Provisioning_LicenseKey (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,licenseKeyId LONG not null primary key,companyId LONG,userUuid VARCHAR(75) null,userName VARCHAR(75) null,createDate DATE null,modifiedUserUuid VARCHAR(75) null,modifiedUserName VARCHAR(75) null,modifiedDate DATE null,assetReceiptLicenseUuid VARCHAR(75) null,accountKey VARCHAR(75) null,productPurchaseKey VARCHAR(75) null,licenseEntryId LONG,productKey VARCHAR(75) null,accountName VARCHAR(500) null,licenseEntryName VARCHAR(75) null,licenseEntryType VARCHAR(75) null,licenseVersion INTEGER,productName VARCHAR(75) null,productId VARCHAR(75) null,productVersion VARCHAR(75) null,clusterId LONG,name VARCHAR(75) null,owner VARCHAR(75) null,maxClusterNodes INTEGER,maxServers INTEGER,maxConcurrentUsers LONG,maxUsers LONG,maxHttpSessions INTEGER,sizing VARCHAR(75) null,description VARCHAR(255) null,hostName VARCHAR(75) null,ipAddresses STRING null,macAddresses STRING null,serverId STRING null,key_ STRING null,startDate DATE null,expirationDate DATE null,additionalInfo STRING null,complimentary BOOLEAN,active_ BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table Provisioning_LicenseKey";

	public static final String ORDER_BY_JPQL =
		" ORDER BY licenseKey.active DESC, licenseKey.licenseKeyId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Provisioning_LicenseKey.active_ DESC, Provisioning_LicenseKey.licenseKeyId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long ASSETRECEIPTLICENSEUUID_COLUMN_BITMASK = 2L;

	public static final long CLUSTERID_COLUMN_BITMASK = 4L;

	public static final long COMPANYID_COLUMN_BITMASK = 8L;

	public static final long COMPLIMENTARY_COLUMN_BITMASK = 16L;

	public static final long PRODUCTID_COLUMN_BITMASK = 32L;

	public static final long PRODUCTNAME_COLUMN_BITMASK = 64L;

	public static final long PRODUCTPURCHASEKEY_COLUMN_BITMASK = 128L;

	public static final long SERVERID_COLUMN_BITMASK = 256L;

	public static final long UUID_COLUMN_BITMASK = 512L;

	public static final long LICENSEKEYID_COLUMN_BITMASK = 1024L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LicenseKey toModel(LicenseKeySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LicenseKey model = new LicenseKeyImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setLicenseKeyId(soapModel.getLicenseKeyId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserUuid(soapModel.getUserUuid());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedUserUuid(soapModel.getModifiedUserUuid());
		model.setModifiedUserName(soapModel.getModifiedUserName());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAssetReceiptLicenseUuid(
			soapModel.getAssetReceiptLicenseUuid());
		model.setAccountKey(soapModel.getAccountKey());
		model.setProductPurchaseKey(soapModel.getProductPurchaseKey());
		model.setLicenseEntryId(soapModel.getLicenseEntryId());
		model.setProductKey(soapModel.getProductKey());
		model.setAccountName(soapModel.getAccountName());
		model.setLicenseEntryName(soapModel.getLicenseEntryName());
		model.setLicenseEntryType(soapModel.getLicenseEntryType());
		model.setLicenseVersion(soapModel.getLicenseVersion());
		model.setProductName(soapModel.getProductName());
		model.setProductId(soapModel.getProductId());
		model.setProductVersion(soapModel.getProductVersion());
		model.setClusterId(soapModel.getClusterId());
		model.setName(soapModel.getName());
		model.setOwner(soapModel.getOwner());
		model.setMaxClusterNodes(soapModel.getMaxClusterNodes());
		model.setMaxServers(soapModel.getMaxServers());
		model.setMaxConcurrentUsers(soapModel.getMaxConcurrentUsers());
		model.setMaxUsers(soapModel.getMaxUsers());
		model.setMaxHttpSessions(soapModel.getMaxHttpSessions());
		model.setSizing(soapModel.getSizing());
		model.setDescription(soapModel.getDescription());
		model.setHostName(soapModel.getHostName());
		model.setIpAddresses(soapModel.getIpAddresses());
		model.setMacAddresses(soapModel.getMacAddresses());
		model.setServerId(soapModel.getServerId());
		model.setKey(soapModel.getKey());
		model.setStartDate(soapModel.getStartDate());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setAdditionalInfo(soapModel.getAdditionalInfo());
		model.setComplimentary(soapModel.isComplimentary());
		model.setActive(soapModel.isActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LicenseKey> toModels(LicenseKeySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LicenseKey> models = new ArrayList<LicenseKey>(soapModels.length);

		for (LicenseKeySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LicenseKeyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _licenseKeyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLicenseKeyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _licenseKeyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LicenseKey.class;
	}

	@Override
	public String getModelClassName() {
		return LicenseKey.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LicenseKey)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LicenseKey, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LicenseKey, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LicenseKey)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LicenseKey, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LicenseKey, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LicenseKey, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LicenseKey, Object>>();

		attributeGetterFunctions.put("mvccVersion", LicenseKey::getMvccVersion);
		attributeGetterFunctions.put("uuid", LicenseKey::getUuid);
		attributeGetterFunctions.put(
			"licenseKeyId", LicenseKey::getLicenseKeyId);
		attributeGetterFunctions.put("companyId", LicenseKey::getCompanyId);
		attributeGetterFunctions.put("userUuid", LicenseKey::getUserUuid);
		attributeGetterFunctions.put("userName", LicenseKey::getUserName);
		attributeGetterFunctions.put("createDate", LicenseKey::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedUserUuid", LicenseKey::getModifiedUserUuid);
		attributeGetterFunctions.put(
			"modifiedUserName", LicenseKey::getModifiedUserName);
		attributeGetterFunctions.put(
			"modifiedDate", LicenseKey::getModifiedDate);
		attributeGetterFunctions.put(
			"assetReceiptLicenseUuid", LicenseKey::getAssetReceiptLicenseUuid);
		attributeGetterFunctions.put("accountKey", LicenseKey::getAccountKey);
		attributeGetterFunctions.put(
			"productPurchaseKey", LicenseKey::getProductPurchaseKey);
		attributeGetterFunctions.put(
			"licenseEntryId", LicenseKey::getLicenseEntryId);
		attributeGetterFunctions.put("productKey", LicenseKey::getProductKey);
		attributeGetterFunctions.put("accountName", LicenseKey::getAccountName);
		attributeGetterFunctions.put(
			"licenseEntryName", LicenseKey::getLicenseEntryName);
		attributeGetterFunctions.put(
			"licenseEntryType", LicenseKey::getLicenseEntryType);
		attributeGetterFunctions.put(
			"licenseVersion", LicenseKey::getLicenseVersion);
		attributeGetterFunctions.put("productName", LicenseKey::getProductName);
		attributeGetterFunctions.put("productId", LicenseKey::getProductId);
		attributeGetterFunctions.put(
			"productVersion", LicenseKey::getProductVersion);
		attributeGetterFunctions.put("clusterId", LicenseKey::getClusterId);
		attributeGetterFunctions.put("name", LicenseKey::getName);
		attributeGetterFunctions.put("owner", LicenseKey::getOwner);
		attributeGetterFunctions.put(
			"maxClusterNodes", LicenseKey::getMaxClusterNodes);
		attributeGetterFunctions.put("maxServers", LicenseKey::getMaxServers);
		attributeGetterFunctions.put(
			"maxConcurrentUsers", LicenseKey::getMaxConcurrentUsers);
		attributeGetterFunctions.put("maxUsers", LicenseKey::getMaxUsers);
		attributeGetterFunctions.put(
			"maxHttpSessions", LicenseKey::getMaxHttpSessions);
		attributeGetterFunctions.put("sizing", LicenseKey::getSizing);
		attributeGetterFunctions.put("description", LicenseKey::getDescription);
		attributeGetterFunctions.put("hostName", LicenseKey::getHostName);
		attributeGetterFunctions.put("ipAddresses", LicenseKey::getIpAddresses);
		attributeGetterFunctions.put(
			"macAddresses", LicenseKey::getMacAddresses);
		attributeGetterFunctions.put("serverId", LicenseKey::getServerId);
		attributeGetterFunctions.put("key", LicenseKey::getKey);
		attributeGetterFunctions.put("startDate", LicenseKey::getStartDate);
		attributeGetterFunctions.put(
			"expirationDate", LicenseKey::getExpirationDate);
		attributeGetterFunctions.put(
			"additionalInfo", LicenseKey::getAdditionalInfo);
		attributeGetterFunctions.put(
			"complimentary", LicenseKey::getComplimentary);
		attributeGetterFunctions.put("active", LicenseKey::getActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<LicenseKey, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<LicenseKey, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LicenseKey, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<LicenseKey, Long>)LicenseKey::setMvccVersion);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<LicenseKey, String>)LicenseKey::setUuid);
		attributeSetterBiConsumers.put(
			"licenseKeyId",
			(BiConsumer<LicenseKey, Long>)LicenseKey::setLicenseKeyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LicenseKey, Long>)LicenseKey::setCompanyId);
		attributeSetterBiConsumers.put(
			"userUuid",
			(BiConsumer<LicenseKey, String>)LicenseKey::setUserUuid);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LicenseKey, String>)LicenseKey::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LicenseKey, Date>)LicenseKey::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedUserUuid",
			(BiConsumer<LicenseKey, String>)LicenseKey::setModifiedUserUuid);
		attributeSetterBiConsumers.put(
			"modifiedUserName",
			(BiConsumer<LicenseKey, String>)LicenseKey::setModifiedUserName);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LicenseKey, Date>)LicenseKey::setModifiedDate);
		attributeSetterBiConsumers.put(
			"assetReceiptLicenseUuid",
			(BiConsumer<LicenseKey, String>)
				LicenseKey::setAssetReceiptLicenseUuid);
		attributeSetterBiConsumers.put(
			"accountKey",
			(BiConsumer<LicenseKey, String>)LicenseKey::setAccountKey);
		attributeSetterBiConsumers.put(
			"productPurchaseKey",
			(BiConsumer<LicenseKey, String>)LicenseKey::setProductPurchaseKey);
		attributeSetterBiConsumers.put(
			"licenseEntryId",
			(BiConsumer<LicenseKey, Long>)LicenseKey::setLicenseEntryId);
		attributeSetterBiConsumers.put(
			"productKey",
			(BiConsumer<LicenseKey, String>)LicenseKey::setProductKey);
		attributeSetterBiConsumers.put(
			"accountName",
			(BiConsumer<LicenseKey, String>)LicenseKey::setAccountName);
		attributeSetterBiConsumers.put(
			"licenseEntryName",
			(BiConsumer<LicenseKey, String>)LicenseKey::setLicenseEntryName);
		attributeSetterBiConsumers.put(
			"licenseEntryType",
			(BiConsumer<LicenseKey, String>)LicenseKey::setLicenseEntryType);
		attributeSetterBiConsumers.put(
			"licenseVersion",
			(BiConsumer<LicenseKey, Integer>)LicenseKey::setLicenseVersion);
		attributeSetterBiConsumers.put(
			"productName",
			(BiConsumer<LicenseKey, String>)LicenseKey::setProductName);
		attributeSetterBiConsumers.put(
			"productId",
			(BiConsumer<LicenseKey, String>)LicenseKey::setProductId);
		attributeSetterBiConsumers.put(
			"productVersion",
			(BiConsumer<LicenseKey, String>)LicenseKey::setProductVersion);
		attributeSetterBiConsumers.put(
			"clusterId",
			(BiConsumer<LicenseKey, Long>)LicenseKey::setClusterId);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<LicenseKey, String>)LicenseKey::setName);
		attributeSetterBiConsumers.put(
			"owner", (BiConsumer<LicenseKey, String>)LicenseKey::setOwner);
		attributeSetterBiConsumers.put(
			"maxClusterNodes",
			(BiConsumer<LicenseKey, Integer>)LicenseKey::setMaxClusterNodes);
		attributeSetterBiConsumers.put(
			"maxServers",
			(BiConsumer<LicenseKey, Integer>)LicenseKey::setMaxServers);
		attributeSetterBiConsumers.put(
			"maxConcurrentUsers",
			(BiConsumer<LicenseKey, Long>)LicenseKey::setMaxConcurrentUsers);
		attributeSetterBiConsumers.put(
			"maxUsers", (BiConsumer<LicenseKey, Long>)LicenseKey::setMaxUsers);
		attributeSetterBiConsumers.put(
			"maxHttpSessions",
			(BiConsumer<LicenseKey, Integer>)LicenseKey::setMaxHttpSessions);
		attributeSetterBiConsumers.put(
			"sizing", (BiConsumer<LicenseKey, String>)LicenseKey::setSizing);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<LicenseKey, String>)LicenseKey::setDescription);
		attributeSetterBiConsumers.put(
			"hostName",
			(BiConsumer<LicenseKey, String>)LicenseKey::setHostName);
		attributeSetterBiConsumers.put(
			"ipAddresses",
			(BiConsumer<LicenseKey, String>)LicenseKey::setIpAddresses);
		attributeSetterBiConsumers.put(
			"macAddresses",
			(BiConsumer<LicenseKey, String>)LicenseKey::setMacAddresses);
		attributeSetterBiConsumers.put(
			"serverId",
			(BiConsumer<LicenseKey, String>)LicenseKey::setServerId);
		attributeSetterBiConsumers.put(
			"key", (BiConsumer<LicenseKey, String>)LicenseKey::setKey);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<LicenseKey, Date>)LicenseKey::setStartDate);
		attributeSetterBiConsumers.put(
			"expirationDate",
			(BiConsumer<LicenseKey, Date>)LicenseKey::setExpirationDate);
		attributeSetterBiConsumers.put(
			"additionalInfo",
			(BiConsumer<LicenseKey, String>)LicenseKey::setAdditionalInfo);
		attributeSetterBiConsumers.put(
			"complimentary",
			(BiConsumer<LicenseKey, Boolean>)LicenseKey::setComplimentary);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<LicenseKey, Boolean>)LicenseKey::setActive);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLicenseKeyId() {
		return _licenseKeyId;
	}

	@Override
	public void setLicenseKeyId(long licenseKeyId) {
		_columnBitmask = -1L;

		_licenseKeyId = licenseKeyId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public String getUserUuid() {
		if (_userUuid == null) {
			return "";
		}
		else {
			return _userUuid;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public String getModifiedUserUuid() {
		if (_modifiedUserUuid == null) {
			return "";
		}
		else {
			return _modifiedUserUuid;
		}
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@JSON
	@Override
	public String getModifiedUserName() {
		if (_modifiedUserName == null) {
			return "";
		}
		else {
			return _modifiedUserName;
		}
	}

	@Override
	public void setModifiedUserName(String modifiedUserName) {
		_modifiedUserName = modifiedUserName;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getAssetReceiptLicenseUuid() {
		if (_assetReceiptLicenseUuid == null) {
			return "";
		}
		else {
			return _assetReceiptLicenseUuid;
		}
	}

	@Override
	public void setAssetReceiptLicenseUuid(String assetReceiptLicenseUuid) {
		_columnBitmask |= ASSETRECEIPTLICENSEUUID_COLUMN_BITMASK;

		if (_originalAssetReceiptLicenseUuid == null) {
			_originalAssetReceiptLicenseUuid = _assetReceiptLicenseUuid;
		}

		_assetReceiptLicenseUuid = assetReceiptLicenseUuid;
	}

	public String getOriginalAssetReceiptLicenseUuid() {
		return GetterUtil.getString(_originalAssetReceiptLicenseUuid);
	}

	@JSON
	@Override
	public String getAccountKey() {
		if (_accountKey == null) {
			return "";
		}
		else {
			return _accountKey;
		}
	}

	@Override
	public void setAccountKey(String accountKey) {
		_accountKey = accountKey;
	}

	@JSON
	@Override
	public String getProductPurchaseKey() {
		if (_productPurchaseKey == null) {
			return "";
		}
		else {
			return _productPurchaseKey;
		}
	}

	@Override
	public void setProductPurchaseKey(String productPurchaseKey) {
		_columnBitmask |= PRODUCTPURCHASEKEY_COLUMN_BITMASK;

		if (_originalProductPurchaseKey == null) {
			_originalProductPurchaseKey = _productPurchaseKey;
		}

		_productPurchaseKey = productPurchaseKey;
	}

	public String getOriginalProductPurchaseKey() {
		return GetterUtil.getString(_originalProductPurchaseKey);
	}

	@JSON
	@Override
	public long getLicenseEntryId() {
		return _licenseEntryId;
	}

	@Override
	public void setLicenseEntryId(long licenseEntryId) {
		_licenseEntryId = licenseEntryId;
	}

	@JSON
	@Override
	public String getProductKey() {
		if (_productKey == null) {
			return "";
		}
		else {
			return _productKey;
		}
	}

	@Override
	public void setProductKey(String productKey) {
		_productKey = productKey;
	}

	@JSON
	@Override
	public String getAccountName() {
		if (_accountName == null) {
			return "";
		}
		else {
			return _accountName;
		}
	}

	@Override
	public void setAccountName(String accountName) {
		_accountName = accountName;
	}

	@JSON
	@Override
	public String getLicenseEntryName() {
		if (_licenseEntryName == null) {
			return "";
		}
		else {
			return _licenseEntryName;
		}
	}

	@Override
	public void setLicenseEntryName(String licenseEntryName) {
		_licenseEntryName = licenseEntryName;
	}

	@JSON
	@Override
	public String getLicenseEntryType() {
		if (_licenseEntryType == null) {
			return "";
		}
		else {
			return _licenseEntryType;
		}
	}

	@Override
	public void setLicenseEntryType(String licenseEntryType) {
		_licenseEntryType = licenseEntryType;
	}

	@JSON
	@Override
	public int getLicenseVersion() {
		return _licenseVersion;
	}

	@Override
	public void setLicenseVersion(int licenseVersion) {
		_licenseVersion = licenseVersion;
	}

	@JSON
	@Override
	public String getProductName() {
		if (_productName == null) {
			return "";
		}
		else {
			return _productName;
		}
	}

	@Override
	public void setProductName(String productName) {
		_columnBitmask |= PRODUCTNAME_COLUMN_BITMASK;

		if (_originalProductName == null) {
			_originalProductName = _productName;
		}

		_productName = productName;
	}

	public String getOriginalProductName() {
		return GetterUtil.getString(_originalProductName);
	}

	@JSON
	@Override
	public String getProductId() {
		if (_productId == null) {
			return "";
		}
		else {
			return _productId;
		}
	}

	@Override
	public void setProductId(String productId) {
		_columnBitmask |= PRODUCTID_COLUMN_BITMASK;

		if (_originalProductId == null) {
			_originalProductId = _productId;
		}

		_productId = productId;
	}

	public String getOriginalProductId() {
		return GetterUtil.getString(_originalProductId);
	}

	@JSON
	@Override
	public String getProductVersion() {
		if (_productVersion == null) {
			return "";
		}
		else {
			return _productVersion;
		}
	}

	@Override
	public void setProductVersion(String productVersion) {
		_productVersion = productVersion;
	}

	@JSON
	@Override
	public long getClusterId() {
		return _clusterId;
	}

	@Override
	public void setClusterId(long clusterId) {
		_columnBitmask |= CLUSTERID_COLUMN_BITMASK;

		if (!_setOriginalClusterId) {
			_setOriginalClusterId = true;

			_originalClusterId = _clusterId;
		}

		_clusterId = clusterId;
	}

	public long getOriginalClusterId() {
		return _originalClusterId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getOwner() {
		if (_owner == null) {
			return "";
		}
		else {
			return _owner;
		}
	}

	@Override
	public void setOwner(String owner) {
		_owner = owner;
	}

	@JSON
	@Override
	public int getMaxClusterNodes() {
		return _maxClusterNodes;
	}

	@Override
	public void setMaxClusterNodes(int maxClusterNodes) {
		_maxClusterNodes = maxClusterNodes;
	}

	@JSON
	@Override
	public int getMaxServers() {
		return _maxServers;
	}

	@Override
	public void setMaxServers(int maxServers) {
		_maxServers = maxServers;
	}

	@JSON
	@Override
	public long getMaxConcurrentUsers() {
		return _maxConcurrentUsers;
	}

	@Override
	public void setMaxConcurrentUsers(long maxConcurrentUsers) {
		_maxConcurrentUsers = maxConcurrentUsers;
	}

	@JSON
	@Override
	public long getMaxUsers() {
		return _maxUsers;
	}

	@Override
	public void setMaxUsers(long maxUsers) {
		_maxUsers = maxUsers;
	}

	@JSON
	@Override
	public int getMaxHttpSessions() {
		return _maxHttpSessions;
	}

	@Override
	public void setMaxHttpSessions(int maxHttpSessions) {
		_maxHttpSessions = maxHttpSessions;
	}

	@JSON
	@Override
	public String getSizing() {
		if (_sizing == null) {
			return "";
		}
		else {
			return _sizing;
		}
	}

	@Override
	public void setSizing(String sizing) {
		_sizing = sizing;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getHostName() {
		if (_hostName == null) {
			return "";
		}
		else {
			return _hostName;
		}
	}

	@Override
	public void setHostName(String hostName) {
		_hostName = hostName;
	}

	@JSON
	@Override
	public String getIpAddresses() {
		if (_ipAddresses == null) {
			return "";
		}
		else {
			return _ipAddresses;
		}
	}

	@Override
	public void setIpAddresses(String ipAddresses) {
		_ipAddresses = ipAddresses;
	}

	@JSON
	@Override
	public String getMacAddresses() {
		if (_macAddresses == null) {
			return "";
		}
		else {
			return _macAddresses;
		}
	}

	@Override
	public void setMacAddresses(String macAddresses) {
		_macAddresses = macAddresses;
	}

	@JSON
	@Override
	public String getServerId() {
		if (_serverId == null) {
			return "";
		}
		else {
			return _serverId;
		}
	}

	@Override
	public void setServerId(String serverId) {
		_columnBitmask |= SERVERID_COLUMN_BITMASK;

		if (_originalServerId == null) {
			_originalServerId = _serverId;
		}

		_serverId = serverId;
	}

	public String getOriginalServerId() {
		return GetterUtil.getString(_originalServerId);
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_key = key;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public String getAdditionalInfo() {
		if (_additionalInfo == null) {
			return "";
		}
		else {
			return _additionalInfo;
		}
	}

	@Override
	public void setAdditionalInfo(String additionalInfo) {
		_additionalInfo = additionalInfo;
	}

	@JSON
	@Override
	public boolean getComplimentary() {
		return _complimentary;
	}

	@JSON
	@Override
	public boolean isComplimentary() {
		return _complimentary;
	}

	@Override
	public void setComplimentary(boolean complimentary) {
		_columnBitmask |= COMPLIMENTARY_COLUMN_BITMASK;

		if (!_setOriginalComplimentary) {
			_setOriginalComplimentary = true;

			_originalComplimentary = _complimentary;
		}

		_complimentary = complimentary;
	}

	public boolean getOriginalComplimentary() {
		return _originalComplimentary;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask = -1L;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LicenseKey.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LicenseKey.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LicenseKey toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LicenseKey>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LicenseKeyImpl licenseKeyImpl = new LicenseKeyImpl();

		licenseKeyImpl.setMvccVersion(getMvccVersion());
		licenseKeyImpl.setUuid(getUuid());
		licenseKeyImpl.setLicenseKeyId(getLicenseKeyId());
		licenseKeyImpl.setCompanyId(getCompanyId());
		licenseKeyImpl.setUserUuid(getUserUuid());
		licenseKeyImpl.setUserName(getUserName());
		licenseKeyImpl.setCreateDate(getCreateDate());
		licenseKeyImpl.setModifiedUserUuid(getModifiedUserUuid());
		licenseKeyImpl.setModifiedUserName(getModifiedUserName());
		licenseKeyImpl.setModifiedDate(getModifiedDate());
		licenseKeyImpl.setAssetReceiptLicenseUuid(getAssetReceiptLicenseUuid());
		licenseKeyImpl.setAccountKey(getAccountKey());
		licenseKeyImpl.setProductPurchaseKey(getProductPurchaseKey());
		licenseKeyImpl.setLicenseEntryId(getLicenseEntryId());
		licenseKeyImpl.setProductKey(getProductKey());
		licenseKeyImpl.setAccountName(getAccountName());
		licenseKeyImpl.setLicenseEntryName(getLicenseEntryName());
		licenseKeyImpl.setLicenseEntryType(getLicenseEntryType());
		licenseKeyImpl.setLicenseVersion(getLicenseVersion());
		licenseKeyImpl.setProductName(getProductName());
		licenseKeyImpl.setProductId(getProductId());
		licenseKeyImpl.setProductVersion(getProductVersion());
		licenseKeyImpl.setClusterId(getClusterId());
		licenseKeyImpl.setName(getName());
		licenseKeyImpl.setOwner(getOwner());
		licenseKeyImpl.setMaxClusterNodes(getMaxClusterNodes());
		licenseKeyImpl.setMaxServers(getMaxServers());
		licenseKeyImpl.setMaxConcurrentUsers(getMaxConcurrentUsers());
		licenseKeyImpl.setMaxUsers(getMaxUsers());
		licenseKeyImpl.setMaxHttpSessions(getMaxHttpSessions());
		licenseKeyImpl.setSizing(getSizing());
		licenseKeyImpl.setDescription(getDescription());
		licenseKeyImpl.setHostName(getHostName());
		licenseKeyImpl.setIpAddresses(getIpAddresses());
		licenseKeyImpl.setMacAddresses(getMacAddresses());
		licenseKeyImpl.setServerId(getServerId());
		licenseKeyImpl.setKey(getKey());
		licenseKeyImpl.setStartDate(getStartDate());
		licenseKeyImpl.setExpirationDate(getExpirationDate());
		licenseKeyImpl.setAdditionalInfo(getAdditionalInfo());
		licenseKeyImpl.setComplimentary(isComplimentary());
		licenseKeyImpl.setActive(isActive());

		licenseKeyImpl.resetOriginalValues();

		return licenseKeyImpl;
	}

	@Override
	public int compareTo(LicenseKey licenseKey) {
		int value = 0;

		value = Boolean.compare(isActive(), licenseKey.isActive());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		if (getLicenseKeyId() < licenseKey.getLicenseKeyId()) {
			value = -1;
		}
		else if (getLicenseKeyId() > licenseKey.getLicenseKeyId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LicenseKey)) {
			return false;
		}

		LicenseKey licenseKey = (LicenseKey)object;

		long primaryKey = licenseKey.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_setModifiedDate = false;
		_originalAssetReceiptLicenseUuid = _assetReceiptLicenseUuid;

		_originalProductPurchaseKey = _productPurchaseKey;

		_originalProductName = _productName;

		_originalProductId = _productId;

		_originalClusterId = _clusterId;

		_setOriginalClusterId = false;

		_originalServerId = _serverId;

		_originalComplimentary = _complimentary;

		_setOriginalComplimentary = false;

		_originalActive = _active;

		_setOriginalActive = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LicenseKey> toCacheModel() {
		LicenseKeyCacheModel licenseKeyCacheModel = new LicenseKeyCacheModel();

		licenseKeyCacheModel.mvccVersion = getMvccVersion();

		licenseKeyCacheModel.uuid = getUuid();

		String uuid = licenseKeyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			licenseKeyCacheModel.uuid = null;
		}

		licenseKeyCacheModel.licenseKeyId = getLicenseKeyId();

		licenseKeyCacheModel.companyId = getCompanyId();

		licenseKeyCacheModel.userUuid = getUserUuid();

		String userUuid = licenseKeyCacheModel.userUuid;

		if ((userUuid != null) && (userUuid.length() == 0)) {
			licenseKeyCacheModel.userUuid = null;
		}

		licenseKeyCacheModel.userName = getUserName();

		String userName = licenseKeyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			licenseKeyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			licenseKeyCacheModel.createDate = createDate.getTime();
		}
		else {
			licenseKeyCacheModel.createDate = Long.MIN_VALUE;
		}

		licenseKeyCacheModel.modifiedUserUuid = getModifiedUserUuid();

		String modifiedUserUuid = licenseKeyCacheModel.modifiedUserUuid;

		if ((modifiedUserUuid != null) && (modifiedUserUuid.length() == 0)) {
			licenseKeyCacheModel.modifiedUserUuid = null;
		}

		licenseKeyCacheModel.modifiedUserName = getModifiedUserName();

		String modifiedUserName = licenseKeyCacheModel.modifiedUserName;

		if ((modifiedUserName != null) && (modifiedUserName.length() == 0)) {
			licenseKeyCacheModel.modifiedUserName = null;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			licenseKeyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			licenseKeyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		licenseKeyCacheModel.assetReceiptLicenseUuid =
			getAssetReceiptLicenseUuid();

		String assetReceiptLicenseUuid =
			licenseKeyCacheModel.assetReceiptLicenseUuid;

		if ((assetReceiptLicenseUuid != null) &&
			(assetReceiptLicenseUuid.length() == 0)) {

			licenseKeyCacheModel.assetReceiptLicenseUuid = null;
		}

		licenseKeyCacheModel.accountKey = getAccountKey();

		String accountKey = licenseKeyCacheModel.accountKey;

		if ((accountKey != null) && (accountKey.length() == 0)) {
			licenseKeyCacheModel.accountKey = null;
		}

		licenseKeyCacheModel.productPurchaseKey = getProductPurchaseKey();

		String productPurchaseKey = licenseKeyCacheModel.productPurchaseKey;

		if ((productPurchaseKey != null) &&
			(productPurchaseKey.length() == 0)) {

			licenseKeyCacheModel.productPurchaseKey = null;
		}

		licenseKeyCacheModel.licenseEntryId = getLicenseEntryId();

		licenseKeyCacheModel.productKey = getProductKey();

		String productKey = licenseKeyCacheModel.productKey;

		if ((productKey != null) && (productKey.length() == 0)) {
			licenseKeyCacheModel.productKey = null;
		}

		licenseKeyCacheModel.accountName = getAccountName();

		String accountName = licenseKeyCacheModel.accountName;

		if ((accountName != null) && (accountName.length() == 0)) {
			licenseKeyCacheModel.accountName = null;
		}

		licenseKeyCacheModel.licenseEntryName = getLicenseEntryName();

		String licenseEntryName = licenseKeyCacheModel.licenseEntryName;

		if ((licenseEntryName != null) && (licenseEntryName.length() == 0)) {
			licenseKeyCacheModel.licenseEntryName = null;
		}

		licenseKeyCacheModel.licenseEntryType = getLicenseEntryType();

		String licenseEntryType = licenseKeyCacheModel.licenseEntryType;

		if ((licenseEntryType != null) && (licenseEntryType.length() == 0)) {
			licenseKeyCacheModel.licenseEntryType = null;
		}

		licenseKeyCacheModel.licenseVersion = getLicenseVersion();

		licenseKeyCacheModel.productName = getProductName();

		String productName = licenseKeyCacheModel.productName;

		if ((productName != null) && (productName.length() == 0)) {
			licenseKeyCacheModel.productName = null;
		}

		licenseKeyCacheModel.productId = getProductId();

		String productId = licenseKeyCacheModel.productId;

		if ((productId != null) && (productId.length() == 0)) {
			licenseKeyCacheModel.productId = null;
		}

		licenseKeyCacheModel.productVersion = getProductVersion();

		String productVersion = licenseKeyCacheModel.productVersion;

		if ((productVersion != null) && (productVersion.length() == 0)) {
			licenseKeyCacheModel.productVersion = null;
		}

		licenseKeyCacheModel.clusterId = getClusterId();

		licenseKeyCacheModel.name = getName();

		String name = licenseKeyCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			licenseKeyCacheModel.name = null;
		}

		licenseKeyCacheModel.owner = getOwner();

		String owner = licenseKeyCacheModel.owner;

		if ((owner != null) && (owner.length() == 0)) {
			licenseKeyCacheModel.owner = null;
		}

		licenseKeyCacheModel.maxClusterNodes = getMaxClusterNodes();

		licenseKeyCacheModel.maxServers = getMaxServers();

		licenseKeyCacheModel.maxConcurrentUsers = getMaxConcurrentUsers();

		licenseKeyCacheModel.maxUsers = getMaxUsers();

		licenseKeyCacheModel.maxHttpSessions = getMaxHttpSessions();

		licenseKeyCacheModel.sizing = getSizing();

		String sizing = licenseKeyCacheModel.sizing;

		if ((sizing != null) && (sizing.length() == 0)) {
			licenseKeyCacheModel.sizing = null;
		}

		licenseKeyCacheModel.description = getDescription();

		String description = licenseKeyCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			licenseKeyCacheModel.description = null;
		}

		licenseKeyCacheModel.hostName = getHostName();

		String hostName = licenseKeyCacheModel.hostName;

		if ((hostName != null) && (hostName.length() == 0)) {
			licenseKeyCacheModel.hostName = null;
		}

		licenseKeyCacheModel.ipAddresses = getIpAddresses();

		String ipAddresses = licenseKeyCacheModel.ipAddresses;

		if ((ipAddresses != null) && (ipAddresses.length() == 0)) {
			licenseKeyCacheModel.ipAddresses = null;
		}

		licenseKeyCacheModel.macAddresses = getMacAddresses();

		String macAddresses = licenseKeyCacheModel.macAddresses;

		if ((macAddresses != null) && (macAddresses.length() == 0)) {
			licenseKeyCacheModel.macAddresses = null;
		}

		licenseKeyCacheModel.serverId = getServerId();

		String serverId = licenseKeyCacheModel.serverId;

		if ((serverId != null) && (serverId.length() == 0)) {
			licenseKeyCacheModel.serverId = null;
		}

		licenseKeyCacheModel.key = getKey();

		String key = licenseKeyCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			licenseKeyCacheModel.key = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			licenseKeyCacheModel.startDate = startDate.getTime();
		}
		else {
			licenseKeyCacheModel.startDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			licenseKeyCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			licenseKeyCacheModel.expirationDate = Long.MIN_VALUE;
		}

		licenseKeyCacheModel.additionalInfo = getAdditionalInfo();

		String additionalInfo = licenseKeyCacheModel.additionalInfo;

		if ((additionalInfo != null) && (additionalInfo.length() == 0)) {
			licenseKeyCacheModel.additionalInfo = null;
		}

		licenseKeyCacheModel.complimentary = isComplimentary();

		licenseKeyCacheModel.active = isActive();

		return licenseKeyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LicenseKey)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LicenseKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LicenseKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LicenseKey)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LicenseKey>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LicenseKey.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _licenseKeyId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private String _modifiedUserUuid;
	private String _modifiedUserName;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _assetReceiptLicenseUuid;
	private String _originalAssetReceiptLicenseUuid;
	private String _accountKey;
	private String _productPurchaseKey;
	private String _originalProductPurchaseKey;
	private long _licenseEntryId;
	private String _productKey;
	private String _accountName;
	private String _licenseEntryName;
	private String _licenseEntryType;
	private int _licenseVersion;
	private String _productName;
	private String _originalProductName;
	private String _productId;
	private String _originalProductId;
	private String _productVersion;
	private long _clusterId;
	private long _originalClusterId;
	private boolean _setOriginalClusterId;
	private String _name;
	private String _owner;
	private int _maxClusterNodes;
	private int _maxServers;
	private long _maxConcurrentUsers;
	private long _maxUsers;
	private int _maxHttpSessions;
	private String _sizing;
	private String _description;
	private String _hostName;
	private String _ipAddresses;
	private String _macAddresses;
	private String _serverId;
	private String _originalServerId;
	private String _key;
	private Date _startDate;
	private Date _expirationDate;
	private String _additionalInfo;
	private boolean _complimentary;
	private boolean _originalComplimentary;
	private boolean _setOriginalComplimentary;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private long _columnBitmask;
	private LicenseKey _escapedModel;

}