/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.license.model.impl;

import com.liferay.osb.provisioning.license.model.LicenseEntry;
import com.liferay.osb.provisioning.license.service.LicenseEntryLocalServiceUtil;

/**
 * The extended model base implementation for the LicenseEntry service. Represents a row in the &quot;Provisioning_LicenseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseEntryImpl
 * @see LicenseEntry
 * @generated
 */
public abstract class LicenseEntryBaseImpl
	extends LicenseEntryModelImpl implements LicenseEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license entry model instance should use the <code>LicenseEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LicenseEntryLocalServiceUtil.addLicenseEntry(this);
		}
		else {
			LicenseEntryLocalServiceUtil.updateLicenseEntry(this);
		}
	}

}