/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.license.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.provisioning.license.model.LicenseEntry;
import com.liferay.osb.provisioning.license.model.LicenseEntryModel;
import com.liferay.osb.provisioning.license.model.LicenseEntrySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LicenseEntry service. Represents a row in the &quot;Provisioning_LicenseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LicenseEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseEntryImpl
 * @generated
 */
@JSON(strict = true)
public class LicenseEntryModelImpl
	extends BaseModelImpl<LicenseEntry> implements LicenseEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license entry model instance should use the <code>LicenseEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "Provisioning_LicenseEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"licenseEntryId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"productKey", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"type_", Types.VARCHAR}, {"versionMin", Types.VARCHAR},
		{"versionMax", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("licenseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("productKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("versionMin", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("versionMax", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Provisioning_LicenseEntry (mvccVersion LONG default 0 not null,licenseEntryId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,productKey VARCHAR(75) null,name VARCHAR(75) null,type_ VARCHAR(75) null,versionMin VARCHAR(75) null,versionMax VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Provisioning_LicenseEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY licenseEntry.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Provisioning_LicenseEntry.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long NAME_COLUMN_BITMASK = 1L;

	public static final long PRODUCTKEY_COLUMN_BITMASK = 2L;

	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LicenseEntry toModel(LicenseEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LicenseEntry model = new LicenseEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setLicenseEntryId(soapModel.getLicenseEntryId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProductKey(soapModel.getProductKey());
		model.setName(soapModel.getName());
		model.setType(soapModel.getType());
		model.setVersionMin(soapModel.getVersionMin());
		model.setVersionMax(soapModel.getVersionMax());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LicenseEntry> toModels(LicenseEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LicenseEntry> models = new ArrayList<LicenseEntry>(
			soapModels.length);

		for (LicenseEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LicenseEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _licenseEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLicenseEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _licenseEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LicenseEntry.class;
	}

	@Override
	public String getModelClassName() {
		return LicenseEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LicenseEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LicenseEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LicenseEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LicenseEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LicenseEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LicenseEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LicenseEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LicenseEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LicenseEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<LicenseEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LicenseEntry, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", LicenseEntry::getMvccVersion);
		attributeGetterFunctions.put(
			"licenseEntryId", LicenseEntry::getLicenseEntryId);
		attributeGetterFunctions.put("userId", LicenseEntry::getUserId);
		attributeGetterFunctions.put("userName", LicenseEntry::getUserName);
		attributeGetterFunctions.put("createDate", LicenseEntry::getCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LicenseEntry::getModifiedDate);
		attributeGetterFunctions.put("productKey", LicenseEntry::getProductKey);
		attributeGetterFunctions.put("name", LicenseEntry::getName);
		attributeGetterFunctions.put("type", LicenseEntry::getType);
		attributeGetterFunctions.put("versionMin", LicenseEntry::getVersionMin);
		attributeGetterFunctions.put("versionMax", LicenseEntry::getVersionMax);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<LicenseEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<LicenseEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LicenseEntry, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<LicenseEntry, Long>)LicenseEntry::setMvccVersion);
		attributeSetterBiConsumers.put(
			"licenseEntryId",
			(BiConsumer<LicenseEntry, Long>)LicenseEntry::setLicenseEntryId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<LicenseEntry, Long>)LicenseEntry::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LicenseEntry, String>)LicenseEntry::setUserName);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LicenseEntry, Date>)LicenseEntry::setCreateDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LicenseEntry, Date>)LicenseEntry::setModifiedDate);
		attributeSetterBiConsumers.put(
			"productKey",
			(BiConsumer<LicenseEntry, String>)LicenseEntry::setProductKey);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<LicenseEntry, String>)LicenseEntry::setName);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<LicenseEntry, String>)LicenseEntry::setType);
		attributeSetterBiConsumers.put(
			"versionMin",
			(BiConsumer<LicenseEntry, String>)LicenseEntry::setVersionMin);
		attributeSetterBiConsumers.put(
			"versionMax",
			(BiConsumer<LicenseEntry, String>)LicenseEntry::setVersionMax);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getLicenseEntryId() {
		return _licenseEntryId;
	}

	@Override
	public void setLicenseEntryId(long licenseEntryId) {
		_licenseEntryId = licenseEntryId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getProductKey() {
		if (_productKey == null) {
			return "";
		}
		else {
			return _productKey;
		}
	}

	@Override
	public void setProductKey(String productKey) {
		_columnBitmask |= PRODUCTKEY_COLUMN_BITMASK;

		if (_originalProductKey == null) {
			_originalProductKey = _productKey;
		}

		_productKey = productKey;
	}

	public String getOriginalProductKey() {
		return GetterUtil.getString(_originalProductKey);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (_originalType == null) {
			_originalType = _type;
		}

		_type = type;
	}

	public String getOriginalType() {
		return GetterUtil.getString(_originalType);
	}

	@JSON
	@Override
	public String getVersionMin() {
		if (_versionMin == null) {
			return "";
		}
		else {
			return _versionMin;
		}
	}

	@Override
	public void setVersionMin(String versionMin) {
		_versionMin = versionMin;
	}

	@JSON
	@Override
	public String getVersionMax() {
		if (_versionMax == null) {
			return "";
		}
		else {
			return _versionMax;
		}
	}

	@Override
	public void setVersionMax(String versionMax) {
		_versionMax = versionMax;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LicenseEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LicenseEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LicenseEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LicenseEntryImpl licenseEntryImpl = new LicenseEntryImpl();

		licenseEntryImpl.setMvccVersion(getMvccVersion());
		licenseEntryImpl.setLicenseEntryId(getLicenseEntryId());
		licenseEntryImpl.setUserId(getUserId());
		licenseEntryImpl.setUserName(getUserName());
		licenseEntryImpl.setCreateDate(getCreateDate());
		licenseEntryImpl.setModifiedDate(getModifiedDate());
		licenseEntryImpl.setProductKey(getProductKey());
		licenseEntryImpl.setName(getName());
		licenseEntryImpl.setType(getType());
		licenseEntryImpl.setVersionMin(getVersionMin());
		licenseEntryImpl.setVersionMax(getVersionMax());

		licenseEntryImpl.resetOriginalValues();

		return licenseEntryImpl;
	}

	@Override
	public int compareTo(LicenseEntry licenseEntry) {
		int value = 0;

		value = getName().compareToIgnoreCase(licenseEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LicenseEntry)) {
			return false;
		}

		LicenseEntry licenseEntry = (LicenseEntry)object;

		long primaryKey = licenseEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
		_originalProductKey = _productKey;

		_originalName = _name;

		_originalType = _type;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LicenseEntry> toCacheModel() {
		LicenseEntryCacheModel licenseEntryCacheModel =
			new LicenseEntryCacheModel();

		licenseEntryCacheModel.mvccVersion = getMvccVersion();

		licenseEntryCacheModel.licenseEntryId = getLicenseEntryId();

		licenseEntryCacheModel.userId = getUserId();

		licenseEntryCacheModel.userName = getUserName();

		String userName = licenseEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			licenseEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			licenseEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			licenseEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			licenseEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			licenseEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		licenseEntryCacheModel.productKey = getProductKey();

		String productKey = licenseEntryCacheModel.productKey;

		if ((productKey != null) && (productKey.length() == 0)) {
			licenseEntryCacheModel.productKey = null;
		}

		licenseEntryCacheModel.name = getName();

		String name = licenseEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			licenseEntryCacheModel.name = null;
		}

		licenseEntryCacheModel.type = getType();

		String type = licenseEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			licenseEntryCacheModel.type = null;
		}

		licenseEntryCacheModel.versionMin = getVersionMin();

		String versionMin = licenseEntryCacheModel.versionMin;

		if ((versionMin != null) && (versionMin.length() == 0)) {
			licenseEntryCacheModel.versionMin = null;
		}

		licenseEntryCacheModel.versionMax = getVersionMax();

		String versionMax = licenseEntryCacheModel.versionMax;

		if ((versionMax != null) && (versionMax.length() == 0)) {
			licenseEntryCacheModel.versionMax = null;
		}

		return licenseEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LicenseEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LicenseEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LicenseEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LicenseEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LicenseEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LicenseEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LicenseEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LicenseEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LicenseEntry.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private long _licenseEntryId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _productKey;
	private String _originalProductKey;
	private String _name;
	private String _originalName;
	private String _type;
	private String _originalType;
	private String _versionMin;
	private String _versionMax;
	private long _columnBitmask;
	private LicenseEntry _escapedModel;

}