ci.test.auto.recipients=\
    brianchandotcom[relevant:sf]

ci.test.auto.senders.blacklist=liferay-continuous-integration

ci.test.available.suites=\
    acceptance,\
    acceptance-functional,\
    acceptance-upstream,\
    analytics-cloud,\
    analytics-cloud-acceptance,\
    analytics-cloud-quarantine,\
    auto-tagging,\
    backend,\
    backend-hypersonic,\
    blade,\
    blogs,\
    bulk-editing,\
    bundle,\
    calendar,\
    clustering,\
    commerce,\
    commerce-es7,\
    commerce-es7-remote,\
    commerce-remote,\
    content-page-review,\
    data-engine,\
    dl-store,\
    document,\
    echo,\
    echo-upgrade,\
    environments,\
    export-import,\
    forms,\
    frontend,\
    gauntlet,\
    gauntlet-bucket,\
    gradle-plugins,\
    jacoco-report,\
    jdk11,\
    jsf,\
    knowledge-base,\
    ldap,\
    license,\
    license-cluster,\
    lima,\
    lima-upgrade,\
    lpkg,\
    message-boards,\
    oauth2,\
    onedrive,\
    online-editing,\
    poshi-release,\
    relevant,\
    saml,\
    search,\
    search-es7,\
    search-es7-remote,\
    search-es7-remote-jdk11,\
    search-es7-remote-minimum,\
    search-remote,\
    search-remote-jdk11,\
    search-remote-minimum,\
    search-solr,\
    search-solr8,\
    security,\
    seo,\
    sf,\
    sharepoint,\
    sharing,\
    site-template,\
    stable,\
    staging,\
    sybase,\
    tango-analytics-cloud,\
    tck,\
    um,\
    um-db-partition,\
    upgrade,\
    upgrade-all,\
    upgrade-client,\
    upstream-functional,\
    users,\
    wiki,\
    workflow,\
    workflow-es7,\
    workflow-es7-remote,\
    workflow-remote

ci.test.relevant.bypass.file.path.patterns=\
    .*/(ci|test).properties$,\
    .*/packageinfo$,\
    .*\\.function$,\
    .*\\.macro$,\
    .*\\.path$,\
    .*\\.prose$,\
    .*\\.testcase$

ci.test.suite.description[acceptance]=Test acceptance tests.
ci.test.suite.description[acceptance-functional]=Test acceptance functional tests.
ci.test.suite.description[acceptance-upstream]=Test acceptance upstream tests.
ci.test.suite.description[auto-tagging]=Test Auto Tagging tests.
ci.test.suite.description[backend]=Test only backend tests.
ci.test.suite.description[backend-hypersonic]=Test only backend tests on Hypersonic.
ci.test.suite.description[blade]=Test only Blade samples tests.
ci.test.suite.description[blogs]=Test all upstream Blogs tests.
ci.test.suite.description[bulk-editing]=Test Bulk Editing tests.
ci.test.suite.description[bundle]=Saves a compiled tomcat bundle.
ci.test.suite.description[calendar]=Test only calendar tests.
ci.test.suite.description[clustering]=Test only clustering.
ci.test.suite.description[commerce]=Test only Commerce tests.
ci.test.suite.description[commerce-es7]=Test only Commerce test with the Elasticsearch 7 search engine.
ci.test.suite.description[commerce-es7-remote]=Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
ci.test.suite.description[commerce-remote]=Test only Commerce tests with the latest compatible remote Elasticsearch 6 version.
ci.test.suite.description[content-page-review]=Run Content Page Review (comments) tests.
ci.test.suite.description[data-engine]=Test Data Engine functional tests (ddl scripts).
ci.test.suite.description[dl-store]=Run Document Library Store tests.
ci.test.suite.description[document]=Test all upstream Document and Media tests.
ci.test.suite.description[echo]=Test all Echo (WCM) team tests.
ci.test.suite.description[echo-upgrade]=Test Echo (WCM) team upgrade tests.
ci.test.suite.description[environments]=Test environment acceptance functional tests on all available environment stacks.
ci.test.suite.description[export-import]=Test only exportimport tests.
ci.test.suite.description[forms]=Test only forms tests.
ci.test.suite.description[frontend]=Test frontend tests.
ci.test.suite.description[gauntlet]=Test upstream tests.
ci.test.suite.description[gauntlet-bucket]=Test a subset of upstream tests.
ci.test.suite.description[gradle-plugins]=Test only Gradle Plugins tests.
ci.test.suite.description[jacoco-report]=Test integration and unit tests to generate JaCoCo reports.
ci.test.suite.description[jdk11]=Test acceptance, smoke, and upgrade functional tests against JDK11.
ci.test.suite.description[jsf]=Test only Liferay Faces tests.
ci.test.suite.description[ldap]=Test only LDAP tests.
ci.test.suite.description[license]=Compile a release bundle and execute tests for licensing.
ci.test.suite.description[license-cluster]=Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
ci.test.suite.description[lima]=Test Lima tests.
ci.test.suite.description[lima-upgrade]=Test Lima upgrade tests.
ci.test.suite.description[lpkg]=Test only LPKG tests.
ci.test.suite.description[oauth2]=Test only OAuth 2 tests.
ci.test.suite.description[onedrive]=Test OneDrive tests.
ci.test.suite.description[online-editing]=Test Online Editing tests.
ci.test.suite.description[relevant]=Test relevant changes only.
ci.test.suite.description[saml]=Test only SAML tests.
ci.test.suite.description[search]=Test only search tests with the Elasticsearch 6 search engine.
ci.test.suite.description[search-es7]=Test only search tests with the Elasticsearch 7 search engine.
ci.test.suite.description[search-es7-remote]=Test only search tests with the latest compatible remote Elasticsearch 7 version.
ci.test.suite.description[search-es7-remote-jdk11]=Test only search tests with the latest compatible remote Elasticsearch 7 version and OpenJDK 11.
ci.test.suite.description[search-es7-remote-minimum]=Test only search tests with the minimum compatible remote Elasticsearch 7 version.
ci.test.suite.description[search-remote]=Test only search tests with the latest compatible remote Elasticsearch 6 version.
ci.test.suite.description[search-remote-jdk11]=Test only search tests with the latest compatible remote Elasticsearch 6 version and OpenJDK 11.
ci.test.suite.description[search-remote-minimum]=Test only search tests with the minimum compatible remote Elasticsearch 6 version.
ci.test.suite.description[search-solr]=Test only search tests with the Solr 7 search engine.
ci.test.suite.description[search-solr8]=Test only search tests with the Solr 8 search engine.
ci.test.suite.description[security]=Test only security tests.
ci.test.suite.description[seo]=Test SEO tests.
ci.test.suite.description[sf]=Test with only source formatter.
ci.test.suite.description[sharepoint]=Test Sharepoint 2010 tests.
ci.test.suite.description[sharing]=Test DM Asset Sharing tests.
ci.test.suite.description[site-template]=Test Site Template tests.
ci.test.suite.description[staging]=Test all Staging components tests.
ci.test.suite.description[sybase]=Test functional and integration tests on Sybase database.
ci.test.suite.description[tango-analytics-cloud]=Test segmentation and personalization with Analytics Cloud.
ci.test.suite.description[tck]=Test only TCK tests.
ci.test.suite.description[upgrade]=Test upgrades against tomcat app server and all supported databases.
ci.test.suite.description[upgrade-all]=Test upgrades from all components against all app servers and databases.
ci.test.suite.description[upgrade-client]=Test only upgrade client.
ci.test.suite.description[upstream-functional]=Test upstream functional tests.
ci.test.suite.description[users]=Test Users and Organizations tests.
ci.test.suite.description[um]=Test User Management tests.
ci.test.suite.description[wiki]=Test wiki tests.
ci.test.suite.description[workflow]=Test only workflow tests.
ci.test.suite.description[workflow-es7]=Test only workflow tests with the Elasticsearch 7 search engine.
ci.test.suite.description[workflow-es7-remote]=Test only workflow tests with the latest compatible remote Elasticsearch 7 version.
ci.test.suite.description[workflow-remote]=Test only workflow tests with the latest compatible remote Elasticsearch 6 version.

jira.project.keys=\
    APIO,\
    BLADE,\
    CEREBRO,\
    CLDSVCS,\
    COMMERCE,\
    EMP,\
    FARO,\
    IDE,\
    ISOPS,\
    ISSD,\
    ISSUP,\
    LCD,\
    LOOP,\
    LPD,\
    LPS,\
    LRAC,\
    LRCI,\
    LRDCOM,\
    LRDOCS,\
    LRIS,\
    LRQA,\
    OAUTH2,\
    POSHI,\
    RELEASE,\
    SYNC,\
    TR,\
    WCM