ci.test.auto.recipients=\
    brianchandotcom[relevant:sf]

ci.test.auto.senders.blacklist=liferay-continuous-integration

ci.test.available.suites=\
    acceptance,\
    acceptance-functional,\
    acceptance-upstream,\
    analytics-cloud,\
    analytics-cloud-acceptance,\
    analytics-cloud-quarantine,\
    backend,\
    blade,\
    blogs,\
    bundle,\
    data-engine,\
    document,\
    echo,\
    echo-upgrade,\
    environments,\
    forms,\
    frontend,\
    gauntlet,\
    gauntlet-bucket,\
    jacoco-report,\
    jsf,\
    knowledge-base,\
    license,\
    license-cluster,\
    lima,\
    lima-upgrade,\
    lpkg,\
    message-boards,\
    poshi-release,\
    relevant,\
    search,\
    search-es6,\
    search-es6-remote,\
    search-es6-remote-minimum,\
    search-remote,\
    search-solr,\
    security,\
    sf,\
    stable,\
    staging,\
    tango-analytics-cloud,\
    tck,\
    upgrade,\
    upgrade-all,\
    upstream-functional,\
    users,\
    wiki,\
    workflow

ci.test.relevant.bypass.file.path.patterns=\
    .*/(ci|test).properties$,\
    .*/packageinfo$,\
    .*\\.function$,\
    .*\\.macro$,\
    .*\\.path$,\
    .*\\.prose$,\
    .*\\.testcase$

ci.test.suite.description[acceptance]=Test acceptance tests.
ci.test.suite.description[acceptance-functional]=Test acceptance functional tests.
ci.test.suite.description[acceptance-upstream]=Test acceptance upstream tests.
ci.test.suite.description[blade]=Test only Blade samples tests.
ci.test.suite.description[bundle]=Saves a compiled tomcat bundle.
ci.test.suite.description[data-engine]=Test Data Engine functional tests (ddl scripts).
ci.test.suite.description[echo]=Test all Echo (WCM) team tests.
ci.test.suite.description[echo-upgrade]=Test Echo (WCM) team upgrade tests.
ci.test.suite.description[environments]=Test environment acceptance functional tests on all available environment stacks.
ci.test.suite.description[forms]=Test only forms tests.
ci.test.suite.description[frontend]=Test frontend tests.
ci.test.suite.description[gauntlet]=Test all tests.
ci.test.suite.description[gauntlet-bucket]=Test a subset of upstream tests.
ci.test.suite.description[jacoco-report]=Test integration and unit tests to generate JaCoCo reports.
ci.test.suite.description[jsf]=Test only Liferay Faces tests.
ci.test.suite.description[license]=Compile a release bundle and execute tests for licensing.
ci.test.suite.description[license-cluster]=Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
ci.test.suite.description[lima]=Test Lima tests.
ci.test.suite.description[lima-upgrade]=Test Lima upgrade tests.
ci.test.suite.description[lpkg]=Test only LPKG tests.
ci.test.suite.description[relevant]=Test relevant changes only.
ci.test.suite.description[search]=Test only search tests with the Elasticsearch 2 search engine.
ci.test.suite.description[search-es6]=Test only search tests with the Elasticsearch 6 search engine.
ci.test.suite.description[search-es6-remote]=Test only search tests with the latest compatible remote Elasticsearch 6 version.
ci.test.suite.description[search-es6-remote-minimum]=Test only search tests with the minimum compatible remote Elasticsearch 6 version.
ci.test.suite.description[search-remote]=Test only search tests with the latest compatible remote Elasticsearch 2 version.
ci.test.suite.description[search-solr]=Test only search tests with the Solr search engine.
ci.test.suite.description[security]=Test security tests.
ci.test.suite.description[sf]=Test with only source formatter.
ci.test.suite.description[stable]=Test only the tests that define stability.
ci.test.suite.description[staging]=Test only staging tests.
ci.test.suite.description[tango-analytics-cloud]=Test segmentation and personalization with Analytics Cloud.
ci.test.suite.description[tck]=Test only TCK tests.
ci.test.suite.description[upgrade]=Test upgrades against tomcat app server and all supported databases.
ci.test.suite.description[upgrade-all]=Test upgrades from all components against all app servers and databases.
ci.test.suite.description[upstream-functional]=Test upstream functional tests.
ci.test.suite.description[users]=Test Users and Organizations tests.
ci.test.suite.description[wiki]=Test wiki tests.
ci.test.suite.description[workflow]=Test only workflow tests.

jira.project.keys=\
    APIO,\
    ASAH,\
    BLADE,\
    CEREBRO,\
    CLDSVCS,\
    COMMERCE,\
    EMP,\
    FARO,\
    IDE,\
    ISOPS,\
    ISSD,\
    ISSUP,\
    LCD,\
    LOOP,\
    LPD,\
    LPS,\
    LRAC,\
    LRCI,\
    LRDCOM,\
    LRDOCS,\
    LRIS,\
    LRQA,\
    OAUTH2,\
    POSHI,\
    RELEASE,\
    SYNC,\
    TR,\
    WCM