dependencies {
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.13.2"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.13.2"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.13.2.2"
	compileInclude group: "com.liferay", name: "com.liferay.petra.json.web.service.client", version: "7.1.0"
	compileInclude group: "org.apache.httpcomponents", name: "httpasyncclient", version: "4.1.3"
	compileInclude group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.13"
	compileInclude group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.6"
	compileInclude group: "org.apache.httpcomponents", name: "httpcore-nio", version: "4.4.6"
	compileInclude group: "org.apache.httpcomponents", name: "httpmime", version: "4.3.6"
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.6.0"
	compileOnly group: "javax.mail", name: "mail", version: "1.4"
	compileOnly group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-legacy:osb-customer-legacy-web-service-api")
}