fragment geolocationFragment on Metric {
	geolocation {
		value
		valueKey
	}
}

query WebContentMetrics($assetId: String!, $channelId: String, $devices: String, $location: String, $rangeEnd: String, $rangeKey: Int, $rangeStart: String, $title: String, $touchpoint: String) {
	journal(assetId: $assetId, canonicalUrl: $touchpoint, channelId: $channelId, country: $location, deviceType: $devices, rangeEnd: $rangeEnd, rangeKey: $rangeKey, rangeStart: $rangeStart, title: $title) {
		assetId
		assetTitle
		viewsMetric {
			...geolocationFragment
		}
	}
}