INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'SmartPhone', '1', 'Android', TIMESTAMP '${today-2dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'SmartPhone', '2', 'Android', TIMESTAMP '${today-2dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Edge', 1, 'SmartPhone', '3', 'Android', TIMESTAMP '${today-5dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Firefox', 1, 'SmartPhone', '4', 'Android', TIMESTAMP '${today-5dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'Tablet', '5', 'Android', TIMESTAMP '${today-10dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Firefox', 1, 'Tablet', '6', 'Android', TIMESTAMP '${today-12dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Safari', 1, 'SmartPhone', '7', 'Android', TIMESTAMP '${today-2dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Safari', 1, 'SmartPhone', '8', 'Android', TIMESTAMP '${today-8dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'Desktop', '9', 'MacOS', TIMESTAMP '${today-14dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Firefox', 1, 'Desktop', '10', 'Ubuntu', TIMESTAMP '${today-10dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Safari', 1, 'Desktop', '11', 'Linux', TIMESTAMP '${today-2dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Default Browser', 1, 'Desktop', '12', 'Win10', TIMESTAMP '${today-2dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Edge', 1, 'Desktop', '13', 'Win10', TIMESTAMP '${today-6dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Default Browser', 1, 'Desktop', '14', 'Win10', TIMESTAMP '${today-16dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Android WebView', 1, 'Desktop', '15', 'Ubuntu', TIMESTAMP '${today-3dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'Desktop', '16', 'Ubuntu', TIMESTAMP '${today-7dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'SmartPhone', '17', 'Android', TIMESTAMP '${today-9dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Headless Chrome', 1, 'SmartPhone', '18', 'Android', TIMESTAMP '${today-11dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Samsung Browser', 1, 'Tablet', '19', 'Android', TIMESTAMP '${today-13dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Chrome', 1, 'Desktop', '20', 'Win10', TIMESTAMP '${today-25dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Firefox', 1, 'Desktop', '21', 'Win10', TIMESTAMP '${today-32dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Puffin', 1, 'Desktop', '22', 'Win10', TIMESTAMP '${today-38dT11:50:00.000Z}');
INSERT INTO Session(browserName, channelId, deviceType, id, platformName, sessionStart) VALUES('Edge', 1, 'Desktop', '23', 'MacOS', TIMESTAMP '${today-45dT11:50:00.000Z}');