dependencies {
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testImplementation project(":apps:forms-and-workflow:dynamic-data-lists:dynamic-data-lists-api")
	testImplementation project(":apps:forms-and-workflow:dynamic-data-lists:dynamic-data-lists-service")
	testImplementation project(":apps:forms-and-workflow:dynamic-data-lists:dynamic-data-lists-web")
	testImplementation project(":apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-api")
	testImplementation project(":apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-io")
	testImplementation project(":apps:web-experience:export-import:export-import-api")
	testImplementation project(":apps:web-experience:export-import:export-import-service")
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-test-util")
	testIntegrationImplementation project(":core:registry-api")
}