import com.liferay.gradle.util.FileUtil

import com.pswidersk.gradle.python.PythonPlugin
import com.pswidersk.gradle.python.VenvTask

buildscript {
	dependencies {
		classpath group: "com.pswidersk", name: "python-gradle-plugin", version: "2.3.0"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

configure(subprojects.findAll { FileUtil.exists(it, "src/main/python")}) {
	repositories {
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}

	apply plugin: PythonPlugin
	apply plugin: "com.liferay.source.formatter"
	apply plugin: "eclipse"
	apply plugin: "idea"

	task installIndirectEnvDependencies(type: VenvTask)
	task installPackageDependencies(type: VenvTask)
	task installProjectEnvDependencies(type: VenvTask)
	task installTestEnvDependencies(type: VenvTask)
	task packagePython(type: VenvTask)
	task testPython(type: VenvTask)
	task zipPython(type: VenvTask)

	String pythonSource = "src/main/python"
	String pythonTempDir = "$buildDir/python-temp"
	String pythonTestSource = "src/test/python"

	installIndirectEnvDependencies {
		args = ["install", "--isolated", "-r", "$projectDir/$pythonSource/indirect-requirements.txt"]
		venvExec = "pip"
	}

	installPackageDependencies {
		args = ["install", "--isolated", "-r", "$projectDir/$pythonSource/requirements-package.txt", "--target", pythonTempDir]
		venvExec = "pip"
	}

	installProjectEnvDependencies {
		dependsOn installIndirectEnvDependencies

		args = ["install", "--isolated", "-r", "$projectDir/$pythonSource/requirements.txt"]

		if (FileUtil.exists(project, "$pythonSource/constraints.txt")) {
			args += ["-c", "$projectDir/$pythonSource/constraints.txt"]
		}

		venvExec = "pip"
	}

	installTestEnvDependencies {
		args = ["install", "--isolated", "-r", "$projectDir/$pythonTestSource/requirements.txt"]
		venvExec = "pip"
	}

	packagePython {
		dependsOn installPackageDependencies
		dependsOn installProjectEnvDependencies

		finalizedBy zipPython

		doLast {
			copy {
				exclude "requirements-package.txt"
				from pythonSource
				into pythonTempDir
			}

			File buildLibs = new File("$buildDir/libs")

			if (!buildLibs.exists()) {
				buildLibs.mkdirs()
			}
		}
	}

	pythonPlugin {
		condaVersion.set("py37_4.9.2")
		pythonVersion.set("3.7.9")
	}

	testPython {
		args = ["$projectDir/$pythonTestSource/", "--capture=no", "--disable-warnings", "--suppress-no-test-exit-code"]

		dependsOn installProjectEnvDependencies
		dependsOn installTestEnvDependencies

		environment = ["PYTHONPATH": file("src/main")]
		venvExec = "pytest"
		workingDir = file("src/test")
	}

	zipPython {
		args = ["-m", "zipapp", pythonTempDir, "-o", "$buildDir/libs/${project.name}.zip"]
		venvExec = "python"

		doLast {
			copy {
				from pythonSource + "/__main__.py"
				into "$buildDir/libs"
				rename "(.*)__main__.py", "\$1osb-asah-spark-python-driver.py"
			}

			delete pythonTempDir
		}
	}

	task assemble {
		dependsOn packagePython
	}

	task clean {
		delete buildDir
	}

	task test {
		dependsOn testPython
	}
}