import com.github.spotbugs.snom.SpotBugsPlugin
import com.github.spotbugs.snom.SpotBugsTask

import com.liferay.gradle.util.FileUtil

import org.gradle.testing.jacoco.tasks.JacocoReport

import org.kt3k.gradle.plugin.CoverallsPlugin

buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
		classpath group: "gradle.plugin.org.kt3k.gradle.plugin", name: "coveralls-gradle-plugin", version: "2.10.0"
	}

	repositories {
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: CoverallsPlugin

ext {
	set("commons-lang3.version", "3.13.0")
}

task jacocoRootReport(type: JacocoReport)
task jacocoTestCoverageVerification(type: JacocoCoverageVerification)

Set<Project> javaSubprojects = subprojects.findAll {
	FileUtil.exists(it, "src/main/java")
}

allprojects {
	apply plugin: JacocoPlugin
	apply plugin: SpotBugsPlugin
	apply plugin: "pmd"

	jacoco {
		toolVersion = "0.8.12"
	}

	pmd {
		incrementalAnalysis = false
		toolVersion = "5.8.1"
	}

	spotbugs {
		showProgress = true
		toolVersion = "4.8.6"
	}

	tasks.withType(SpotBugsTask) {
		dependencies {
			spotbugsPlugins group: "com.h3xstream.findsecbugs", name: "findsecbugs-plugin", version: "1.13.0"
		}

		String customConfigFile = rootDir.toString() + "/find-security-bugs-config.txt"

		if (FileUtil.exists(project, "find-security-bugs-false-positives.txt")) {
			customConfigFile += File.pathSeparator + projectDir + "/find-security-bugs-false-positives.txt";
		}

		String pathTraversalDetector = rootDir.toString() + "/find-security-bugs-PathTraversalDetector-PATH_TRAVERSAL_OUT.txt|PATH_TRAVERSAL_OUT"

		jvmArgs = [
			"-Dfindsecbugs.taint.customconfigfile=" + customConfigFile,
			"-Dfindsecbugs.injection.customconfigfile.PathTraversalDetector=" + pathTraversalDetector
		]

		if (FileUtil.exists(project, "spotbugs-exclude.xml")) {
			excludeFilter = file("spotbugs-exclude.xml")
		}

		File reportFile = null

		reports {
			html {
				enabled = true
				stylesheet = "fancy-hist.xsl"
			}

			reportFile = html.destination
		}

		doFirst {
			logger.lifecycle "Creating report: {}", reportFile
		}
	}
}

configure(javaSubprojects) {
	apply plugin: "com.liferay.source.formatter"
	apply plugin: "com.liferay.test.integration.base"
	apply plugin: "eclipse"
	apply plugin: "java"

	configurations {
		testIntegrationCompile.extendsFrom testCompile
		testIntegrationRuntime.extendsFrom testRuntime
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}

	test {
		ignoreFailures = false

		jacoco {
			destinationFile = new File(buildDir, "jacoco/jacocoTest.exec")
			enabled = false
			excludes = ["**/joestelmach/natty/**", "**/maxmind/geoip/**"]
		}

		testLogging {
			events = ["failed", "passed", "skipped", "standardError", "started"]
			exceptionFormat = "full"
			showCauses = true
			showExceptions = true
			showStackTraces = true
		}

		useJUnitPlatform()
	}

	testIntegration {
		ignoreFailures = false

		jacoco {
			destinationFile = new File(buildDir, "jacoco/jacocoIntegrationTest.exec")
			enabled = false
			excludes = ["**/joestelmach/natty/**"]
		}

		testLogging {
			events = ["failed", "passed", "skipped", "standardError", "started"]
			exceptionFormat = "full"
			showCauses = true
			showExceptions = true
			showStackTraces = true
		}

		useJUnitPlatform()
	}
}

coveralls {
	jacocoReportPath = "${rootDir}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml"

	sourceDirs = files(javaSubprojects.sourceSets.main.allSource.srcDirs).collect {
		file -> file.absolutePath
	}
}

jacocoRootReport {
	additionalSourceDirs.from = files(javaSubprojects.sourceSets.main.allSource.srcDirs)
	classDirectories.from = files(javaSubprojects.sourceSets.main.output)

	Set<JacocoTaskExtension> testJacocoTaskExtensions = javaSubprojects.test.jacoco.findAll {
		it.enabled
	}

	Set<JacocoTaskExtension> testIntegrationJacocoTaskExtensions = javaSubprojects.testIntegration.jacoco.findAll {
		it.enabled
	}

	executionData.from = files(testJacocoTaskExtensions.destinationFile, testIntegrationJacocoTaskExtensions.destinationFile)

	sourceDirectories.from = files(javaSubprojects.sourceSets.main.allSource.srcDirs)

	afterEvaluate {
		classDirectories.from = files(
			classDirectories.files.collect {
				fileTree(
					dir: it,
					exclude: [
						"**/*Mock*",
						"**/constants/*",
						"**/exception/*Exception*",
						"**/test/util/*"
					])
				})
		}

		reports {
			csv.required = false
			html.required = true
			xml.required = true
		}
	}

	jacocoTestCoverageVerification {
		classDirectories.from = files(javaSubprojects.sourceSets.main.output)

		Set<JacocoTaskExtension> testJacocoTaskExtensions = javaSubprojects.test.jacoco.findAll {
			it.enabled
		}

		Set<JacocoTaskExtension> testIntegrationJacocoTaskExtensions = javaSubprojects.testIntegration.jacoco.findAll {
			it.enabled
		}

		executionData.from = files(testJacocoTaskExtensions.destinationFile, testIntegrationJacocoTaskExtensions.destinationFile)

		violationRules {
			rule {
				limit {
					counter = 'LINE'
					minimum = 0.4200
					value = 'COVEREDRATIO'
				}
			}
		}
	}

	tasks.coveralls {
		dependsOn jacocoRootReport
	}