buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
		classpath group: "org.springframework.boot", name: "spring-boot-gradle-plugin", version: "3.4.7"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.root.defaults.plugin"

apply from: "build-ext.gradle"
apply from: "build-ext-coverage.gradle"
apply from: "build-ext-idea.gradle"
apply from: "build-ext-python.gradle"