pipeline {
	agent any

	environment {
		IMAGE_NAME = "liferaycloud/com-liferay-osb-asah-private"
		IMAGE_TAG_SUFFIX = "${sh(script: 'date +%Y%m%d', returnStdout: true).trim()}-${sh(script: 'git rev-parse --short ${GIT_COMMIT}', returnStdout: true).trim()}"
	}

	stages {
		stage('Build') {
			steps {
				sh './gradlew clean assemble'
			}
		}

		stage('Build Docker Images') {
			parallel {
				stage('osb-asah-backend') {
					steps {
						dir('osb-asah-backend') {
							script {
								withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
									osbAsahBackendImage = docker.build("${IMAGE_NAME}:osb-asah-backend-${IMAGE_TAG_SUFFIX}", '--no-cache -f ./Dockerfile ./')

	                                osbAsahBackendImage.push()
	                            }
							}
						}
					}
				}

				stage('osb-asah-batch-curator') {
					steps {
						dir('osb-asah-batch-curator') {
							script {
								withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
									osbAsahBatchCuratorImage = docker.build("${IMAGE_NAME}:osb-asah-batch-curator-${IMAGE_TAG_SUFFIX}", '--no-cache -f ./Dockerfile ./')

									osbAsahBatchCuratorImage.push()
								}
							}
						}
					}
				}

				stage('osb-asah-publisher') {
					steps {
						dir('osb-asah-publisher') {
							script {
								withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
									osbAsahPublisherImage = docker.build("${IMAGE_NAME}:osb-asah-publisher-${IMAGE_TAG_SUFFIX}", '--no-cache -f ./Dockerfile ./')

									osbAsahPublisherImage.push()
								}
							}
						}
					}
				}

				stage('osb-asah-stream-curator') {
					steps {
						dir('osb-asah-stream-curator') {
							script {
								withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
									osbAsahStreamCuratorImage = docker.build("${IMAGE_NAME}:osb-asah-stream-curator-${IMAGE_TAG_SUFFIX}", '--no-cache -f ./Dockerfile ./')

									osbAsahStreamCuratorImage.push()
								}
							}
						}
					}
				}

				stage('osb-asah-upgrade') {
					steps {
						dir('osb-asah-upgrade') {
							script {
								withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
									osbAsahUpgradeImage = docker.build("${IMAGE_NAME}:osb-asah-upgrade-${IMAGE_TAG_SUFFIX}", '--no-cache -f ./Dockerfile ./')

									osbAsahUpgradeImage.push()
								}
							}
						}
					}
				}
			}
		}
	}
}