pipeline {
	agent any

	environment {
		GIT_HASH = "${sh(script: 'git rev-parse --short=7 ${GIT_COMMIT}', returnStdout: true).trim()}"

		LABEL_BUILD_DATE = "${sh(script: 'date -u +%Y-%m-%dT%H:%M:%SZ', returnStdout: true).trim()}"
		IMAGE_NAME = "liferaycloud/com-liferay-osb-asah-private"
		IMAGE_TAG_SUFFIX = "${sh(script: 'date +%Y%m%d', returnStdout: true).trim()}-${GIT_HASH}"

		DOCKER_BUILD_ARGS = "--build-arg GIT_HASH=${GIT_HASH} --build-arg LABEL_BUILD_DATE=${LABEL_BUILD_DATE} --build-arg LABEL_VCS_REF=${GIT_COMMIT} --no-cache -f ./Dockerfile ./"
	}

	stages {
		stage('Build') {
			steps {
				sh './gradlew clean assemble -Dinclude.spark.python=true'

				dir('osb-asah-spark-python') {
					sh 'cp -R build docker-resources/build'

					sh 'mkdir -p docker-resources/src/main'

					sh 'cp -R src/main/resources docker-resources/src/main'
				}
			}
		}

		stage('Build Docker Images') {
			steps {
				dir('osb-asah-backend') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahBackendImage = docker.build(
								"${IMAGE_NAME}:osb-asah-backend-${IMAGE_TAG_SUFFIX}",
								"${DOCKER_BUILD_ARGS}")

                            osbAsahBackendImage.push()
                        }
					}
				}

				dir('osb-asah-batch-curator') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahBatchCuratorImage = docker.build(
								"${IMAGE_NAME}:osb-asah-batch-curator-${IMAGE_TAG_SUFFIX}",
								 "${DOCKER_BUILD_ARGS}")

							osbAsahBatchCuratorImage.push()
						}
					}
				}

				dir('osb-asah-composer') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahComposerImage = docker.build(
								"${IMAGE_NAME}:osb-asah-composer-${IMAGE_TAG_SUFFIX}",
								 "${DOCKER_BUILD_ARGS}")

							osbAsahComposerImage.push()
						}
					}
				}

				dir('osb-asah-publisher') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahPublisherImage = docker.build(
								"${IMAGE_NAME}:osb-asah-publisher-${IMAGE_TAG_SUFFIX}",
								"${DOCKER_BUILD_ARGS}")

							osbAsahPublisherImage.push()
						}
					}
				}

				dir('osb-asah-spark-python') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahSparkPythonImage = docker.build(
								"${IMAGE_NAME}:osb-asah-spark-python-${IMAGE_TAG_SUFFIX}",
								"${DOCKER_BUILD_ARGS}")

							osbAsahSparkPythonImage.push()
						}
					}
				}

				dir('osb-asah-stream-curator') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahStreamCuratorImage = docker.build(
								"${IMAGE_NAME}:osb-asah-stream-curator-${IMAGE_TAG_SUFFIX}", 
								"${DOCKER_BUILD_ARGS}")

							osbAsahStreamCuratorImage.push()
						}
					}
				}

				dir('osb-asah-upgrade') {
					script {
						withDockerRegistry([credentialsId: "dockerhub", url: ""]) {
							osbAsahUpgradeImage = docker.build(
								"${IMAGE_NAME}:osb-asah-upgrade-${IMAGE_TAG_SUFFIX}",
								"${DOCKER_BUILD_ARGS}")

							osbAsahUpgradeImage.push()
						}
					}
				}
			}
		}
	}
}