String projectPathPrefix = properties["project.path.prefix"]

rootDir.eachDirRecurse {
	File subprojectDir ->

	File srcDir = new File(subprojectDir, "src")

	if (!srcDir.exists()) {
		return
	}

	if (!subprojectDir.name.equals("dataflow-emulator") && !subprojectDir.name.startsWith("osb-asah")) {
		return
	}

	if (gradle.startParameter.taskNames.contains("assemble") && (subprojectDir.name.equals("osb-asah-composer") || (subprojectDir.name.equals("osb-asah-spark-python") && !Boolean.getBoolean("include.spark.python")))) {
		return
	}

	String subprojectName = "${projectPathPrefix}:${subprojectDir.name}"

	include subprojectName

	ProjectDescriptor projectDescriptor = project(subprojectName)

	projectDescriptor.projectDir = subprojectDir
}