buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
		classpath group: "gradle.plugin.io.gatling.gradle", name: "gatling-gradle-plugin", version: "3.9.5.6"
		classpath group: "org.springframework.boot", name: "spring-boot-gradle-plugin", version: "3.4.3"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.settings.plugin"

apply from: "settings-ext.gradle"