INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '1', TIMESTAMP  '${today-400d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '2', TIMESTAMP '${today-387d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '3', TIMESTAMP '${today-367d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '4', TIMESTAMP '${today-364d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '5', TIMESTAMP '${today-100d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '6', TIMESTAMP '${today-20d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '7', TIMESTAMP '${today-1d}');
INSERT INTO Session(channelId, id, sessionStart) VALUES(1, '8', TIMESTAMP '${today}');

INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', DATE(TIMESTAMP  '${today-400d}'), '1');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', DATE(TIMESTAMP '${today-387d}'), '2');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', DATE(TIMESTAMP '${today-367d}'), '3');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', DATE(TIMESTAMP '${today-364d}'), '4');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', DATE(TIMESTAMP '${today-100d}'), '5');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', DATE(TIMESTAMP '${today-20d}'), '6');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'holistic roi', DATE(TIMESTAMP '${today-1d}'), '7');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'engineer', DATE(TIMESTAMP '${today}'), '8');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, FALSE, 'error', DATE(TIMESTAMP '${today}'), '8');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'intuitive', DATE(TIMESTAMP '${today}'), '8');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'models', DATE(TIMESTAMP '${today}'), '8');