INSERT INTO IdentityActivitySummary (activitiesCount, channelId, dataSourceId, eventId, firstActivityDate, identityId, individualId, lastActivityDate) VALUES (1, 1, 1, 'webContentViewed', TIMESTAMP '2023-11-04T17:10:00.666Z', '1', '1', TIMESTAMP '2023-11-04T17:10:00.666Z');
INSERT INTO IdentityActivitySummary (activitiesCount, channelId, dataSourceId, eventId, firstActivityDate, identityId, individualId, lastActivityDate) VALUES (2, 1, 1, 'webContentViewed', TIMESTAMP '2023-11-04T17:10:00.666Z', '2', '2', TIMESTAMP '2023-11-04T17:10:00.666Z');
INSERT INTO IdentityActivitySummary (activitiesCount, channelId, dataSourceId, eventId, firstActivityDate, identityId, individualId, lastActivityDate) VALUES (3, 1, 1, 'webContentViewed', TIMESTAMP '2023-11-04T17:10:00.666Z', '3', '3', TIMESTAMP '2023-11-04T17:10:00.666Z');
INSERT INTO IdentityActivitySummary (activitiesCount, channelId, dataSourceId, eventId, firstActivityDate, identityId, individualId, lastActivityDate) VALUES (4, 1, 1, 'pageLoaded', TIMESTAMP '2023-11-04T17:10:00.666Z', '4', '4', TIMESTAMP '2023-11-04T17:10:00.666Z');

INSERT INTO Identity_Raw (id, individualId) VALUES ('1', '1');
INSERT INTO Identity_Raw (id, individualId) VALUES ('2', '2');
INSERT INTO Identity_Raw (id, individualId) VALUES ('3', '3');
INSERT INTO Identity_Raw (id, individualId) VALUES ('4', '4');

INSERT INTO Individual (emailAddress, fields, firstName, id, jobTitle, lastName) VALUES ('test1@liferay.com', ARRAY<STRUCT<dataSourceId INT64, name STRING, value String>> [(1, 'emailAddress', 'test1@liferay.com'), (1, 'firstName', 'Test 1'), (1, 'jobTitle', 'Software Engineer'), (1, 'lastName', 'Test 1')], 'Test 1', '1', 'Software Engineer', 'Test 1');
INSERT INTO Individual (emailAddress, fields, firstName, id, jobTitle, lastName) VALUES ('test2@liferay.com', ARRAY<STRUCT<dataSourceId INT64, name STRING, value String>> [(1, 'emailAddress', 'test2@liferay.com'), (1, 'firstName', 'Test 2'), (1, 'jobTitle', 'QA'), (1, 'lastName', 'Test 2')], 'Test 2', '2', 'QA', 'Test 2');
INSERT INTO Individual (emailAddress, fields, firstName, id, jobTitle, lastName) VALUES ('test3@liferay.com', ARRAY<STRUCT<dataSourceId INT64, name STRING, value String>> [(1, 'emailAddress', 'test3@liferay.com'), (1, 'firstName', 'Test 3'), (1, 'jobTitle', 'Project Manager'), (1, 'lastName', 'Test 3')], 'Test 3', '3', 'Project Manager', 'Test 3');
INSERT INTO Individual (emailAddress, fields, firstName, id, jobTitle, lastName) VALUES ('test4@liferay.com', ARRAY<STRUCT<dataSourceId INT64, name STRING, value String>> [(1, 'emailAddress', 'test4@liferay.com'), (1, 'firstName', 'Test 4'), (1, 'jobTitle', 'Product Owner'), (1, 'lastName', 'Test 4')], 'Test 4', '4', 'Product Owner', 'Test 4');