/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.segments.web.internal.constants;

/**
 * @author Eduardo García
 */
public class SegmentsWebKeys {

	public static final String EDIT_SEGMENTS_ENTRY_DISPLAY_CONTEXT =
		"EDIT_SEGMENTS_ENTRY_DISPLAY_CONTEXT";

	public static final String EXCLUDED_ROLE_NAMES = "EXCLUDED_ROLE_NAMES";

	public static final String ITEM_SELECTOR = "ITEM_SELECTOR";

	public static final String PREVIEW_SEGMENTS_ENTRY_CRITERIA =
		"PREVIEW_SEGMENTS_ENTRY_CRITERIA";

	public static final String PREVIEW_SEGMENTS_ENTRY_USERS_DISPLAY_CONTEXT =
		"PREVIEW_SEGMENTS_ENTRY_USERS_DISPLAY_CONTEXT";

	public static final String SEGMENTS_DISPLAY_CONTEXT =
		"SEGMENTS_DISPLAY_CONTEXT";

	public static final String
		SEGMENTS_SELECT_ORGANIZATION_MANAGEMENT_TOOLBAL_DISPLAY_CONTEXT =
			"SEGMENTS_SELECT_ORGANIZATION_MANAGEMENT_TOOLBAL_DISPLAY_CONTEXT";

	public static final String
		SEGMENTS_SELECT_USER_MANAGEMENT_TOOLBAL_DISPLAY_CONTEXT =
			"SEGMENTS_SELECT_USER_MANAGEMENT_TOOLBAL_DISPLAY_CONTEXT";

	public static final String SELECT_ORGANIZATIONS_DISPLAY_CONTEXT =
		"SELECT_ORGANIZATIONS_DISPLAY_CONTEXT";

	public static final String SELECT_SEGMENTS_ENTRY_DISPLAY_CONTEXT =
		"SELECT_SEGMENTS_ENTRY_DISPLAY_CONTEXT";

	public static final String SELECT_USERS_DISPLAY_CONTEXT =
		"SELECT_USERS_DISPLAY_CONTEXT";

}