apply plugin: "io.spring.dependency-management"
apply plugin: "org.springframework.boot"

ext["log4j2.version"] = "2.17.0"

bootJar {
	enabled = false
}

configurations.all {
	exclude group: "com.vaadin.external.google", module: "android-json"
}

dependencies {
	api group: "nl.jqno.equalsverifier", name: "equalsverifier", version: "2.5.1"
	api group: "org.springframework.boot", name: "spring-boot-starter-test"
	api project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-common")
}

jar {
	enabled = true
}