INSERT INTO DocumentLibraryDaily (assetId, channelId, eventDate, previews, userId) VALUES ('e131fabc', 1, TIMESTAMP(DATETIME_TRUNC(timestamp '${today-4d}', HOUR)), 1, '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO DocumentLibraryDaily (assetId, channelId, eventDate, previews, userId) VALUES ('e131fabc', 1, TIMESTAMP(DATETIME_TRUNC(timestamp '${today-4d}', HOUR)), 1, 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO DocumentLibraryDaily (assetId, channelId, eventDate, previews, userId) VALUES ('e131fabc', 1, TIMESTAMP(DATETIME_TRUNC(timestamp '${today-4d}', HOUR)), 1, '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');

INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now}', 'documentPreviewed', '1', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-10h}', 'documentPreviewed', '2', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-10h}', 'documentPreviewed', '3', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-10h}', 'documentPreviewed', '4', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '7f2b2049-440b-47c9-b8c7-6c9eff878d82');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-10h}', 'documentPreviewed', '5', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-7h}', 'documentPreviewed', '6', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-7h}', 'documentPreviewed', '7', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 2, timestamp '${now-8h}', 'documentPreviewed', '8', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '7f2b2049-440b-47c9-b8c7-6c9eff878d82');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 2, timestamp '${now-8h}', 'documentPreviewed', '9', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 2, timestamp '${now-8h}', 'documentPreviewed', '10', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 2, timestamp '${now-8h}', 'documentPreviewed', '11', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 2, timestamp '${now-8h}', 'documentPreviewed', '12', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '7f2b2049-440b-47c9-b8c7-6c9eff878d82');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-25h}', 'documentPreviewed', '13', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-25h}', 'documentPreviewed', '14', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-25h}', 'documentPreviewed', '15', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-25h}', 'documentPreviewed', '16', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '7f2b2049-440b-47c9-b8c7-6c9eff878d82');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-26h}', 'documentPreviewed', '17', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-26h}', 'documentPreviewed', '18', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-26h}', 'documentPreviewed', '19', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'e131fabc', 'Asset Title 1', 'https://www.beryl.com/products/commercial/irrigation/FF-2100', 1, timestamp '${now-26h}', 'documentPreviewed', '20', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 1', '7f2b2049-440b-47c9-b8c7-6c9eff878d82');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'a73ihsy9', 'Asset Title 2', 'https://www.beryl.com/delivery', 1, timestamp '${now-5h}', 'documentPreviewed', '21', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 2', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'a73ihsy9', 'Asset Title 2', 'https://www.beryl.com/delivery', 1, timestamp '${now-5h}', 'documentPreviewed', '22', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 2', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'a73ihsy9', 'Asset Title 2', 'https://www.beryl.com/delivery', 1, timestamp '${now-5h}', 'documentPreviewed', '23', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 2', '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'a73ihsy9', 'Asset Title 2', 'https://www.beryl.com/delivery', 1, timestamp '${now-5h}', 'documentPreviewed', '24', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 2', '7f2b2049-440b-47c9-b8c7-6c9eff878d82');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'a73ihsy9', 'Asset Title 2', 'https://www.beryl.com/delivery', 1, timestamp '${now-6h}', 'documentPreviewed', '25', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 2', '12ec1ae5-d9da-474b-8d64-42096e8109f2');
INSERT INTO Event (applicationId, assetId, assetTitle, canonicalUrl, channelId, eventDate, eventId, id, properties, title, userId) VALUES ('Document', 'a73ihsy9', 'Asset Title 2', 'https://www.beryl.com/delivery', 1, timestamp '${now-6h}', 'documentPreviewed', '26', ARRAY<STRUCT<name STRING, value STRING>> [], 'Title 2', 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977');

INSERT INTO Identity_Raw (id, individualId) VALUES ('12ec1ae5-d9da-474b-8d64-42096e8109f2', '2000');
INSERT INTO Identity_Raw (id, individualId) VALUES ('de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977', '2001');
INSERT INTO Identity_Raw (id, individualId) VALUES ('9b739f5a-76eb-4199-ba58-53d5dcaa3ec5', '2002');
INSERT INTO Identity_Raw (id, individualId) VALUES ('7f2b2049-440b-47c9-b8c7-6c9eff878d82', '2003');

INSERT INTO Individual (id, suppressed) VALUES ('2000', null);
INSERT INTO Individual (id, suppressed) VALUES ('2001', false);
INSERT INTO Individual (id, suppressed) VALUES ('2002', true);
INSERT INTO Individual (id, suppressed) VALUES ('2003', true);

INSERT INTO Membership (channelId, identityId, individualId, segmentId) VALUES (1, '12ec1ae5-d9da-474b-8d64-42096e8109f2', '2000', 192837465);
INSERT INTO Membership (channelId, identityId, individualId, segmentId) VALUES (1, 'de2ccc5b-ccf4-44f0-87a5-c7e6ad22e977', '2001', 192837465);
INSERT INTO Membership (channelId, identityId, individualId, segmentId) VALUES (1, '9b739f5a-76eb-4199-ba58-53d5dcaa3ec5', null, 192837465);
INSERT INTO Membership (channelId, identityId, individualId, segmentId) VALUES (1, '7f2b2049-440b-47c9-b8c7-6c9eff878d82', null, 192837465);