dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation project(":apps:asset:asset-test-util")
	testIntegrationImplementation project(":apps:bookmarks:bookmarks-api")
	testIntegrationImplementation project(":apps:bookmarks:bookmarks-test-util")
	testIntegrationImplementation project(":apps:export-import:export-import-api")
	testIntegrationImplementation project(":apps:export-import:export-import-test-util")
	testIntegrationImplementation project(":apps:journal:journal-api")
	testIntegrationImplementation project(":apps:journal:journal-test-util")
}