#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/provisioning-marketplace-rest
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Provisioning.Marketplace.REST)
osgi.jaxrs.resource=true