apply plugin: "io.gatling.gradle"

ext {
	set("junit-jupiter.version", "5.8.2")
	set("log4j2.version", "2.17.0")
}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

configurations.all {
	exclude group: "org.apache.geronimo.bundles", module: "json"
	exclude group: "org.nd4j", module: "nd4j-native-platform"
	exclude group: "org.slf4j", module: "slf4j-log4j12"
}

dependencies {
	gatlingImplementation group: "commons-codec", name: "commons-codec", version: "1.17.1"
	gatlingImplementation group: "org.json", name: "json", version: "20240303"
}