dependencies {
	compileOnly project(":core:petra:petra-function")
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	testIntegrationImplementation project(":apps:dispatch:dispatch-api")
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":core:registry-api")
}