test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
    ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Account") OR \
        (testray.main.component.name ~ "Account")\
    )

modules.includes.required.test.batch.class.names.excludes[modules-integration-*-jdk8][relevant]=\
    **/account-rest-test/**/AccountResourceTest.java

modules.includes.required[relevant]=apps/account
testray.main.component.name=Account