apiVersion: 1
datasources:
    -   access: proxy
      editable: true
      isDefault: true
      jsonData:
          graphiteVersion: "1.1"
          tlsAuth: false
          tlsAuthWithCACert: false
      name: osbasahprometheus
      orgId: 1
      type: prometheus
      url: http://osbasahprometheus:9090
      version: 1