/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.koroneiki.phytohormone.service.base;

import com.liferay.osb.koroneiki.phytohormone.model.EntitlementDefinition;
import com.liferay.osb.koroneiki.phytohormone.service.EntitlementDefinitionService;
import com.liferay.osb.koroneiki.phytohormone.service.EntitlementDefinitionServiceUtil;
import com.liferay.osb.koroneiki.phytohormone.service.persistence.EntitlementDefinitionPersistence;
import com.liferay.osb.koroneiki.phytohormone.service.persistence.EntitlementPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the entitlement definition remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.koroneiki.phytohormone.service.impl.EntitlementDefinitionServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.koroneiki.phytohormone.service.impl.EntitlementDefinitionServiceImpl
 * @generated
 */
public abstract class EntitlementDefinitionServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, EntitlementDefinitionService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EntitlementDefinitionService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EntitlementDefinitionServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		EntitlementDefinitionServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EntitlementDefinitionService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		entitlementDefinitionService = (EntitlementDefinitionService)aopProxy;

		EntitlementDefinitionServiceUtil.setService(
			entitlementDefinitionService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EntitlementDefinitionService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EntitlementDefinition.class;
	}

	protected String getModelClassName() {
		return EntitlementDefinition.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				entitlementDefinitionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected EntitlementPersistence entitlementPersistence;

	@Reference
	protected com.liferay.osb.koroneiki.phytohormone.service.
		EntitlementDefinitionLocalService entitlementDefinitionLocalService;

	protected EntitlementDefinitionService entitlementDefinitionService;

	@Reference
	protected EntitlementDefinitionPersistence entitlementDefinitionPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		EntitlementDefinitionServiceBaseImpl.class);

}