compileJSP {
	enabled = false
}

dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.50.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "2.4.0"
	compileOnly group: "javax.portlet", name: "portlet-api", version: "2.0"
	compileOnly group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-account-entry:osb-customer-account-entry-details-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-admin:osb-customer-admin-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-admin:osb-customer-admin-service")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-github:osb-customer-github-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-github:osb-customer-github-service")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-koroneiki:osb-customer-koroneiki-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-koroneiki:osb-customer-koroneiki-web-service-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-ticket:osb-customer-ticket-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-ticket:osb-customer-ticket-service")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-zendesk-util")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-zendesk:osb-customer-zendesk-api")
	compileOnly project(":dxp:apps:osb:osb-customer:osb-customer-zendesk:osb-customer-zendesk-web-service-api")
}

generateJSPJava {
	enabled = false
}

processResources {
	dependsOn packageRunWebpack
}