test.batch.run.property.query[functional-bundle-tomcat-mysql56-jdk8][test-portal-hotfix-release]=\
    ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]}

test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Knowledge Base") OR \
        (testray.main.component.name ~ "Knowledge Base")\
    )

testray.main.component.name=Knowledge Base