/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.distributed.messaging.model.impl;

import com.liferay.osb.distributed.messaging.model.QueuedMessage;
import com.liferay.osb.distributed.messaging.service.QueuedMessageLocalServiceUtil;

/**
 * The extended model base implementation for the QueuedMessage service. Represents a row in the &quot;DM_QueuedMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QueuedMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QueuedMessageImpl
 * @see QueuedMessage
 * @generated
 */
public abstract class QueuedMessageBaseImpl
	extends QueuedMessageModelImpl implements QueuedMessage {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a queued message model instance should use the <code>QueuedMessage</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			QueuedMessageLocalServiceUtil.addQueuedMessage(this);
		}
		else {
			QueuedMessageLocalServiceUtil.updateQueuedMessage(this);
		}
	}

}