dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "org.osgi", name: "org.osgi.service.cm", version: "1.5.0"
	testIntegrationImplementation project(":apps:portal-configuration:portal-configuration-test-util")
	testIntegrationImplementation project(":apps:portal-store:portal-store-azure")
	testIntegrationImplementation project(":apps:portal-store:portal-store-test-util")
}