/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.loop.token.auth.service.base;

import com.liferay.osb.loop.token.auth.model.TokenAuthEntry;
import com.liferay.osb.loop.token.auth.service.TokenAuthEntryService;
import com.liferay.osb.loop.token.auth.service.TokenAuthEntryServiceUtil;
import com.liferay.osb.loop.token.auth.service.persistence.TokenAuthEntryPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the token auth entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.loop.token.auth.service.impl.TokenAuthEntryServiceImpl}.
 * </p>
 *
 * @author Bruno Farache
 * @see com.liferay.osb.loop.token.auth.service.impl.TokenAuthEntryServiceImpl
 * @generated
 */
public abstract class TokenAuthEntryServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, TokenAuthEntryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TokenAuthEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>TokenAuthEntryServiceUtil</code>.
	 */

	/**
	 * Returns the token auth entry local service.
	 *
	 * @return the token auth entry local service
	 */
	public com.liferay.osb.loop.token.auth.service.TokenAuthEntryLocalService
		getTokenAuthEntryLocalService() {

		return tokenAuthEntryLocalService;
	}

	/**
	 * Sets the token auth entry local service.
	 *
	 * @param tokenAuthEntryLocalService the token auth entry local service
	 */
	public void setTokenAuthEntryLocalService(
		com.liferay.osb.loop.token.auth.service.TokenAuthEntryLocalService
			tokenAuthEntryLocalService) {

		this.tokenAuthEntryLocalService = tokenAuthEntryLocalService;
	}

	/**
	 * Returns the token auth entry remote service.
	 *
	 * @return the token auth entry remote service
	 */
	public TokenAuthEntryService getTokenAuthEntryService() {
		return tokenAuthEntryService;
	}

	/**
	 * Sets the token auth entry remote service.
	 *
	 * @param tokenAuthEntryService the token auth entry remote service
	 */
	public void setTokenAuthEntryService(
		TokenAuthEntryService tokenAuthEntryService) {

		this.tokenAuthEntryService = tokenAuthEntryService;
	}

	/**
	 * Returns the token auth entry persistence.
	 *
	 * @return the token auth entry persistence
	 */
	public TokenAuthEntryPersistence getTokenAuthEntryPersistence() {
		return tokenAuthEntryPersistence;
	}

	/**
	 * Sets the token auth entry persistence.
	 *
	 * @param tokenAuthEntryPersistence the token auth entry persistence
	 */
	public void setTokenAuthEntryPersistence(
		TokenAuthEntryPersistence tokenAuthEntryPersistence) {

		this.tokenAuthEntryPersistence = tokenAuthEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		TokenAuthEntryServiceUtil.setService(tokenAuthEntryService);
	}

	public void destroy() {
		TokenAuthEntryServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TokenAuthEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return TokenAuthEntry.class;
	}

	protected String getModelClassName() {
		return TokenAuthEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = tokenAuthEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.osb.loop.token.auth.service.TokenAuthEntryLocalService.class
	)
	protected com.liferay.osb.loop.token.auth.service.TokenAuthEntryLocalService
		tokenAuthEntryLocalService;

	@BeanReference(type = TokenAuthEntryService.class)
	protected TokenAuthEntryService tokenAuthEntryService;

	@BeanReference(type = TokenAuthEntryPersistence.class)
	protected TokenAuthEntryPersistence tokenAuthEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		TokenAuthEntryServiceBaseImpl.class);

}