dependencies {
	testIntegrationImplementation group: "com.github.ignaciotcrespo", name: "frutilla", version: "0.7.1"
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation project(":apps:commerce:commerce-currency-api")
	testIntegrationImplementation project(":apps:commerce:commerce-currency-test-util")
	testIntegrationImplementation project(":apps:commerce:commerce-price-list-api")
	testIntegrationImplementation project(":apps:commerce:commerce-product-api")
	testIntegrationImplementation project(":apps:commerce:commerce-product-test-util")
	testIntegrationImplementation project(":apps:commerce:commerce-product-type-simple")
	testIntegrationImplementation project(":apps:portal-search:portal-search-api")
	testIntegrationImplementation project(":apps:portal-search:portal-search-test-util")
}

if (!System.getenv("JENKINS_HOME")) {
	apply plugin: "com.liferay.poshi.runner.resources.defaults"

	poshiRunnerResources {
		baseName "commerce"

		dirs = ["src/testFunctional"]
	}
}