/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.customer.admin.service.base;

import com.liferay.osb.customer.admin.model.LicenseEntry;
import com.liferay.osb.customer.admin.service.LicenseEntryService;
import com.liferay.osb.customer.admin.service.LicenseEntryServiceUtil;
import com.liferay.osb.customer.admin.service.persistence.AccountAttachmentPersistence;
import com.liferay.osb.customer.admin.service.persistence.AccountEntryFinder;
import com.liferay.osb.customer.admin.service.persistence.AccountEntryLanguagePersistence;
import com.liferay.osb.customer.admin.service.persistence.AccountEntryPersistence;
import com.liferay.osb.customer.admin.service.persistence.AccountEnvironmentAttachmentPersistence;
import com.liferay.osb.customer.admin.service.persistence.AccountEnvironmentPersistence;
import com.liferay.osb.customer.admin.service.persistence.AuditEntryPersistence;
import com.liferay.osb.customer.admin.service.persistence.ExternalIdMapperPersistence;
import com.liferay.osb.customer.admin.service.persistence.LicenseEntryPersistence;
import com.liferay.osb.customer.admin.service.persistence.ProductEntryFinder;
import com.liferay.osb.customer.admin.service.persistence.ProductEntryPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the license entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.customer.admin.service.impl.LicenseEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.customer.admin.service.impl.LicenseEntryServiceImpl
 * @generated
 */
public abstract class LicenseEntryServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, LicenseEntryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LicenseEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>LicenseEntryServiceUtil</code>.
	 */

	/**
	 * Returns the account attachment local service.
	 *
	 * @return the account attachment local service
	 */
	public com.liferay.osb.customer.admin.service.AccountAttachmentLocalService
		getAccountAttachmentLocalService() {

		return accountAttachmentLocalService;
	}

	/**
	 * Sets the account attachment local service.
	 *
	 * @param accountAttachmentLocalService the account attachment local service
	 */
	public void setAccountAttachmentLocalService(
		com.liferay.osb.customer.admin.service.AccountAttachmentLocalService
			accountAttachmentLocalService) {

		this.accountAttachmentLocalService = accountAttachmentLocalService;
	}

	/**
	 * Returns the account attachment remote service.
	 *
	 * @return the account attachment remote service
	 */
	public com.liferay.osb.customer.admin.service.AccountAttachmentService
		getAccountAttachmentService() {

		return accountAttachmentService;
	}

	/**
	 * Sets the account attachment remote service.
	 *
	 * @param accountAttachmentService the account attachment remote service
	 */
	public void setAccountAttachmentService(
		com.liferay.osb.customer.admin.service.AccountAttachmentService
			accountAttachmentService) {

		this.accountAttachmentService = accountAttachmentService;
	}

	/**
	 * Returns the account attachment persistence.
	 *
	 * @return the account attachment persistence
	 */
	public AccountAttachmentPersistence getAccountAttachmentPersistence() {
		return accountAttachmentPersistence;
	}

	/**
	 * Sets the account attachment persistence.
	 *
	 * @param accountAttachmentPersistence the account attachment persistence
	 */
	public void setAccountAttachmentPersistence(
		AccountAttachmentPersistence accountAttachmentPersistence) {

		this.accountAttachmentPersistence = accountAttachmentPersistence;
	}

	/**
	 * Returns the account customer remote service.
	 *
	 * @return the account customer remote service
	 */
	public com.liferay.osb.customer.admin.service.AccountCustomerService
		getAccountCustomerService() {

		return accountCustomerService;
	}

	/**
	 * Sets the account customer remote service.
	 *
	 * @param accountCustomerService the account customer remote service
	 */
	public void setAccountCustomerService(
		com.liferay.osb.customer.admin.service.AccountCustomerService
			accountCustomerService) {

		this.accountCustomerService = accountCustomerService;
	}

	/**
	 * Returns the account entry local service.
	 *
	 * @return the account entry local service
	 */
	public com.liferay.osb.customer.admin.service.AccountEntryLocalService
		getAccountEntryLocalService() {

		return accountEntryLocalService;
	}

	/**
	 * Sets the account entry local service.
	 *
	 * @param accountEntryLocalService the account entry local service
	 */
	public void setAccountEntryLocalService(
		com.liferay.osb.customer.admin.service.AccountEntryLocalService
			accountEntryLocalService) {

		this.accountEntryLocalService = accountEntryLocalService;
	}

	/**
	 * Returns the account entry remote service.
	 *
	 * @return the account entry remote service
	 */
	public com.liferay.osb.customer.admin.service.AccountEntryService
		getAccountEntryService() {

		return accountEntryService;
	}

	/**
	 * Sets the account entry remote service.
	 *
	 * @param accountEntryService the account entry remote service
	 */
	public void setAccountEntryService(
		com.liferay.osb.customer.admin.service.AccountEntryService
			accountEntryService) {

		this.accountEntryService = accountEntryService;
	}

	/**
	 * Returns the account entry persistence.
	 *
	 * @return the account entry persistence
	 */
	public AccountEntryPersistence getAccountEntryPersistence() {
		return accountEntryPersistence;
	}

	/**
	 * Sets the account entry persistence.
	 *
	 * @param accountEntryPersistence the account entry persistence
	 */
	public void setAccountEntryPersistence(
		AccountEntryPersistence accountEntryPersistence) {

		this.accountEntryPersistence = accountEntryPersistence;
	}

	/**
	 * Returns the account entry finder.
	 *
	 * @return the account entry finder
	 */
	public AccountEntryFinder getAccountEntryFinder() {
		return accountEntryFinder;
	}

	/**
	 * Sets the account entry finder.
	 *
	 * @param accountEntryFinder the account entry finder
	 */
	public void setAccountEntryFinder(AccountEntryFinder accountEntryFinder) {
		this.accountEntryFinder = accountEntryFinder;
	}

	/**
	 * Returns the account entry language local service.
	 *
	 * @return the account entry language local service
	 */
	public
		com.liferay.osb.customer.admin.service.AccountEntryLanguageLocalService
			getAccountEntryLanguageLocalService() {

		return accountEntryLanguageLocalService;
	}

	/**
	 * Sets the account entry language local service.
	 *
	 * @param accountEntryLanguageLocalService the account entry language local service
	 */
	public void setAccountEntryLanguageLocalService(
		com.liferay.osb.customer.admin.service.AccountEntryLanguageLocalService
			accountEntryLanguageLocalService) {

		this.accountEntryLanguageLocalService =
			accountEntryLanguageLocalService;
	}

	/**
	 * Returns the account entry language remote service.
	 *
	 * @return the account entry language remote service
	 */
	public com.liferay.osb.customer.admin.service.AccountEntryLanguageService
		getAccountEntryLanguageService() {

		return accountEntryLanguageService;
	}

	/**
	 * Sets the account entry language remote service.
	 *
	 * @param accountEntryLanguageService the account entry language remote service
	 */
	public void setAccountEntryLanguageService(
		com.liferay.osb.customer.admin.service.AccountEntryLanguageService
			accountEntryLanguageService) {

		this.accountEntryLanguageService = accountEntryLanguageService;
	}

	/**
	 * Returns the account entry language persistence.
	 *
	 * @return the account entry language persistence
	 */
	public AccountEntryLanguagePersistence
		getAccountEntryLanguagePersistence() {

		return accountEntryLanguagePersistence;
	}

	/**
	 * Sets the account entry language persistence.
	 *
	 * @param accountEntryLanguagePersistence the account entry language persistence
	 */
	public void setAccountEntryLanguagePersistence(
		AccountEntryLanguagePersistence accountEntryLanguagePersistence) {

		this.accountEntryLanguagePersistence = accountEntryLanguagePersistence;
	}

	/**
	 * Returns the account environment local service.
	 *
	 * @return the account environment local service
	 */
	public com.liferay.osb.customer.admin.service.AccountEnvironmentLocalService
		getAccountEnvironmentLocalService() {

		return accountEnvironmentLocalService;
	}

	/**
	 * Sets the account environment local service.
	 *
	 * @param accountEnvironmentLocalService the account environment local service
	 */
	public void setAccountEnvironmentLocalService(
		com.liferay.osb.customer.admin.service.AccountEnvironmentLocalService
			accountEnvironmentLocalService) {

		this.accountEnvironmentLocalService = accountEnvironmentLocalService;
	}

	/**
	 * Returns the account environment remote service.
	 *
	 * @return the account environment remote service
	 */
	public com.liferay.osb.customer.admin.service.AccountEnvironmentService
		getAccountEnvironmentService() {

		return accountEnvironmentService;
	}

	/**
	 * Sets the account environment remote service.
	 *
	 * @param accountEnvironmentService the account environment remote service
	 */
	public void setAccountEnvironmentService(
		com.liferay.osb.customer.admin.service.AccountEnvironmentService
			accountEnvironmentService) {

		this.accountEnvironmentService = accountEnvironmentService;
	}

	/**
	 * Returns the account environment persistence.
	 *
	 * @return the account environment persistence
	 */
	public AccountEnvironmentPersistence getAccountEnvironmentPersistence() {
		return accountEnvironmentPersistence;
	}

	/**
	 * Sets the account environment persistence.
	 *
	 * @param accountEnvironmentPersistence the account environment persistence
	 */
	public void setAccountEnvironmentPersistence(
		AccountEnvironmentPersistence accountEnvironmentPersistence) {

		this.accountEnvironmentPersistence = accountEnvironmentPersistence;
	}

	/**
	 * Returns the account environment attachment local service.
	 *
	 * @return the account environment attachment local service
	 */
	public com.liferay.osb.customer.admin.service.
		AccountEnvironmentAttachmentLocalService
			getAccountEnvironmentAttachmentLocalService() {

		return accountEnvironmentAttachmentLocalService;
	}

	/**
	 * Sets the account environment attachment local service.
	 *
	 * @param accountEnvironmentAttachmentLocalService the account environment attachment local service
	 */
	public void setAccountEnvironmentAttachmentLocalService(
		com.liferay.osb.customer.admin.service.
			AccountEnvironmentAttachmentLocalService
				accountEnvironmentAttachmentLocalService) {

		this.accountEnvironmentAttachmentLocalService =
			accountEnvironmentAttachmentLocalService;
	}

	/**
	 * Returns the account environment attachment remote service.
	 *
	 * @return the account environment attachment remote service
	 */
	public
		com.liferay.osb.customer.admin.service.
			AccountEnvironmentAttachmentService
				getAccountEnvironmentAttachmentService() {

		return accountEnvironmentAttachmentService;
	}

	/**
	 * Sets the account environment attachment remote service.
	 *
	 * @param accountEnvironmentAttachmentService the account environment attachment remote service
	 */
	public void setAccountEnvironmentAttachmentService(
		com.liferay.osb.customer.admin.service.
			AccountEnvironmentAttachmentService
				accountEnvironmentAttachmentService) {

		this.accountEnvironmentAttachmentService =
			accountEnvironmentAttachmentService;
	}

	/**
	 * Returns the account environment attachment persistence.
	 *
	 * @return the account environment attachment persistence
	 */
	public AccountEnvironmentAttachmentPersistence
		getAccountEnvironmentAttachmentPersistence() {

		return accountEnvironmentAttachmentPersistence;
	}

	/**
	 * Sets the account environment attachment persistence.
	 *
	 * @param accountEnvironmentAttachmentPersistence the account environment attachment persistence
	 */
	public void setAccountEnvironmentAttachmentPersistence(
		AccountEnvironmentAttachmentPersistence
			accountEnvironmentAttachmentPersistence) {

		this.accountEnvironmentAttachmentPersistence =
			accountEnvironmentAttachmentPersistence;
	}

	/**
	 * Returns the audit entry local service.
	 *
	 * @return the audit entry local service
	 */
	public com.liferay.osb.customer.admin.service.AuditEntryLocalService
		getAuditEntryLocalService() {

		return auditEntryLocalService;
	}

	/**
	 * Sets the audit entry local service.
	 *
	 * @param auditEntryLocalService the audit entry local service
	 */
	public void setAuditEntryLocalService(
		com.liferay.osb.customer.admin.service.AuditEntryLocalService
			auditEntryLocalService) {

		this.auditEntryLocalService = auditEntryLocalService;
	}

	/**
	 * Returns the audit entry remote service.
	 *
	 * @return the audit entry remote service
	 */
	public com.liferay.osb.customer.admin.service.AuditEntryService
		getAuditEntryService() {

		return auditEntryService;
	}

	/**
	 * Sets the audit entry remote service.
	 *
	 * @param auditEntryService the audit entry remote service
	 */
	public void setAuditEntryService(
		com.liferay.osb.customer.admin.service.AuditEntryService
			auditEntryService) {

		this.auditEntryService = auditEntryService;
	}

	/**
	 * Returns the audit entry persistence.
	 *
	 * @return the audit entry persistence
	 */
	public AuditEntryPersistence getAuditEntryPersistence() {
		return auditEntryPersistence;
	}

	/**
	 * Sets the audit entry persistence.
	 *
	 * @param auditEntryPersistence the audit entry persistence
	 */
	public void setAuditEntryPersistence(
		AuditEntryPersistence auditEntryPersistence) {

		this.auditEntryPersistence = auditEntryPersistence;
	}

	/**
	 * Returns the external ID mapper local service.
	 *
	 * @return the external ID mapper local service
	 */
	public com.liferay.osb.customer.admin.service.ExternalIdMapperLocalService
		getExternalIdMapperLocalService() {

		return externalIdMapperLocalService;
	}

	/**
	 * Sets the external ID mapper local service.
	 *
	 * @param externalIdMapperLocalService the external ID mapper local service
	 */
	public void setExternalIdMapperLocalService(
		com.liferay.osb.customer.admin.service.ExternalIdMapperLocalService
			externalIdMapperLocalService) {

		this.externalIdMapperLocalService = externalIdMapperLocalService;
	}

	/**
	 * Returns the external ID mapper persistence.
	 *
	 * @return the external ID mapper persistence
	 */
	public ExternalIdMapperPersistence getExternalIdMapperPersistence() {
		return externalIdMapperPersistence;
	}

	/**
	 * Sets the external ID mapper persistence.
	 *
	 * @param externalIdMapperPersistence the external ID mapper persistence
	 */
	public void setExternalIdMapperPersistence(
		ExternalIdMapperPersistence externalIdMapperPersistence) {

		this.externalIdMapperPersistence = externalIdMapperPersistence;
	}

	/**
	 * Returns the license entry local service.
	 *
	 * @return the license entry local service
	 */
	public com.liferay.osb.customer.admin.service.LicenseEntryLocalService
		getLicenseEntryLocalService() {

		return licenseEntryLocalService;
	}

	/**
	 * Sets the license entry local service.
	 *
	 * @param licenseEntryLocalService the license entry local service
	 */
	public void setLicenseEntryLocalService(
		com.liferay.osb.customer.admin.service.LicenseEntryLocalService
			licenseEntryLocalService) {

		this.licenseEntryLocalService = licenseEntryLocalService;
	}

	/**
	 * Returns the license entry remote service.
	 *
	 * @return the license entry remote service
	 */
	public LicenseEntryService getLicenseEntryService() {
		return licenseEntryService;
	}

	/**
	 * Sets the license entry remote service.
	 *
	 * @param licenseEntryService the license entry remote service
	 */
	public void setLicenseEntryService(
		LicenseEntryService licenseEntryService) {

		this.licenseEntryService = licenseEntryService;
	}

	/**
	 * Returns the license entry persistence.
	 *
	 * @return the license entry persistence
	 */
	public LicenseEntryPersistence getLicenseEntryPersistence() {
		return licenseEntryPersistence;
	}

	/**
	 * Sets the license entry persistence.
	 *
	 * @param licenseEntryPersistence the license entry persistence
	 */
	public void setLicenseEntryPersistence(
		LicenseEntryPersistence licenseEntryPersistence) {

		this.licenseEntryPersistence = licenseEntryPersistence;
	}

	/**
	 * Returns the product entry local service.
	 *
	 * @return the product entry local service
	 */
	public com.liferay.osb.customer.admin.service.ProductEntryLocalService
		getProductEntryLocalService() {

		return productEntryLocalService;
	}

	/**
	 * Sets the product entry local service.
	 *
	 * @param productEntryLocalService the product entry local service
	 */
	public void setProductEntryLocalService(
		com.liferay.osb.customer.admin.service.ProductEntryLocalService
			productEntryLocalService) {

		this.productEntryLocalService = productEntryLocalService;
	}

	/**
	 * Returns the product entry remote service.
	 *
	 * @return the product entry remote service
	 */
	public com.liferay.osb.customer.admin.service.ProductEntryService
		getProductEntryService() {

		return productEntryService;
	}

	/**
	 * Sets the product entry remote service.
	 *
	 * @param productEntryService the product entry remote service
	 */
	public void setProductEntryService(
		com.liferay.osb.customer.admin.service.ProductEntryService
			productEntryService) {

		this.productEntryService = productEntryService;
	}

	/**
	 * Returns the product entry persistence.
	 *
	 * @return the product entry persistence
	 */
	public ProductEntryPersistence getProductEntryPersistence() {
		return productEntryPersistence;
	}

	/**
	 * Sets the product entry persistence.
	 *
	 * @param productEntryPersistence the product entry persistence
	 */
	public void setProductEntryPersistence(
		ProductEntryPersistence productEntryPersistence) {

		this.productEntryPersistence = productEntryPersistence;
	}

	/**
	 * Returns the product entry finder.
	 *
	 * @return the product entry finder
	 */
	public ProductEntryFinder getProductEntryFinder() {
		return productEntryFinder;
	}

	/**
	 * Sets the product entry finder.
	 *
	 * @param productEntryFinder the product entry finder
	 */
	public void setProductEntryFinder(ProductEntryFinder productEntryFinder) {
		this.productEntryFinder = productEntryFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		LicenseEntryServiceUtil.setService(licenseEntryService);
	}

	public void destroy() {
		LicenseEntryServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LicenseEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LicenseEntry.class;
	}

	protected String getModelClassName() {
		return LicenseEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = licenseEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountAttachmentLocalService.class
	)
	protected
		com.liferay.osb.customer.admin.service.AccountAttachmentLocalService
			accountAttachmentLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountAttachmentService.class
	)
	protected com.liferay.osb.customer.admin.service.AccountAttachmentService
		accountAttachmentService;

	@BeanReference(type = AccountAttachmentPersistence.class)
	protected AccountAttachmentPersistence accountAttachmentPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountCustomerService.class
	)
	protected com.liferay.osb.customer.admin.service.AccountCustomerService
		accountCustomerService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEntryLocalService.class
	)
	protected com.liferay.osb.customer.admin.service.AccountEntryLocalService
		accountEntryLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEntryService.class
	)
	protected com.liferay.osb.customer.admin.service.AccountEntryService
		accountEntryService;

	@BeanReference(type = AccountEntryPersistence.class)
	protected AccountEntryPersistence accountEntryPersistence;

	@BeanReference(type = AccountEntryFinder.class)
	protected AccountEntryFinder accountEntryFinder;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEntryLanguageLocalService.class
	)
	protected
		com.liferay.osb.customer.admin.service.AccountEntryLanguageLocalService
			accountEntryLanguageLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEntryLanguageService.class
	)
	protected com.liferay.osb.customer.admin.service.AccountEntryLanguageService
		accountEntryLanguageService;

	@BeanReference(type = AccountEntryLanguagePersistence.class)
	protected AccountEntryLanguagePersistence accountEntryLanguagePersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEnvironmentLocalService.class
	)
	protected
		com.liferay.osb.customer.admin.service.AccountEnvironmentLocalService
			accountEnvironmentLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEnvironmentService.class
	)
	protected com.liferay.osb.customer.admin.service.AccountEnvironmentService
		accountEnvironmentService;

	@BeanReference(type = AccountEnvironmentPersistence.class)
	protected AccountEnvironmentPersistence accountEnvironmentPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEnvironmentAttachmentLocalService.class
	)
	protected com.liferay.osb.customer.admin.service.
		AccountEnvironmentAttachmentLocalService
			accountEnvironmentAttachmentLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AccountEnvironmentAttachmentService.class
	)
	protected
		com.liferay.osb.customer.admin.service.
			AccountEnvironmentAttachmentService
				accountEnvironmentAttachmentService;

	@BeanReference(type = AccountEnvironmentAttachmentPersistence.class)
	protected AccountEnvironmentAttachmentPersistence
		accountEnvironmentAttachmentPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AuditEntryLocalService.class
	)
	protected com.liferay.osb.customer.admin.service.AuditEntryLocalService
		auditEntryLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.AuditEntryService.class
	)
	protected com.liferay.osb.customer.admin.service.AuditEntryService
		auditEntryService;

	@BeanReference(type = AuditEntryPersistence.class)
	protected AuditEntryPersistence auditEntryPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.ExternalIdMapperLocalService.class
	)
	protected
		com.liferay.osb.customer.admin.service.ExternalIdMapperLocalService
			externalIdMapperLocalService;

	@BeanReference(type = ExternalIdMapperPersistence.class)
	protected ExternalIdMapperPersistence externalIdMapperPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.LicenseEntryLocalService.class
	)
	protected com.liferay.osb.customer.admin.service.LicenseEntryLocalService
		licenseEntryLocalService;

	@BeanReference(type = LicenseEntryService.class)
	protected LicenseEntryService licenseEntryService;

	@BeanReference(type = LicenseEntryPersistence.class)
	protected LicenseEntryPersistence licenseEntryPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.ProductEntryLocalService.class
	)
	protected com.liferay.osb.customer.admin.service.ProductEntryLocalService
		productEntryLocalService;

	@BeanReference(
		type = com.liferay.osb.customer.admin.service.ProductEntryService.class
	)
	protected com.liferay.osb.customer.admin.service.ProductEntryService
		productEntryService;

	@BeanReference(type = ProductEntryPersistence.class)
	protected ProductEntryPersistence productEntryPersistence;

	@BeanReference(type = ProductEntryFinder.class)
	protected ProductEntryFinder productEntryFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		LicenseEntryServiceBaseImpl.class);

}