modules.includes.required.functional[relevant]=apps/segments

modules.includes.required.test.batch.class.names.includes[relevant]=\
    apps/segments/**/*Test.java

testray.main.component.name=Analytics Cloud