/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.provisioning.subscription.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.provisioning.subscription.model.SubscriptionEntry;
import com.liferay.osb.provisioning.subscription.model.SubscriptionEntryModel;
import com.liferay.osb.provisioning.subscription.model.SubscriptionEntrySoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SubscriptionEntry service. Represents a row in the &quot;Provisioning_SubscriptionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubscriptionEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubscriptionEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubscriptionEntryImpl
 * @generated
 */
@JSON(strict = true)
public class SubscriptionEntryModelImpl
	extends BaseModelImpl<SubscriptionEntry> implements SubscriptionEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subscription entry model instance should use the <code>SubscriptionEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "Provisioning_SubscriptionEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"subscriptionEntryId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"contactUuid", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subscriptionEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactUuid", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Provisioning_SubscriptionEntry (mvccVersion LONG default 0 not null,subscriptionEntryId LONG not null primary key,createDate DATE null,classNameId LONG,classPK LONG,contactUuid VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Provisioning_SubscriptionEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subscriptionEntry.subscriptionEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Provisioning_SubscriptionEntry.subscriptionEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long CONTACTUUID_COLUMN_BITMASK = 4L;

	public static final long SUBSCRIPTIONENTRYID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SubscriptionEntry toModel(SubscriptionEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SubscriptionEntry model = new SubscriptionEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setSubscriptionEntryId(soapModel.getSubscriptionEntryId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setContactUuid(soapModel.getContactUuid());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SubscriptionEntry> toModels(
		SubscriptionEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SubscriptionEntry> models = new ArrayList<SubscriptionEntry>(
			soapModels.length);

		for (SubscriptionEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SubscriptionEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subscriptionEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubscriptionEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subscriptionEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SubscriptionEntry.class;
	}

	@Override
	public String getModelClassName() {
		return SubscriptionEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SubscriptionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SubscriptionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubscriptionEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SubscriptionEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SubscriptionEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SubscriptionEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SubscriptionEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SubscriptionEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SubscriptionEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SubscriptionEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<SubscriptionEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SubscriptionEntry, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", SubscriptionEntry::getMvccVersion);
		attributeGetterFunctions.put(
			"subscriptionEntryId", SubscriptionEntry::getSubscriptionEntryId);
		attributeGetterFunctions.put(
			"createDate", SubscriptionEntry::getCreateDate);
		attributeGetterFunctions.put(
			"classNameId", SubscriptionEntry::getClassNameId);
		attributeGetterFunctions.put("classPK", SubscriptionEntry::getClassPK);
		attributeGetterFunctions.put(
			"contactUuid", SubscriptionEntry::getContactUuid);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<SubscriptionEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<SubscriptionEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SubscriptionEntry, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<SubscriptionEntry, Long>)
				SubscriptionEntry::setMvccVersion);
		attributeSetterBiConsumers.put(
			"subscriptionEntryId",
			(BiConsumer<SubscriptionEntry, Long>)
				SubscriptionEntry::setSubscriptionEntryId);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SubscriptionEntry, Date>)
				SubscriptionEntry::setCreateDate);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<SubscriptionEntry, Long>)
				SubscriptionEntry::setClassNameId);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<SubscriptionEntry, Long>)SubscriptionEntry::setClassPK);
		attributeSetterBiConsumers.put(
			"contactUuid",
			(BiConsumer<SubscriptionEntry, String>)
				SubscriptionEntry::setContactUuid);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getSubscriptionEntryId() {
		return _subscriptionEntryId;
	}

	@Override
	public void setSubscriptionEntryId(long subscriptionEntryId) {
		_subscriptionEntryId = subscriptionEntryId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@JSON
	@Override
	public String getContactUuid() {
		if (_contactUuid == null) {
			return "";
		}
		else {
			return _contactUuid;
		}
	}

	@Override
	public void setContactUuid(String contactUuid) {
		_columnBitmask |= CONTACTUUID_COLUMN_BITMASK;

		if (_originalContactUuid == null) {
			_originalContactUuid = _contactUuid;
		}

		_contactUuid = contactUuid;
	}

	public String getOriginalContactUuid() {
		return GetterUtil.getString(_originalContactUuid);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SubscriptionEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SubscriptionEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SubscriptionEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubscriptionEntryImpl subscriptionEntryImpl =
			new SubscriptionEntryImpl();

		subscriptionEntryImpl.setMvccVersion(getMvccVersion());
		subscriptionEntryImpl.setSubscriptionEntryId(getSubscriptionEntryId());
		subscriptionEntryImpl.setCreateDate(getCreateDate());
		subscriptionEntryImpl.setClassNameId(getClassNameId());
		subscriptionEntryImpl.setClassPK(getClassPK());
		subscriptionEntryImpl.setContactUuid(getContactUuid());

		subscriptionEntryImpl.resetOriginalValues();

		return subscriptionEntryImpl;
	}

	@Override
	public int compareTo(SubscriptionEntry subscriptionEntry) {
		long primaryKey = subscriptionEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SubscriptionEntry)) {
			return false;
		}

		SubscriptionEntry subscriptionEntry = (SubscriptionEntry)object;

		long primaryKey = subscriptionEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalClassNameId = _classNameId;

		_setOriginalClassNameId = false;

		_originalClassPK = _classPK;

		_setOriginalClassPK = false;

		_originalContactUuid = _contactUuid;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SubscriptionEntry> toCacheModel() {
		SubscriptionEntryCacheModel subscriptionEntryCacheModel =
			new SubscriptionEntryCacheModel();

		subscriptionEntryCacheModel.mvccVersion = getMvccVersion();

		subscriptionEntryCacheModel.subscriptionEntryId =
			getSubscriptionEntryId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			subscriptionEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			subscriptionEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		subscriptionEntryCacheModel.classNameId = getClassNameId();

		subscriptionEntryCacheModel.classPK = getClassPK();

		subscriptionEntryCacheModel.contactUuid = getContactUuid();

		String contactUuid = subscriptionEntryCacheModel.contactUuid;

		if ((contactUuid != null) && (contactUuid.length() == 0)) {
			subscriptionEntryCacheModel.contactUuid = null;
		}

		return subscriptionEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SubscriptionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SubscriptionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubscriptionEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SubscriptionEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SubscriptionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SubscriptionEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SubscriptionEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SubscriptionEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SubscriptionEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SubscriptionEntry.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private long _subscriptionEntryId;
	private Date _createDate;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _contactUuid;
	private String _originalContactUuid;
	private long _columnBitmask;
	private SubscriptionEntry _escapedModel;

}