commerce:
    data:
        source: bigquery
    ml:
        locale: en_US
forecast:
    algorithm: 'sarima'
    cross:
        validation:
            steps: 4
    data:
        history:
            length: 8
        minimum:
            length: 30
    force:
        parallelism:
    horizon:
        steps: 1
    model:
        max:
            order: 10
        order:
            d:
            p:
                -   0
                -   1
                -   2
                -   3
                -   4
                -   5
            q:
                -   0
                -   1
                -   2
                -   3
                -   4
                -   5
        period:
        prediction:
            dynamic:
                flag:
        seasonal:
            d:
            p:
                -   0
                -   1
                -   2
            q:
                -   0
                -   1
                -   2
        selection:
            criterion: 'error'
        trend:
            -   "n"
            -   "c"
            -   "t"
            -   "ct"
    prophet:
        changepoint_range: 0.8
        checkpoint_prior_scale:
            -   0.001
            -   0.01
            -   0.1
            -   0.5
        daily_seasonality: 'auto'
        growth: 'linear'
        holidays_prior_scale:
            -   10.0
        interval_width: 0.8
        mcmc_samples: 0
        n_changepoints: 25
        seasonality_mode:
            -   'additive'
            -   'multiplicative'
        seasonality_prior_scale:
            -   0.01
            -   0.1
            -   1.0
            -   10.0
        weekly_seasonality: 'auto'
        yearly_seasonality: 'auto'
frequent:
    pattern:
        recommendation:
            itemset:
                items:
                    max:
                        count: 5
            min:
                confidence: 0.50
                support:
                    factor: 0.4
google:
    storage:
        bucket: gs://${PROJECT_ID}-dxp-entities
product:
    content:
        recommendation:
            coalesce:
                partition:
                    count:
            max:
                rank: 10
    interaction:
        recommendation:
            enable: true
            max:
                rank: 10
            score:
                function: "tanimoto_coefficient"
user:
    interaction:
        order:
            history:
                length: 5
        recommendation:
            als:
                checkpoint:
                    interval: 5
            catalog:
                coverage: 0.3
            train:
                split:
                    ratio: 0.85
            tuning:
                alpha:
                    -   40
                    -   60
                cross:
                    validator:
                        numFolds: 5
                        parallelism: 2
                max:
                    iteration:
                        -   10
                        -   20
                rank:
                    -   10
                    -   20
                    -   5
                regularization:
                    parameter:
                        -   0.1
                        -   1.0