content:
    interaction:
        recommendation:
            enable: true
            max:
                rank: 10
            score:
                function: "tanimoto_coefficient"
google:
    storage:
        bucket: gs://${PROJECT_ID}-dxp-entities
        path:
            temporaryGcsBucket: ${PROJECT_ID}-dataproc-${REGION}/temp_write_bucket_for_bq_writes
most:
    viewed:
        content:
            recommendation:
                window:
                    days: 30
user:
    content:
        recommendation:
            als:
                checkpoint:
                    interval: 5
            content:
                coverage: 0.3
            train:
                split:
                    ratio: 0.85
            tuning:
                alpha:
                    -   40
                    -   60
                cross:
                    validator:
                        num:
                            folds: 5
                        parallelism: 2
                max:
                    iteration:
                        -   10
                        -   20
                rank:
                    -   10
                    -   20
                    -   5
                regularization:
                    parameter:
                        -   0.1
                        -   1.0