dependencies {
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testImplementation project(":apps:static:portal-lpkg-deployer:portal-lpkg-deployer-test-util")
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "org.osgi", name: "org.osgi.service.cm", version: "1.5.0"
	testIntegrationImplementation group: "org.osgi", name: "osgi.core", version: "6.0.0"
	testIntegrationImplementation project(":apps:static:osgi:osgi-util")
	testIntegrationImplementation project(":apps:static:portal-bundle-blacklist:portal-bundle-blacklist")
}

test {
	systemProperty "blacklist.cfg.name", System.getProperty("blacklist.cfg.name")
	systemProperty "liferay.home", System.getProperty("liferay.home")
}