dependencies {
	compileOnly project(":core:petra:petra-function")
	testIntegrationImplementation group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.13.4"
	testIntegrationImplementation group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.13.4"
	testIntegrationImplementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.13.4.2"
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "commons-beanutils", name: "commons-beanutils", version: "1.9.4"
	testIntegrationImplementation group: "javax.ws.rs", name: "javax.ws.rs-api", version: "2.1"
	testIntegrationImplementation project(":apps:headless:headless-admin-content:headless-admin-content-api")
	testIntegrationImplementation project(":apps:headless:headless-admin-content:headless-admin-content-client")
	testIntegrationImplementation project(":apps:headless:headless-delivery:headless-delivery-api")
	testIntegrationImplementation project(":apps:portal-odata:portal-odata-api")
	testIntegrationImplementation project(":apps:portal-search:portal-search-test-util")
	testIntegrationImplementation project(":apps:portal-vulcan:portal-vulcan-api")
}