apply plugin: "com.liferay.spring.boot.defaults"
apply plugin: "io.spring.dependency-management"

ext {
	set("junit-jupiter.version", "5.8.2")
	set("log4j2.version", "2.17.0")
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"

bootJar {
	classifier = "application"
}

dependencies {
	api (group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.10") {
		force = true
	}
	api project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-common")

	testImplementation project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-test-util")
}

jar {
	enabled = true
}