/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.customer.zendesk.documentation.sync.service.base;

import com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskCategory;
import com.liferay.osb.customer.zendesk.documentation.sync.service.ZendeskCategoryLocalService;
import com.liferay.osb.customer.zendesk.documentation.sync.service.ZendeskCategoryLocalServiceUtil;
import com.liferay.osb.customer.zendesk.documentation.sync.service.persistence.ZendeskArticleAttachmentPersistence;
import com.liferay.osb.customer.zendesk.documentation.sync.service.persistence.ZendeskArticlePersistence;
import com.liferay.osb.customer.zendesk.documentation.sync.service.persistence.ZendeskCategoryPersistence;
import com.liferay.osb.customer.zendesk.documentation.sync.service.persistence.ZendeskSectionPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the zendesk category local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.customer.zendesk.documentation.sync.service.impl.ZendeskCategoryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.customer.zendesk.documentation.sync.service.impl.ZendeskCategoryLocalServiceImpl
 * @generated
 */
public abstract class ZendeskCategoryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, ZendeskCategoryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ZendeskCategoryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ZendeskCategoryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the zendesk category to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ZendeskCategoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param zendeskCategory the zendesk category
	 * @return the zendesk category that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ZendeskCategory addZendeskCategory(ZendeskCategory zendeskCategory) {
		zendeskCategory.setNew(true);

		return zendeskCategoryPersistence.update(zendeskCategory);
	}

	/**
	 * Creates a new zendesk category with the primary key. Does not add the zendesk category to the database.
	 *
	 * @param zendeskCategoryId the primary key for the new zendesk category
	 * @return the new zendesk category
	 */
	@Override
	@Transactional(enabled = false)
	public ZendeskCategory createZendeskCategory(long zendeskCategoryId) {
		return zendeskCategoryPersistence.create(zendeskCategoryId);
	}

	/**
	 * Deletes the zendesk category with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ZendeskCategoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param zendeskCategoryId the primary key of the zendesk category
	 * @return the zendesk category that was removed
	 * @throws PortalException if a zendesk category with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ZendeskCategory deleteZendeskCategory(long zendeskCategoryId)
		throws PortalException {

		return zendeskCategoryPersistence.remove(zendeskCategoryId);
	}

	/**
	 * Deletes the zendesk category from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ZendeskCategoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param zendeskCategory the zendesk category
	 * @return the zendesk category that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ZendeskCategory deleteZendeskCategory(
		ZendeskCategory zendeskCategory) {

		return zendeskCategoryPersistence.remove(zendeskCategory);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ZendeskCategory.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return zendeskCategoryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.customer.zendesk.documentation.sync.model.impl.ZendeskCategoryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return zendeskCategoryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.customer.zendesk.documentation.sync.model.impl.ZendeskCategoryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return zendeskCategoryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return zendeskCategoryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return zendeskCategoryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ZendeskCategory fetchZendeskCategory(long zendeskCategoryId) {
		return zendeskCategoryPersistence.fetchByPrimaryKey(zendeskCategoryId);
	}

	/**
	 * Returns the zendesk category with the primary key.
	 *
	 * @param zendeskCategoryId the primary key of the zendesk category
	 * @return the zendesk category
	 * @throws PortalException if a zendesk category with the primary key could not be found
	 */
	@Override
	public ZendeskCategory getZendeskCategory(long zendeskCategoryId)
		throws PortalException {

		return zendeskCategoryPersistence.findByPrimaryKey(zendeskCategoryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(zendeskCategoryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ZendeskCategory.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("zendeskCategoryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			zendeskCategoryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ZendeskCategory.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"zendeskCategoryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(zendeskCategoryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ZendeskCategory.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("zendeskCategoryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return zendeskCategoryLocalService.deleteZendeskCategory(
			(ZendeskCategory)persistedModel);
	}

	public BasePersistence<ZendeskCategory> getBasePersistence() {
		return zendeskCategoryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return zendeskCategoryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the zendesk categories.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.customer.zendesk.documentation.sync.model.impl.ZendeskCategoryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of zendesk categories
	 * @param end the upper bound of the range of zendesk categories (not inclusive)
	 * @return the range of zendesk categories
	 */
	@Override
	public List<ZendeskCategory> getZendeskCategories(int start, int end) {
		return zendeskCategoryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of zendesk categories.
	 *
	 * @return the number of zendesk categories
	 */
	@Override
	public int getZendeskCategoriesCount() {
		return zendeskCategoryPersistence.countAll();
	}

	/**
	 * Updates the zendesk category in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ZendeskCategoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param zendeskCategory the zendesk category
	 * @return the zendesk category that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ZendeskCategory updateZendeskCategory(
		ZendeskCategory zendeskCategory) {

		return zendeskCategoryPersistence.update(zendeskCategory);
	}

	/**
	 * Returns the zendesk article local service.
	 *
	 * @return the zendesk article local service
	 */
	public com.liferay.osb.customer.zendesk.documentation.sync.service.
		ZendeskArticleLocalService getZendeskArticleLocalService() {

		return zendeskArticleLocalService;
	}

	/**
	 * Sets the zendesk article local service.
	 *
	 * @param zendeskArticleLocalService the zendesk article local service
	 */
	public void setZendeskArticleLocalService(
		com.liferay.osb.customer.zendesk.documentation.sync.service.
			ZendeskArticleLocalService zendeskArticleLocalService) {

		this.zendeskArticleLocalService = zendeskArticleLocalService;
	}

	/**
	 * Returns the zendesk article persistence.
	 *
	 * @return the zendesk article persistence
	 */
	public ZendeskArticlePersistence getZendeskArticlePersistence() {
		return zendeskArticlePersistence;
	}

	/**
	 * Sets the zendesk article persistence.
	 *
	 * @param zendeskArticlePersistence the zendesk article persistence
	 */
	public void setZendeskArticlePersistence(
		ZendeskArticlePersistence zendeskArticlePersistence) {

		this.zendeskArticlePersistence = zendeskArticlePersistence;
	}

	/**
	 * Returns the zendesk article attachment local service.
	 *
	 * @return the zendesk article attachment local service
	 */
	public com.liferay.osb.customer.zendesk.documentation.sync.service.
		ZendeskArticleAttachmentLocalService
			getZendeskArticleAttachmentLocalService() {

		return zendeskArticleAttachmentLocalService;
	}

	/**
	 * Sets the zendesk article attachment local service.
	 *
	 * @param zendeskArticleAttachmentLocalService the zendesk article attachment local service
	 */
	public void setZendeskArticleAttachmentLocalService(
		com.liferay.osb.customer.zendesk.documentation.sync.service.
			ZendeskArticleAttachmentLocalService
				zendeskArticleAttachmentLocalService) {

		this.zendeskArticleAttachmentLocalService =
			zendeskArticleAttachmentLocalService;
	}

	/**
	 * Returns the zendesk article attachment persistence.
	 *
	 * @return the zendesk article attachment persistence
	 */
	public ZendeskArticleAttachmentPersistence
		getZendeskArticleAttachmentPersistence() {

		return zendeskArticleAttachmentPersistence;
	}

	/**
	 * Sets the zendesk article attachment persistence.
	 *
	 * @param zendeskArticleAttachmentPersistence the zendesk article attachment persistence
	 */
	public void setZendeskArticleAttachmentPersistence(
		ZendeskArticleAttachmentPersistence
			zendeskArticleAttachmentPersistence) {

		this.zendeskArticleAttachmentPersistence =
			zendeskArticleAttachmentPersistence;
	}

	/**
	 * Returns the zendesk category local service.
	 *
	 * @return the zendesk category local service
	 */
	public ZendeskCategoryLocalService getZendeskCategoryLocalService() {
		return zendeskCategoryLocalService;
	}

	/**
	 * Sets the zendesk category local service.
	 *
	 * @param zendeskCategoryLocalService the zendesk category local service
	 */
	public void setZendeskCategoryLocalService(
		ZendeskCategoryLocalService zendeskCategoryLocalService) {

		this.zendeskCategoryLocalService = zendeskCategoryLocalService;
	}

	/**
	 * Returns the zendesk category persistence.
	 *
	 * @return the zendesk category persistence
	 */
	public ZendeskCategoryPersistence getZendeskCategoryPersistence() {
		return zendeskCategoryPersistence;
	}

	/**
	 * Sets the zendesk category persistence.
	 *
	 * @param zendeskCategoryPersistence the zendesk category persistence
	 */
	public void setZendeskCategoryPersistence(
		ZendeskCategoryPersistence zendeskCategoryPersistence) {

		this.zendeskCategoryPersistence = zendeskCategoryPersistence;
	}

	/**
	 * Returns the zendesk section local service.
	 *
	 * @return the zendesk section local service
	 */
	public com.liferay.osb.customer.zendesk.documentation.sync.service.
		ZendeskSectionLocalService getZendeskSectionLocalService() {

		return zendeskSectionLocalService;
	}

	/**
	 * Sets the zendesk section local service.
	 *
	 * @param zendeskSectionLocalService the zendesk section local service
	 */
	public void setZendeskSectionLocalService(
		com.liferay.osb.customer.zendesk.documentation.sync.service.
			ZendeskSectionLocalService zendeskSectionLocalService) {

		this.zendeskSectionLocalService = zendeskSectionLocalService;
	}

	/**
	 * Returns the zendesk section persistence.
	 *
	 * @return the zendesk section persistence
	 */
	public ZendeskSectionPersistence getZendeskSectionPersistence() {
		return zendeskSectionPersistence;
	}

	/**
	 * Sets the zendesk section persistence.
	 *
	 * @param zendeskSectionPersistence the zendesk section persistence
	 */
	public void setZendeskSectionPersistence(
		ZendeskSectionPersistence zendeskSectionPersistence) {

		this.zendeskSectionPersistence = zendeskSectionPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskCategory",
			zendeskCategoryLocalService);

		ZendeskCategoryLocalServiceUtil.setService(zendeskCategoryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskCategory");

		ZendeskCategoryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ZendeskCategoryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ZendeskCategory.class;
	}

	protected String getModelClassName() {
		return ZendeskCategory.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = zendeskCategoryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.osb.customer.zendesk.documentation.sync.service.ZendeskArticleLocalService.class
	)
	protected com.liferay.osb.customer.zendesk.documentation.sync.service.
		ZendeskArticleLocalService zendeskArticleLocalService;

	@BeanReference(type = ZendeskArticlePersistence.class)
	protected ZendeskArticlePersistence zendeskArticlePersistence;

	@BeanReference(
		type = com.liferay.osb.customer.zendesk.documentation.sync.service.ZendeskArticleAttachmentLocalService.class
	)
	protected com.liferay.osb.customer.zendesk.documentation.sync.service.
		ZendeskArticleAttachmentLocalService
			zendeskArticleAttachmentLocalService;

	@BeanReference(type = ZendeskArticleAttachmentPersistence.class)
	protected ZendeskArticleAttachmentPersistence
		zendeskArticleAttachmentPersistence;

	@BeanReference(type = ZendeskCategoryLocalService.class)
	protected ZendeskCategoryLocalService zendeskCategoryLocalService;

	@BeanReference(type = ZendeskCategoryPersistence.class)
	protected ZendeskCategoryPersistence zendeskCategoryPersistence;

	@BeanReference(
		type = com.liferay.osb.customer.zendesk.documentation.sync.service.ZendeskSectionLocalService.class
	)
	protected com.liferay.osb.customer.zendesk.documentation.sync.service.
		ZendeskSectionLocalService zendeskSectionLocalService;

	@BeanReference(type = ZendeskSectionPersistence.class)
	protected ZendeskSectionPersistence zendeskSectionPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		ZendeskCategoryLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}