/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.loop.asset.entry.set.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.loop.asset.entry.set.model.AssetEntrySet;
import com.liferay.osb.loop.asset.entry.set.model.AssetEntrySetModel;
import com.liferay.osb.loop.asset.entry.set.model.AssetEntrySetSoap;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssetEntrySet service. Represents a row in the &quot;AssetEntrySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssetEntrySetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntrySetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntrySetImpl
 * @generated
 */
@JSON(strict = true)
public class AssetEntrySetModelImpl
	extends BaseModelImpl<AssetEntrySet> implements AssetEntrySetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry set model instance should use the <code>AssetEntrySet</code> interface instead.
	 */
	public static final String TABLE_NAME = "AssetEntrySet";

	public static final Object[][] TABLE_COLUMNS = {
		{"assetEntrySetId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createTime", Types.BIGINT},
		{"modifiedTime", Types.BIGINT}, {"assetEntryId", Types.BIGINT},
		{"parentAssetEntrySetId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"creatorClassNameId", Types.BIGINT},
		{"creatorClassPK", Types.BIGINT}, {"creatorName", Types.VARCHAR},
		{"assetEntrySetLikesCount", Types.INTEGER},
		{"childAssetEntrySetsCount", Types.INTEGER}, {"level", Types.INTEGER},
		{"payload", Types.VARCHAR}, {"privateAssetEntrySet", Types.BOOLEAN},
		{"stickyTime", Types.BIGINT}, {"title", Types.VARCHAR},
		{"type_", Types.INTEGER}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("assetEntrySetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentAssetEntrySetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("creatorClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("creatorClassPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("creatorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetEntrySetLikesCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("childAssetEntrySetsCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("level", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("payload", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("privateAssetEntrySet", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("stickyTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AssetEntrySet (assetEntrySetId LONG not null primary key,companyId LONG,userId LONG,createTime LONG,modifiedTime LONG,assetEntryId LONG,parentAssetEntrySetId LONG,classNameId LONG,classPK LONG,creatorClassNameId LONG,creatorClassPK LONG,creatorName VARCHAR(75) null,assetEntrySetLikesCount INTEGER,childAssetEntrySetsCount INTEGER,level INTEGER,payload STRING null,privateAssetEntrySet BOOLEAN,stickyTime LONG,title VARCHAR(255) null,type_ INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table AssetEntrySet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assetEntrySet.createTime DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AssetEntrySet.createTime DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.asset.entry.set.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.loop.asset.entry.set.model.AssetEntrySet"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.asset.entry.set.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.loop.asset.entry.set.model.AssetEntrySet"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.asset.entry.set.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.loop.asset.entry.set.model.AssetEntrySet"),
		true);

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long CREATETIME_COLUMN_BITMASK = 4L;

	public static final long CREATORCLASSNAMEID_COLUMN_BITMASK = 8L;

	public static final long CREATORCLASSPK_COLUMN_BITMASK = 16L;

	public static final long PARENTASSETENTRYSETID_COLUMN_BITMASK = 32L;

	public static final long TITLE_COLUMN_BITMASK = 64L;

	public static final long TYPE_COLUMN_BITMASK = 128L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AssetEntrySet toModel(AssetEntrySetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AssetEntrySet model = new AssetEntrySetImpl();

		model.setAssetEntrySetId(soapModel.getAssetEntrySetId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateTime(soapModel.getCreateTime());
		model.setModifiedTime(soapModel.getModifiedTime());
		model.setAssetEntryId(soapModel.getAssetEntryId());
		model.setParentAssetEntrySetId(soapModel.getParentAssetEntrySetId());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setCreatorClassNameId(soapModel.getCreatorClassNameId());
		model.setCreatorClassPK(soapModel.getCreatorClassPK());
		model.setCreatorName(soapModel.getCreatorName());
		model.setAssetEntrySetLikesCount(
			soapModel.getAssetEntrySetLikesCount());
		model.setChildAssetEntrySetsCount(
			soapModel.getChildAssetEntrySetsCount());
		model.setLevel(soapModel.getLevel());
		model.setPayload(soapModel.getPayload());
		model.setPrivateAssetEntrySet(soapModel.isPrivateAssetEntrySet());
		model.setStickyTime(soapModel.getStickyTime());
		model.setTitle(soapModel.getTitle());
		model.setType(soapModel.getType());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AssetEntrySet> toModels(AssetEntrySetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AssetEntrySet> models = new ArrayList<AssetEntrySet>(
			soapModels.length);

		for (AssetEntrySetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.loop.asset.entry.set.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.loop.asset.entry.set.model.AssetEntrySet"));

	public AssetEntrySetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetEntrySetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetEntrySetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetEntrySetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetEntrySet.class;
	}

	@Override
	public String getModelClassName() {
		return AssetEntrySet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssetEntrySet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssetEntrySet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetEntrySet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AssetEntrySet)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssetEntrySet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssetEntrySet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssetEntrySet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssetEntrySet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssetEntrySet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AssetEntrySet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AssetEntrySet.class.getClassLoader(), AssetEntrySet.class,
			ModelWrapper.class);

		try {
			Constructor<AssetEntrySet> constructor =
				(Constructor<AssetEntrySet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AssetEntrySet, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<AssetEntrySet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AssetEntrySet, Object>>();

		attributeGetterFunctions.put(
			"assetEntrySetId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getAssetEntrySetId();
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getCompanyId();
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getUserId();
				}

			});
		attributeGetterFunctions.put(
			"createTime",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getCreateTime();
				}

			});
		attributeGetterFunctions.put(
			"modifiedTime",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getModifiedTime();
				}

			});
		attributeGetterFunctions.put(
			"assetEntryId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getAssetEntryId();
				}

			});
		attributeGetterFunctions.put(
			"parentAssetEntrySetId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getParentAssetEntrySetId();
				}

			});
		attributeGetterFunctions.put(
			"classNameId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getClassNameId();
				}

			});
		attributeGetterFunctions.put(
			"classPK",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getClassPK();
				}

			});
		attributeGetterFunctions.put(
			"creatorClassNameId",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getCreatorClassNameId();
				}

			});
		attributeGetterFunctions.put(
			"creatorClassPK",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getCreatorClassPK();
				}

			});
		attributeGetterFunctions.put(
			"creatorName",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getCreatorName();
				}

			});
		attributeGetterFunctions.put(
			"assetEntrySetLikesCount",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getAssetEntrySetLikesCount();
				}

			});
		attributeGetterFunctions.put(
			"childAssetEntrySetsCount",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getChildAssetEntrySetsCount();
				}

			});
		attributeGetterFunctions.put(
			"level",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getLevel();
				}

			});
		attributeGetterFunctions.put(
			"payload",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getPayload();
				}

			});
		attributeGetterFunctions.put(
			"privateAssetEntrySet",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getPrivateAssetEntrySet();
				}

			});
		attributeGetterFunctions.put(
			"stickyTime",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getStickyTime();
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getTitle();
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getType();
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<AssetEntrySet, Object>() {

				@Override
				public Object apply(AssetEntrySet assetEntrySet) {
					return assetEntrySet.getStatus();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<AssetEntrySet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<AssetEntrySet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AssetEntrySet, ?>>();

		attributeSetterBiConsumers.put(
			"assetEntrySetId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object assetEntrySetIdObject) {

					assetEntrySet.setAssetEntrySetId(
						(Long)assetEntrySetIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object companyIdObject) {

					assetEntrySet.setCompanyId((Long)companyIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object userIdObject) {

					assetEntrySet.setUserId((Long)userIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"createTime",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object createTimeObject) {

					assetEntrySet.setCreateTime((Long)createTimeObject);
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedTime",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object modifiedTimeObject) {

					assetEntrySet.setModifiedTime((Long)modifiedTimeObject);
				}

			});
		attributeSetterBiConsumers.put(
			"assetEntryId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object assetEntryIdObject) {

					assetEntrySet.setAssetEntryId((Long)assetEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"parentAssetEntrySetId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet,
					Object parentAssetEntrySetIdObject) {

					assetEntrySet.setParentAssetEntrySetId(
						(Long)parentAssetEntrySetIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object classNameIdObject) {

					assetEntrySet.setClassNameId((Long)classNameIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"classPK",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object classPKObject) {

					assetEntrySet.setClassPK((Long)classPKObject);
				}

			});
		attributeSetterBiConsumers.put(
			"creatorClassNameId",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet,
					Object creatorClassNameIdObject) {

					assetEntrySet.setCreatorClassNameId(
						(Long)creatorClassNameIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"creatorClassPK",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object creatorClassPKObject) {

					assetEntrySet.setCreatorClassPK((Long)creatorClassPKObject);
				}

			});
		attributeSetterBiConsumers.put(
			"creatorName",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object creatorNameObject) {

					assetEntrySet.setCreatorName((String)creatorNameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"assetEntrySetLikesCount",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet,
					Object assetEntrySetLikesCountObject) {

					assetEntrySet.setAssetEntrySetLikesCount(
						(Integer)assetEntrySetLikesCountObject);
				}

			});
		attributeSetterBiConsumers.put(
			"childAssetEntrySetsCount",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet,
					Object childAssetEntrySetsCountObject) {

					assetEntrySet.setChildAssetEntrySetsCount(
						(Integer)childAssetEntrySetsCountObject);
				}

			});
		attributeSetterBiConsumers.put(
			"level",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object levelObject) {

					assetEntrySet.setLevel((Integer)levelObject);
				}

			});
		attributeSetterBiConsumers.put(
			"payload",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object payloadObject) {

					assetEntrySet.setPayload((String)payloadObject);
				}

			});
		attributeSetterBiConsumers.put(
			"privateAssetEntrySet",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet,
					Object privateAssetEntrySetObject) {

					assetEntrySet.setPrivateAssetEntrySet(
						(Boolean)privateAssetEntrySetObject);
				}

			});
		attributeSetterBiConsumers.put(
			"stickyTime",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object stickyTimeObject) {

					assetEntrySet.setStickyTime((Long)stickyTimeObject);
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object titleObject) {

					assetEntrySet.setTitle((String)titleObject);
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object typeObject) {

					assetEntrySet.setType((Integer)typeObject);
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<AssetEntrySet, Object>() {

				@Override
				public void accept(
					AssetEntrySet assetEntrySet, Object statusObject) {

					assetEntrySet.setStatus((Integer)statusObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAssetEntrySetId() {
		return _assetEntrySetId;
	}

	@Override
	public void setAssetEntrySetId(long assetEntrySetId) {
		_assetEntrySetId = assetEntrySetId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		_columnBitmask = -1L;

		if (!_setOriginalCreateTime) {
			_setOriginalCreateTime = true;

			_originalCreateTime = _createTime;
		}

		_createTime = createTime;
	}

	public long getOriginalCreateTime() {
		return _originalCreateTime;
	}

	@JSON
	@Override
	public long getModifiedTime() {
		return _modifiedTime;
	}

	@Override
	public void setModifiedTime(long modifiedTime) {
		_modifiedTime = modifiedTime;
	}

	@JSON
	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_assetEntryId = assetEntryId;
	}

	@JSON
	@Override
	public long getParentAssetEntrySetId() {
		return _parentAssetEntrySetId;
	}

	@Override
	public void setParentAssetEntrySetId(long parentAssetEntrySetId) {
		_columnBitmask |= PARENTASSETENTRYSETID_COLUMN_BITMASK;

		if (!_setOriginalParentAssetEntrySetId) {
			_setOriginalParentAssetEntrySetId = true;

			_originalParentAssetEntrySetId = _parentAssetEntrySetId;
		}

		_parentAssetEntrySetId = parentAssetEntrySetId;
	}

	public long getOriginalParentAssetEntrySetId() {
		return _originalParentAssetEntrySetId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@JSON
	@Override
	public long getCreatorClassNameId() {
		return _creatorClassNameId;
	}

	@Override
	public void setCreatorClassNameId(long creatorClassNameId) {
		_columnBitmask |= CREATORCLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalCreatorClassNameId) {
			_setOriginalCreatorClassNameId = true;

			_originalCreatorClassNameId = _creatorClassNameId;
		}

		_creatorClassNameId = creatorClassNameId;
	}

	public long getOriginalCreatorClassNameId() {
		return _originalCreatorClassNameId;
	}

	@JSON
	@Override
	public long getCreatorClassPK() {
		return _creatorClassPK;
	}

	@Override
	public void setCreatorClassPK(long creatorClassPK) {
		_columnBitmask |= CREATORCLASSPK_COLUMN_BITMASK;

		if (!_setOriginalCreatorClassPK) {
			_setOriginalCreatorClassPK = true;

			_originalCreatorClassPK = _creatorClassPK;
		}

		_creatorClassPK = creatorClassPK;
	}

	public long getOriginalCreatorClassPK() {
		return _originalCreatorClassPK;
	}

	@JSON
	@Override
	public String getCreatorName() {
		if (_creatorName == null) {
			return "";
		}
		else {
			return _creatorName;
		}
	}

	@Override
	public void setCreatorName(String creatorName) {
		_creatorName = creatorName;
	}

	@JSON
	@Override
	public int getAssetEntrySetLikesCount() {
		return _assetEntrySetLikesCount;
	}

	@Override
	public void setAssetEntrySetLikesCount(int assetEntrySetLikesCount) {
		_assetEntrySetLikesCount = assetEntrySetLikesCount;
	}

	@JSON
	@Override
	public int getChildAssetEntrySetsCount() {
		return _childAssetEntrySetsCount;
	}

	@Override
	public void setChildAssetEntrySetsCount(int childAssetEntrySetsCount) {
		_childAssetEntrySetsCount = childAssetEntrySetsCount;
	}

	@JSON
	@Override
	public int getLevel() {
		return _level;
	}

	@Override
	public void setLevel(int level) {
		_level = level;
	}

	@JSON
	@Override
	public String getPayload() {
		if (_payload == null) {
			return "";
		}
		else {
			return _payload;
		}
	}

	@Override
	public void setPayload(String payload) {
		_payload = payload;
	}

	@JSON
	@Override
	public boolean getPrivateAssetEntrySet() {
		return _privateAssetEntrySet;
	}

	@JSON
	@Override
	public boolean isPrivateAssetEntrySet() {
		return _privateAssetEntrySet;
	}

	@Override
	public void setPrivateAssetEntrySet(boolean privateAssetEntrySet) {
		_privateAssetEntrySet = privateAssetEntrySet;
	}

	@JSON
	@Override
	public long getStickyTime() {
		return _stickyTime;
	}

	@Override
	public void setStickyTime(long stickyTime) {
		_stickyTime = stickyTime;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask |= TITLE_COLUMN_BITMASK;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssetEntrySet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetEntrySet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssetEntrySet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetEntrySetImpl assetEntrySetImpl = new AssetEntrySetImpl();

		assetEntrySetImpl.setAssetEntrySetId(getAssetEntrySetId());
		assetEntrySetImpl.setCompanyId(getCompanyId());
		assetEntrySetImpl.setUserId(getUserId());
		assetEntrySetImpl.setCreateTime(getCreateTime());
		assetEntrySetImpl.setModifiedTime(getModifiedTime());
		assetEntrySetImpl.setAssetEntryId(getAssetEntryId());
		assetEntrySetImpl.setParentAssetEntrySetId(getParentAssetEntrySetId());
		assetEntrySetImpl.setClassNameId(getClassNameId());
		assetEntrySetImpl.setClassPK(getClassPK());
		assetEntrySetImpl.setCreatorClassNameId(getCreatorClassNameId());
		assetEntrySetImpl.setCreatorClassPK(getCreatorClassPK());
		assetEntrySetImpl.setCreatorName(getCreatorName());
		assetEntrySetImpl.setAssetEntrySetLikesCount(
			getAssetEntrySetLikesCount());
		assetEntrySetImpl.setChildAssetEntrySetsCount(
			getChildAssetEntrySetsCount());
		assetEntrySetImpl.setLevel(getLevel());
		assetEntrySetImpl.setPayload(getPayload());
		assetEntrySetImpl.setPrivateAssetEntrySet(isPrivateAssetEntrySet());
		assetEntrySetImpl.setStickyTime(getStickyTime());
		assetEntrySetImpl.setTitle(getTitle());
		assetEntrySetImpl.setType(getType());
		assetEntrySetImpl.setStatus(getStatus());

		assetEntrySetImpl.resetOriginalValues();

		return assetEntrySetImpl;
	}

	@Override
	public int compareTo(AssetEntrySet assetEntrySet) {
		int value = 0;

		if (getCreateTime() < assetEntrySet.getCreateTime()) {
			value = -1;
		}
		else if (getCreateTime() > assetEntrySet.getCreateTime()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssetEntrySet)) {
			return false;
		}

		AssetEntrySet assetEntrySet = (AssetEntrySet)object;

		long primaryKey = assetEntrySet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalCreateTime = _createTime;

		_setOriginalCreateTime = false;

		_originalParentAssetEntrySetId = _parentAssetEntrySetId;

		_setOriginalParentAssetEntrySetId = false;

		_originalClassNameId = _classNameId;

		_setOriginalClassNameId = false;

		_originalClassPK = _classPK;

		_setOriginalClassPK = false;

		_originalCreatorClassNameId = _creatorClassNameId;

		_setOriginalCreatorClassNameId = false;

		_originalCreatorClassPK = _creatorClassPK;

		_setOriginalCreatorClassPK = false;

		_originalTitle = _title;

		_originalType = _type;

		_setOriginalType = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetEntrySet> toCacheModel() {
		AssetEntrySetCacheModel assetEntrySetCacheModel =
			new AssetEntrySetCacheModel();

		assetEntrySetCacheModel.assetEntrySetId = getAssetEntrySetId();

		assetEntrySetCacheModel.companyId = getCompanyId();

		assetEntrySetCacheModel.userId = getUserId();

		assetEntrySetCacheModel.createTime = getCreateTime();

		assetEntrySetCacheModel.modifiedTime = getModifiedTime();

		assetEntrySetCacheModel.assetEntryId = getAssetEntryId();

		assetEntrySetCacheModel.parentAssetEntrySetId =
			getParentAssetEntrySetId();

		assetEntrySetCacheModel.classNameId = getClassNameId();

		assetEntrySetCacheModel.classPK = getClassPK();

		assetEntrySetCacheModel.creatorClassNameId = getCreatorClassNameId();

		assetEntrySetCacheModel.creatorClassPK = getCreatorClassPK();

		assetEntrySetCacheModel.creatorName = getCreatorName();

		String creatorName = assetEntrySetCacheModel.creatorName;

		if ((creatorName != null) && (creatorName.length() == 0)) {
			assetEntrySetCacheModel.creatorName = null;
		}

		assetEntrySetCacheModel.assetEntrySetLikesCount =
			getAssetEntrySetLikesCount();

		assetEntrySetCacheModel.childAssetEntrySetsCount =
			getChildAssetEntrySetsCount();

		assetEntrySetCacheModel.level = getLevel();

		assetEntrySetCacheModel.payload = getPayload();

		String payload = assetEntrySetCacheModel.payload;

		if ((payload != null) && (payload.length() == 0)) {
			assetEntrySetCacheModel.payload = null;
		}

		assetEntrySetCacheModel.privateAssetEntrySet = isPrivateAssetEntrySet();

		assetEntrySetCacheModel.stickyTime = getStickyTime();

		assetEntrySetCacheModel.title = getTitle();

		String title = assetEntrySetCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			assetEntrySetCacheModel.title = null;
		}

		assetEntrySetCacheModel.type = getType();

		assetEntrySetCacheModel.status = getStatus();

		return assetEntrySetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssetEntrySet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssetEntrySet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetEntrySet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AssetEntrySet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AssetEntrySet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AssetEntrySet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetEntrySet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AssetEntrySet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AssetEntrySet>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _assetEntrySetId;
	private long _companyId;
	private long _userId;
	private long _createTime;
	private long _originalCreateTime;
	private boolean _setOriginalCreateTime;
	private long _modifiedTime;
	private long _assetEntryId;
	private long _parentAssetEntrySetId;
	private long _originalParentAssetEntrySetId;
	private boolean _setOriginalParentAssetEntrySetId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private long _creatorClassNameId;
	private long _originalCreatorClassNameId;
	private boolean _setOriginalCreatorClassNameId;
	private long _creatorClassPK;
	private long _originalCreatorClassPK;
	private boolean _setOriginalCreatorClassPK;
	private String _creatorName;
	private int _assetEntrySetLikesCount;
	private int _childAssetEntrySetsCount;
	private int _level;
	private String _payload;
	private boolean _privateAssetEntrySet;
	private long _stickyTime;
	private String _title;
	private String _originalTitle;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private int _status;
	private long _columnBitmask;
	private AssetEntrySet _escapedModel;

}