copyLibs {
	enabled = true
}

dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.java", version: "default"
	compileOnly project(":apps:foundation:petra:petra-xml")
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":core:registry-api")
	testIntegrationImplementation project(":dxp:apps:saml:saml-persistence-api")
	testIntegrationImplementation project(":dxp:apps:saml:saml-persistence-service")
}