copyLibs {
	enabled = true
}

dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.java", version: "default"
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:web-experience:trash:trash-test-util")
	testIntegrationImplementation project(":core:registry-api")
}