/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.fragment.web.internal.constants;

/**
 * @author Eudaldo Alonso
 */
public class FragmentWebKeys {

	public static final String FRAGMENT_COLLECTION_CONTRIBUTOR_TRACKER =
		"FRAGMENT_COLLECTION_CONTRIBUTOR_TRACKER";

	public static final String
		FRAGMENT_COLLECTION_RESOURCE_DROPDOWN_DEFAULT_EVENT_HANDLER =
			"FRAGMENT_COLLECTION_RESOURCE_DROPDOWN_DEFAULT_EVENT_HANDLER";

	public static final String FRAGMENT_COLLECTIONS = "FRAGMENT_COLLECTIONS";

	public static final String
		FRAGMENT_COMPOSITION_DROPDOWN_DEFAULT_EVENT_HANDLER =
			"FRAGMENT_COMPOSITION_DROPDOWN_DEFAULT_EVENT_HANDLER";

	public static final String FRAGMENT_ENTRY_DROPDOWN_DEFAULT_EVENT_HANDLER =
		"FRAGMENT_ENTRY_DROPDOWN_DEFAULT_EVENT_HANDLER";

	public static final String FRAGMENT_ENTRY_PROCESSOR_REGISTRY =
		"FRAGMENT_ENTRY_PROCESSOR_REGISTRY";

	public static final String INHERITED_FRAGMENT_COLLECTIONS =
		"INHERITED_FRAGMENT_COLLECTIONS";

	public static final String ITEM_SELECTOR = "ITEM_SELECTOR";

	public static final String SYSTEM_FRAGMENT_COLLECTIONS =
		"SYSTEM_FRAGMENT_COLLECTIONS";

}