dependencies {
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-xml", version: "2.9.8"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-yaml", version: "2.14.2"
	compileInclude group: "com.google.android", name: "annotations", version: "4.1.1.4"
	compileInclude group: "com.google.api", name: "api-common", version: "2.0.0"
	compileInclude group: "com.google.api", name: "gax", version: "2.0.0"
	compileInclude group: "com.google.api", name: "gax-grpc", version: "2.0.0"
	compileInclude group: "com.google.api.grpc", name: "proto-google-cloud-pubsub-v1", version: "1.95.6"
	compileInclude group: "com.google.api.grpc", name: "proto-google-common-protos", version: "2.3.2"
	compileInclude group: "com.google.api.grpc", name: "proto-google-iam-v1", version: "1.0.14"
	compileInclude group: "com.google.auth", name: "google-auth-library-credentials", version: "1.0.0"
	compileInclude group: "com.google.auth", name: "google-auth-library-oauth2-http", version: "1.0.0"
	compileInclude group: "com.google.auto.value", name: "auto-value-annotations", version: "1.8.2"
	compileInclude group: "com.google.cloud", name: "google-cloud-pubsub", version: "1.113.6"
	compileInclude group: "com.google.code.gson", name: "gson", version: "2.8.7"
	compileInclude group: "com.google.errorprone", name: "error_prone_annotations", version: "2.8.1"
	compileInclude group: "com.google.guava", name: "failureaccess", version: "1.0.1"
	compileInclude group: "com.google.guava", name: "guava", version: "32.0.1-jre"
	compileInclude group: "com.google.http-client", name: "google-http-client", version: "1.39.2"
	compileInclude group: "com.google.http-client", name: "google-http-client-gson", version: "1.39.2"
	compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.21.7"
	compileInclude group: "com.google.protobuf", name: "protobuf-java-util", version: "3.21.7"
	compileInclude group: "io.grpc", name: "grpc-alts", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-api", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-auth", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-context", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-core", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-grpclb", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-netty-shaded", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-protobuf", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-protobuf-lite", version: "1.53.0"
	compileInclude group: "io.grpc", name: "grpc-stub", version: "1.53.0"
	compileInclude group: "io.opencensus", name: "opencensus-api", version: "0.28.0"
	compileInclude group: "io.opencensus", name: "opencensus-contrib-http-util", version: "0.28.0"
	compileInclude group: "io.perfmark", name: "perfmark-api", version: "0.23.0"
	compileInclude group: "javax.annotation", name: "javax.annotation-api", version: "1.3.2"
	compileInclude group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.13"
	compileInclude group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.14"
	compileInclude group: "org.apache.logging.log4j", name: "log4j-api", version: "2.17.1"
	compileInclude group: "org.apache.logging.log4j", name: "log4j-core", version: "2.17.1"
	compileInclude group: "org.checkerframework", name: "checker-qual", version: "3.8.0"
	compileInclude group: "org.codehaus.mojo", name: "animal-sniffer-annotations", version: "1.20"
	compileInclude group: "org.conscrypt", name: "conscrypt-openjdk-uber", version: "2.5.1"
	compileInclude group: "org.threeten", name: "threetenbp", version: "1.5.1"
	compileInclude group: "org.yaml", name: "snakeyaml", version: "2.0"

	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.osgi.util", version: "5.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.lang", version: "3.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "3.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "4.0.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":dxp:apps:osb:osb-distributed-messaging:osb-distributed-messaging-api")
	compileOnly project(":dxp:apps:osb:osb-distributed-messaging:osb-distributed-messaging-publishing-api")
	compileOnly project(":dxp:apps:osb:osb-distributed-messaging:osb-distributed-messaging-subscribing-api")
}