dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:subscription:subscription-api")
	testIntegrationImplementation project(":apps:subscription:subscription-service")
	testIntegrationImplementation project(":core:registry-api")
}