dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-api")
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-spi")
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-store-api")
}