/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.testray.service.base;

import com.liferay.osb.testray.model.TestrayRun;
import com.liferay.osb.testray.service.TestrayRunLocalService;
import com.liferay.osb.testray.service.TestrayRunLocalServiceUtil;
import com.liferay.osb.testray.service.persistence.TestrayArchivePersistence;
import com.liferay.osb.testray.service.persistence.TestrayAssignmentPersistence;
import com.liferay.osb.testray.service.persistence.TestrayBuildPersistence;
import com.liferay.osb.testray.service.persistence.TestrayCasePersistence;
import com.liferay.osb.testray.service.persistence.TestrayCaseResultPersistence;
import com.liferay.osb.testray.service.persistence.TestrayCaseResultWarningPersistence;
import com.liferay.osb.testray.service.persistence.TestrayCaseTypePersistence;
import com.liferay.osb.testray.service.persistence.TestrayComponentPersistence;
import com.liferay.osb.testray.service.persistence.TestrayFactorCategoryPersistence;
import com.liferay.osb.testray.service.persistence.TestrayFactorOptionPersistence;
import com.liferay.osb.testray.service.persistence.TestrayFactorPersistence;
import com.liferay.osb.testray.service.persistence.TestrayIssuePersistence;
import com.liferay.osb.testray.service.persistence.TestrayProductVersionPersistence;
import com.liferay.osb.testray.service.persistence.TestrayProjectPersistence;
import com.liferay.osb.testray.service.persistence.TestrayRequirementPersistence;
import com.liferay.osb.testray.service.persistence.TestrayRoutinePersistence;
import com.liferay.osb.testray.service.persistence.TestrayRunPersistence;
import com.liferay.osb.testray.service.persistence.TestraySubtaskPersistence;
import com.liferay.osb.testray.service.persistence.TestraySuitePersistence;
import com.liferay.osb.testray.service.persistence.TestrayTaskPersistence;
import com.liferay.osb.testray.service.persistence.TestrayTeamPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the testray run local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.testray.service.impl.TestrayRunLocalServiceImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see com.liferay.osb.testray.service.impl.TestrayRunLocalServiceImpl
 * @generated
 */
public abstract class TestrayRunLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, TestrayRunLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TestrayRunLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>TestrayRunLocalServiceUtil</code>.
	 */

	/**
	 * Adds the testray run to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TestrayRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param testrayRun the testray run
	 * @return the testray run that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TestrayRun addTestrayRun(TestrayRun testrayRun) {
		testrayRun.setNew(true);

		return testrayRunPersistence.update(testrayRun);
	}

	/**
	 * Creates a new testray run with the primary key. Does not add the testray run to the database.
	 *
	 * @param testrayRunId the primary key for the new testray run
	 * @return the new testray run
	 */
	@Override
	@Transactional(enabled = false)
	public TestrayRun createTestrayRun(long testrayRunId) {
		return testrayRunPersistence.create(testrayRunId);
	}

	/**
	 * Deletes the testray run with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TestrayRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param testrayRunId the primary key of the testray run
	 * @return the testray run that was removed
	 * @throws PortalException if a testray run with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TestrayRun deleteTestrayRun(long testrayRunId)
		throws PortalException {

		return testrayRunPersistence.remove(testrayRunId);
	}

	/**
	 * Deletes the testray run from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TestrayRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param testrayRun the testray run
	 * @return the testray run that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TestrayRun deleteTestrayRun(TestrayRun testrayRun) {
		return testrayRunPersistence.remove(testrayRun);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			TestrayRun.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return testrayRunPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.testray.model.impl.TestrayRunModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return testrayRunPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.testray.model.impl.TestrayRunModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return testrayRunPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return testrayRunPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return testrayRunPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public TestrayRun fetchTestrayRun(long testrayRunId) {
		return testrayRunPersistence.fetchByPrimaryKey(testrayRunId);
	}

	/**
	 * Returns the testray run with the primary key.
	 *
	 * @param testrayRunId the primary key of the testray run
	 * @return the testray run
	 * @throws PortalException if a testray run with the primary key could not be found
	 */
	@Override
	public TestrayRun getTestrayRun(long testrayRunId) throws PortalException {
		return testrayRunPersistence.findByPrimaryKey(testrayRunId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(testrayRunLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TestrayRun.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("testrayRunId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			testrayRunLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(TestrayRun.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"testrayRunId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(testrayRunLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TestrayRun.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("testrayRunId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return testrayRunLocalService.deleteTestrayRun(
			(TestrayRun)persistedModel);
	}

	public BasePersistence<TestrayRun> getBasePersistence() {
		return testrayRunPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return testrayRunPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the testray runs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.testray.model.impl.TestrayRunModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of testray runs
	 * @param end the upper bound of the range of testray runs (not inclusive)
	 * @return the range of testray runs
	 */
	@Override
	public List<TestrayRun> getTestrayRuns(int start, int end) {
		return testrayRunPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of testray runs.
	 *
	 * @return the number of testray runs
	 */
	@Override
	public int getTestrayRunsCount() {
		return testrayRunPersistence.countAll();
	}

	/**
	 * Updates the testray run in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TestrayRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param testrayRun the testray run
	 * @return the testray run that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TestrayRun updateTestrayRun(TestrayRun testrayRun) {
		return testrayRunPersistence.update(testrayRun);
	}

	/**
	 * Returns the testray archive local service.
	 *
	 * @return the testray archive local service
	 */
	public com.liferay.osb.testray.service.TestrayArchiveLocalService
		getTestrayArchiveLocalService() {

		return testrayArchiveLocalService;
	}

	/**
	 * Sets the testray archive local service.
	 *
	 * @param testrayArchiveLocalService the testray archive local service
	 */
	public void setTestrayArchiveLocalService(
		com.liferay.osb.testray.service.TestrayArchiveLocalService
			testrayArchiveLocalService) {

		this.testrayArchiveLocalService = testrayArchiveLocalService;
	}

	/**
	 * Returns the testray archive persistence.
	 *
	 * @return the testray archive persistence
	 */
	public TestrayArchivePersistence getTestrayArchivePersistence() {
		return testrayArchivePersistence;
	}

	/**
	 * Sets the testray archive persistence.
	 *
	 * @param testrayArchivePersistence the testray archive persistence
	 */
	public void setTestrayArchivePersistence(
		TestrayArchivePersistence testrayArchivePersistence) {

		this.testrayArchivePersistence = testrayArchivePersistence;
	}

	/**
	 * Returns the testray assignment local service.
	 *
	 * @return the testray assignment local service
	 */
	public com.liferay.osb.testray.service.TestrayAssignmentLocalService
		getTestrayAssignmentLocalService() {

		return testrayAssignmentLocalService;
	}

	/**
	 * Sets the testray assignment local service.
	 *
	 * @param testrayAssignmentLocalService the testray assignment local service
	 */
	public void setTestrayAssignmentLocalService(
		com.liferay.osb.testray.service.TestrayAssignmentLocalService
			testrayAssignmentLocalService) {

		this.testrayAssignmentLocalService = testrayAssignmentLocalService;
	}

	/**
	 * Returns the testray assignment persistence.
	 *
	 * @return the testray assignment persistence
	 */
	public TestrayAssignmentPersistence getTestrayAssignmentPersistence() {
		return testrayAssignmentPersistence;
	}

	/**
	 * Sets the testray assignment persistence.
	 *
	 * @param testrayAssignmentPersistence the testray assignment persistence
	 */
	public void setTestrayAssignmentPersistence(
		TestrayAssignmentPersistence testrayAssignmentPersistence) {

		this.testrayAssignmentPersistence = testrayAssignmentPersistence;
	}

	/**
	 * Returns the testray build local service.
	 *
	 * @return the testray build local service
	 */
	public com.liferay.osb.testray.service.TestrayBuildLocalService
		getTestrayBuildLocalService() {

		return testrayBuildLocalService;
	}

	/**
	 * Sets the testray build local service.
	 *
	 * @param testrayBuildLocalService the testray build local service
	 */
	public void setTestrayBuildLocalService(
		com.liferay.osb.testray.service.TestrayBuildLocalService
			testrayBuildLocalService) {

		this.testrayBuildLocalService = testrayBuildLocalService;
	}

	/**
	 * Returns the testray build persistence.
	 *
	 * @return the testray build persistence
	 */
	public TestrayBuildPersistence getTestrayBuildPersistence() {
		return testrayBuildPersistence;
	}

	/**
	 * Sets the testray build persistence.
	 *
	 * @param testrayBuildPersistence the testray build persistence
	 */
	public void setTestrayBuildPersistence(
		TestrayBuildPersistence testrayBuildPersistence) {

		this.testrayBuildPersistence = testrayBuildPersistence;
	}

	/**
	 * Returns the testray case local service.
	 *
	 * @return the testray case local service
	 */
	public com.liferay.osb.testray.service.TestrayCaseLocalService
		getTestrayCaseLocalService() {

		return testrayCaseLocalService;
	}

	/**
	 * Sets the testray case local service.
	 *
	 * @param testrayCaseLocalService the testray case local service
	 */
	public void setTestrayCaseLocalService(
		com.liferay.osb.testray.service.TestrayCaseLocalService
			testrayCaseLocalService) {

		this.testrayCaseLocalService = testrayCaseLocalService;
	}

	/**
	 * Returns the testray case persistence.
	 *
	 * @return the testray case persistence
	 */
	public TestrayCasePersistence getTestrayCasePersistence() {
		return testrayCasePersistence;
	}

	/**
	 * Sets the testray case persistence.
	 *
	 * @param testrayCasePersistence the testray case persistence
	 */
	public void setTestrayCasePersistence(
		TestrayCasePersistence testrayCasePersistence) {

		this.testrayCasePersistence = testrayCasePersistence;
	}

	/**
	 * Returns the testray case result local service.
	 *
	 * @return the testray case result local service
	 */
	public com.liferay.osb.testray.service.TestrayCaseResultLocalService
		getTestrayCaseResultLocalService() {

		return testrayCaseResultLocalService;
	}

	/**
	 * Sets the testray case result local service.
	 *
	 * @param testrayCaseResultLocalService the testray case result local service
	 */
	public void setTestrayCaseResultLocalService(
		com.liferay.osb.testray.service.TestrayCaseResultLocalService
			testrayCaseResultLocalService) {

		this.testrayCaseResultLocalService = testrayCaseResultLocalService;
	}

	/**
	 * Returns the testray case result persistence.
	 *
	 * @return the testray case result persistence
	 */
	public TestrayCaseResultPersistence getTestrayCaseResultPersistence() {
		return testrayCaseResultPersistence;
	}

	/**
	 * Sets the testray case result persistence.
	 *
	 * @param testrayCaseResultPersistence the testray case result persistence
	 */
	public void setTestrayCaseResultPersistence(
		TestrayCaseResultPersistence testrayCaseResultPersistence) {

		this.testrayCaseResultPersistence = testrayCaseResultPersistence;
	}

	/**
	 * Returns the testray case result warning local service.
	 *
	 * @return the testray case result warning local service
	 */
	public com.liferay.osb.testray.service.TestrayCaseResultWarningLocalService
		getTestrayCaseResultWarningLocalService() {

		return testrayCaseResultWarningLocalService;
	}

	/**
	 * Sets the testray case result warning local service.
	 *
	 * @param testrayCaseResultWarningLocalService the testray case result warning local service
	 */
	public void setTestrayCaseResultWarningLocalService(
		com.liferay.osb.testray.service.TestrayCaseResultWarningLocalService
			testrayCaseResultWarningLocalService) {

		this.testrayCaseResultWarningLocalService =
			testrayCaseResultWarningLocalService;
	}

	/**
	 * Returns the testray case result warning persistence.
	 *
	 * @return the testray case result warning persistence
	 */
	public TestrayCaseResultWarningPersistence
		getTestrayCaseResultWarningPersistence() {

		return testrayCaseResultWarningPersistence;
	}

	/**
	 * Sets the testray case result warning persistence.
	 *
	 * @param testrayCaseResultWarningPersistence the testray case result warning persistence
	 */
	public void setTestrayCaseResultWarningPersistence(
		TestrayCaseResultWarningPersistence
			testrayCaseResultWarningPersistence) {

		this.testrayCaseResultWarningPersistence =
			testrayCaseResultWarningPersistence;
	}

	/**
	 * Returns the testray case type local service.
	 *
	 * @return the testray case type local service
	 */
	public com.liferay.osb.testray.service.TestrayCaseTypeLocalService
		getTestrayCaseTypeLocalService() {

		return testrayCaseTypeLocalService;
	}

	/**
	 * Sets the testray case type local service.
	 *
	 * @param testrayCaseTypeLocalService the testray case type local service
	 */
	public void setTestrayCaseTypeLocalService(
		com.liferay.osb.testray.service.TestrayCaseTypeLocalService
			testrayCaseTypeLocalService) {

		this.testrayCaseTypeLocalService = testrayCaseTypeLocalService;
	}

	/**
	 * Returns the testray case type persistence.
	 *
	 * @return the testray case type persistence
	 */
	public TestrayCaseTypePersistence getTestrayCaseTypePersistence() {
		return testrayCaseTypePersistence;
	}

	/**
	 * Sets the testray case type persistence.
	 *
	 * @param testrayCaseTypePersistence the testray case type persistence
	 */
	public void setTestrayCaseTypePersistence(
		TestrayCaseTypePersistence testrayCaseTypePersistence) {

		this.testrayCaseTypePersistence = testrayCaseTypePersistence;
	}

	/**
	 * Returns the testray component local service.
	 *
	 * @return the testray component local service
	 */
	public com.liferay.osb.testray.service.TestrayComponentLocalService
		getTestrayComponentLocalService() {

		return testrayComponentLocalService;
	}

	/**
	 * Sets the testray component local service.
	 *
	 * @param testrayComponentLocalService the testray component local service
	 */
	public void setTestrayComponentLocalService(
		com.liferay.osb.testray.service.TestrayComponentLocalService
			testrayComponentLocalService) {

		this.testrayComponentLocalService = testrayComponentLocalService;
	}

	/**
	 * Returns the testray component persistence.
	 *
	 * @return the testray component persistence
	 */
	public TestrayComponentPersistence getTestrayComponentPersistence() {
		return testrayComponentPersistence;
	}

	/**
	 * Sets the testray component persistence.
	 *
	 * @param testrayComponentPersistence the testray component persistence
	 */
	public void setTestrayComponentPersistence(
		TestrayComponentPersistence testrayComponentPersistence) {

		this.testrayComponentPersistence = testrayComponentPersistence;
	}

	/**
	 * Returns the testray factor local service.
	 *
	 * @return the testray factor local service
	 */
	public com.liferay.osb.testray.service.TestrayFactorLocalService
		getTestrayFactorLocalService() {

		return testrayFactorLocalService;
	}

	/**
	 * Sets the testray factor local service.
	 *
	 * @param testrayFactorLocalService the testray factor local service
	 */
	public void setTestrayFactorLocalService(
		com.liferay.osb.testray.service.TestrayFactorLocalService
			testrayFactorLocalService) {

		this.testrayFactorLocalService = testrayFactorLocalService;
	}

	/**
	 * Returns the testray factor persistence.
	 *
	 * @return the testray factor persistence
	 */
	public TestrayFactorPersistence getTestrayFactorPersistence() {
		return testrayFactorPersistence;
	}

	/**
	 * Sets the testray factor persistence.
	 *
	 * @param testrayFactorPersistence the testray factor persistence
	 */
	public void setTestrayFactorPersistence(
		TestrayFactorPersistence testrayFactorPersistence) {

		this.testrayFactorPersistence = testrayFactorPersistence;
	}

	/**
	 * Returns the testray factor category local service.
	 *
	 * @return the testray factor category local service
	 */
	public com.liferay.osb.testray.service.TestrayFactorCategoryLocalService
		getTestrayFactorCategoryLocalService() {

		return testrayFactorCategoryLocalService;
	}

	/**
	 * Sets the testray factor category local service.
	 *
	 * @param testrayFactorCategoryLocalService the testray factor category local service
	 */
	public void setTestrayFactorCategoryLocalService(
		com.liferay.osb.testray.service.TestrayFactorCategoryLocalService
			testrayFactorCategoryLocalService) {

		this.testrayFactorCategoryLocalService =
			testrayFactorCategoryLocalService;
	}

	/**
	 * Returns the testray factor category persistence.
	 *
	 * @return the testray factor category persistence
	 */
	public TestrayFactorCategoryPersistence
		getTestrayFactorCategoryPersistence() {

		return testrayFactorCategoryPersistence;
	}

	/**
	 * Sets the testray factor category persistence.
	 *
	 * @param testrayFactorCategoryPersistence the testray factor category persistence
	 */
	public void setTestrayFactorCategoryPersistence(
		TestrayFactorCategoryPersistence testrayFactorCategoryPersistence) {

		this.testrayFactorCategoryPersistence =
			testrayFactorCategoryPersistence;
	}

	/**
	 * Returns the testray factor option local service.
	 *
	 * @return the testray factor option local service
	 */
	public com.liferay.osb.testray.service.TestrayFactorOptionLocalService
		getTestrayFactorOptionLocalService() {

		return testrayFactorOptionLocalService;
	}

	/**
	 * Sets the testray factor option local service.
	 *
	 * @param testrayFactorOptionLocalService the testray factor option local service
	 */
	public void setTestrayFactorOptionLocalService(
		com.liferay.osb.testray.service.TestrayFactorOptionLocalService
			testrayFactorOptionLocalService) {

		this.testrayFactorOptionLocalService = testrayFactorOptionLocalService;
	}

	/**
	 * Returns the testray factor option persistence.
	 *
	 * @return the testray factor option persistence
	 */
	public TestrayFactorOptionPersistence getTestrayFactorOptionPersistence() {
		return testrayFactorOptionPersistence;
	}

	/**
	 * Sets the testray factor option persistence.
	 *
	 * @param testrayFactorOptionPersistence the testray factor option persistence
	 */
	public void setTestrayFactorOptionPersistence(
		TestrayFactorOptionPersistence testrayFactorOptionPersistence) {

		this.testrayFactorOptionPersistence = testrayFactorOptionPersistence;
	}

	/**
	 * Returns the testray issue local service.
	 *
	 * @return the testray issue local service
	 */
	public com.liferay.osb.testray.service.TestrayIssueLocalService
		getTestrayIssueLocalService() {

		return testrayIssueLocalService;
	}

	/**
	 * Sets the testray issue local service.
	 *
	 * @param testrayIssueLocalService the testray issue local service
	 */
	public void setTestrayIssueLocalService(
		com.liferay.osb.testray.service.TestrayIssueLocalService
			testrayIssueLocalService) {

		this.testrayIssueLocalService = testrayIssueLocalService;
	}

	/**
	 * Returns the testray issue persistence.
	 *
	 * @return the testray issue persistence
	 */
	public TestrayIssuePersistence getTestrayIssuePersistence() {
		return testrayIssuePersistence;
	}

	/**
	 * Sets the testray issue persistence.
	 *
	 * @param testrayIssuePersistence the testray issue persistence
	 */
	public void setTestrayIssuePersistence(
		TestrayIssuePersistence testrayIssuePersistence) {

		this.testrayIssuePersistence = testrayIssuePersistence;
	}

	/**
	 * Returns the testray product version local service.
	 *
	 * @return the testray product version local service
	 */
	public com.liferay.osb.testray.service.TestrayProductVersionLocalService
		getTestrayProductVersionLocalService() {

		return testrayProductVersionLocalService;
	}

	/**
	 * Sets the testray product version local service.
	 *
	 * @param testrayProductVersionLocalService the testray product version local service
	 */
	public void setTestrayProductVersionLocalService(
		com.liferay.osb.testray.service.TestrayProductVersionLocalService
			testrayProductVersionLocalService) {

		this.testrayProductVersionLocalService =
			testrayProductVersionLocalService;
	}

	/**
	 * Returns the testray product version persistence.
	 *
	 * @return the testray product version persistence
	 */
	public TestrayProductVersionPersistence
		getTestrayProductVersionPersistence() {

		return testrayProductVersionPersistence;
	}

	/**
	 * Sets the testray product version persistence.
	 *
	 * @param testrayProductVersionPersistence the testray product version persistence
	 */
	public void setTestrayProductVersionPersistence(
		TestrayProductVersionPersistence testrayProductVersionPersistence) {

		this.testrayProductVersionPersistence =
			testrayProductVersionPersistence;
	}

	/**
	 * Returns the testray project local service.
	 *
	 * @return the testray project local service
	 */
	public com.liferay.osb.testray.service.TestrayProjectLocalService
		getTestrayProjectLocalService() {

		return testrayProjectLocalService;
	}

	/**
	 * Sets the testray project local service.
	 *
	 * @param testrayProjectLocalService the testray project local service
	 */
	public void setTestrayProjectLocalService(
		com.liferay.osb.testray.service.TestrayProjectLocalService
			testrayProjectLocalService) {

		this.testrayProjectLocalService = testrayProjectLocalService;
	}

	/**
	 * Returns the testray project persistence.
	 *
	 * @return the testray project persistence
	 */
	public TestrayProjectPersistence getTestrayProjectPersistence() {
		return testrayProjectPersistence;
	}

	/**
	 * Sets the testray project persistence.
	 *
	 * @param testrayProjectPersistence the testray project persistence
	 */
	public void setTestrayProjectPersistence(
		TestrayProjectPersistence testrayProjectPersistence) {

		this.testrayProjectPersistence = testrayProjectPersistence;
	}

	/**
	 * Returns the testray requirement local service.
	 *
	 * @return the testray requirement local service
	 */
	public com.liferay.osb.testray.service.TestrayRequirementLocalService
		getTestrayRequirementLocalService() {

		return testrayRequirementLocalService;
	}

	/**
	 * Sets the testray requirement local service.
	 *
	 * @param testrayRequirementLocalService the testray requirement local service
	 */
	public void setTestrayRequirementLocalService(
		com.liferay.osb.testray.service.TestrayRequirementLocalService
			testrayRequirementLocalService) {

		this.testrayRequirementLocalService = testrayRequirementLocalService;
	}

	/**
	 * Returns the testray requirement persistence.
	 *
	 * @return the testray requirement persistence
	 */
	public TestrayRequirementPersistence getTestrayRequirementPersistence() {
		return testrayRequirementPersistence;
	}

	/**
	 * Sets the testray requirement persistence.
	 *
	 * @param testrayRequirementPersistence the testray requirement persistence
	 */
	public void setTestrayRequirementPersistence(
		TestrayRequirementPersistence testrayRequirementPersistence) {

		this.testrayRequirementPersistence = testrayRequirementPersistence;
	}

	/**
	 * Returns the testray routine local service.
	 *
	 * @return the testray routine local service
	 */
	public com.liferay.osb.testray.service.TestrayRoutineLocalService
		getTestrayRoutineLocalService() {

		return testrayRoutineLocalService;
	}

	/**
	 * Sets the testray routine local service.
	 *
	 * @param testrayRoutineLocalService the testray routine local service
	 */
	public void setTestrayRoutineLocalService(
		com.liferay.osb.testray.service.TestrayRoutineLocalService
			testrayRoutineLocalService) {

		this.testrayRoutineLocalService = testrayRoutineLocalService;
	}

	/**
	 * Returns the testray routine persistence.
	 *
	 * @return the testray routine persistence
	 */
	public TestrayRoutinePersistence getTestrayRoutinePersistence() {
		return testrayRoutinePersistence;
	}

	/**
	 * Sets the testray routine persistence.
	 *
	 * @param testrayRoutinePersistence the testray routine persistence
	 */
	public void setTestrayRoutinePersistence(
		TestrayRoutinePersistence testrayRoutinePersistence) {

		this.testrayRoutinePersistence = testrayRoutinePersistence;
	}

	/**
	 * Returns the testray run local service.
	 *
	 * @return the testray run local service
	 */
	public TestrayRunLocalService getTestrayRunLocalService() {
		return testrayRunLocalService;
	}

	/**
	 * Sets the testray run local service.
	 *
	 * @param testrayRunLocalService the testray run local service
	 */
	public void setTestrayRunLocalService(
		TestrayRunLocalService testrayRunLocalService) {

		this.testrayRunLocalService = testrayRunLocalService;
	}

	/**
	 * Returns the testray run persistence.
	 *
	 * @return the testray run persistence
	 */
	public TestrayRunPersistence getTestrayRunPersistence() {
		return testrayRunPersistence;
	}

	/**
	 * Sets the testray run persistence.
	 *
	 * @param testrayRunPersistence the testray run persistence
	 */
	public void setTestrayRunPersistence(
		TestrayRunPersistence testrayRunPersistence) {

		this.testrayRunPersistence = testrayRunPersistence;
	}

	/**
	 * Returns the testray subtask local service.
	 *
	 * @return the testray subtask local service
	 */
	public com.liferay.osb.testray.service.TestraySubtaskLocalService
		getTestraySubtaskLocalService() {

		return testraySubtaskLocalService;
	}

	/**
	 * Sets the testray subtask local service.
	 *
	 * @param testraySubtaskLocalService the testray subtask local service
	 */
	public void setTestraySubtaskLocalService(
		com.liferay.osb.testray.service.TestraySubtaskLocalService
			testraySubtaskLocalService) {

		this.testraySubtaskLocalService = testraySubtaskLocalService;
	}

	/**
	 * Returns the testray subtask persistence.
	 *
	 * @return the testray subtask persistence
	 */
	public TestraySubtaskPersistence getTestraySubtaskPersistence() {
		return testraySubtaskPersistence;
	}

	/**
	 * Sets the testray subtask persistence.
	 *
	 * @param testraySubtaskPersistence the testray subtask persistence
	 */
	public void setTestraySubtaskPersistence(
		TestraySubtaskPersistence testraySubtaskPersistence) {

		this.testraySubtaskPersistence = testraySubtaskPersistence;
	}

	/**
	 * Returns the testray suite local service.
	 *
	 * @return the testray suite local service
	 */
	public com.liferay.osb.testray.service.TestraySuiteLocalService
		getTestraySuiteLocalService() {

		return testraySuiteLocalService;
	}

	/**
	 * Sets the testray suite local service.
	 *
	 * @param testraySuiteLocalService the testray suite local service
	 */
	public void setTestraySuiteLocalService(
		com.liferay.osb.testray.service.TestraySuiteLocalService
			testraySuiteLocalService) {

		this.testraySuiteLocalService = testraySuiteLocalService;
	}

	/**
	 * Returns the testray suite persistence.
	 *
	 * @return the testray suite persistence
	 */
	public TestraySuitePersistence getTestraySuitePersistence() {
		return testraySuitePersistence;
	}

	/**
	 * Sets the testray suite persistence.
	 *
	 * @param testraySuitePersistence the testray suite persistence
	 */
	public void setTestraySuitePersistence(
		TestraySuitePersistence testraySuitePersistence) {

		this.testraySuitePersistence = testraySuitePersistence;
	}

	/**
	 * Returns the testray task local service.
	 *
	 * @return the testray task local service
	 */
	public com.liferay.osb.testray.service.TestrayTaskLocalService
		getTestrayTaskLocalService() {

		return testrayTaskLocalService;
	}

	/**
	 * Sets the testray task local service.
	 *
	 * @param testrayTaskLocalService the testray task local service
	 */
	public void setTestrayTaskLocalService(
		com.liferay.osb.testray.service.TestrayTaskLocalService
			testrayTaskLocalService) {

		this.testrayTaskLocalService = testrayTaskLocalService;
	}

	/**
	 * Returns the testray task persistence.
	 *
	 * @return the testray task persistence
	 */
	public TestrayTaskPersistence getTestrayTaskPersistence() {
		return testrayTaskPersistence;
	}

	/**
	 * Sets the testray task persistence.
	 *
	 * @param testrayTaskPersistence the testray task persistence
	 */
	public void setTestrayTaskPersistence(
		TestrayTaskPersistence testrayTaskPersistence) {

		this.testrayTaskPersistence = testrayTaskPersistence;
	}

	/**
	 * Returns the testray team local service.
	 *
	 * @return the testray team local service
	 */
	public com.liferay.osb.testray.service.TestrayTeamLocalService
		getTestrayTeamLocalService() {

		return testrayTeamLocalService;
	}

	/**
	 * Sets the testray team local service.
	 *
	 * @param testrayTeamLocalService the testray team local service
	 */
	public void setTestrayTeamLocalService(
		com.liferay.osb.testray.service.TestrayTeamLocalService
			testrayTeamLocalService) {

		this.testrayTeamLocalService = testrayTeamLocalService;
	}

	/**
	 * Returns the testray team persistence.
	 *
	 * @return the testray team persistence
	 */
	public TestrayTeamPersistence getTestrayTeamPersistence() {
		return testrayTeamPersistence;
	}

	/**
	 * Sets the testray team persistence.
	 *
	 * @param testrayTeamPersistence the testray team persistence
	 */
	public void setTestrayTeamPersistence(
		TestrayTeamPersistence testrayTeamPersistence) {

		this.testrayTeamPersistence = testrayTeamPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.osb.testray.model.TestrayRun", testrayRunLocalService);

		TestrayRunLocalServiceUtil.setService(testrayRunLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.osb.testray.model.TestrayRun");

		TestrayRunLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TestrayRunLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return TestrayRun.class;
	}

	protected String getModelClassName() {
		return TestrayRun.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = testrayRunPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayArchiveLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayArchiveLocalService
		testrayArchiveLocalService;

	@BeanReference(type = TestrayArchivePersistence.class)
	protected TestrayArchivePersistence testrayArchivePersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayAssignmentLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayAssignmentLocalService
		testrayAssignmentLocalService;

	@BeanReference(type = TestrayAssignmentPersistence.class)
	protected TestrayAssignmentPersistence testrayAssignmentPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayBuildLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayBuildLocalService
		testrayBuildLocalService;

	@BeanReference(type = TestrayBuildPersistence.class)
	protected TestrayBuildPersistence testrayBuildPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayCaseLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayCaseLocalService
		testrayCaseLocalService;

	@BeanReference(type = TestrayCasePersistence.class)
	protected TestrayCasePersistence testrayCasePersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayCaseResultLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayCaseResultLocalService
		testrayCaseResultLocalService;

	@BeanReference(type = TestrayCaseResultPersistence.class)
	protected TestrayCaseResultPersistence testrayCaseResultPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayCaseResultWarningLocalService.class
	)
	protected
		com.liferay.osb.testray.service.TestrayCaseResultWarningLocalService
			testrayCaseResultWarningLocalService;

	@BeanReference(type = TestrayCaseResultWarningPersistence.class)
	protected TestrayCaseResultWarningPersistence
		testrayCaseResultWarningPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayCaseTypeLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayCaseTypeLocalService
		testrayCaseTypeLocalService;

	@BeanReference(type = TestrayCaseTypePersistence.class)
	protected TestrayCaseTypePersistence testrayCaseTypePersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayComponentLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayComponentLocalService
		testrayComponentLocalService;

	@BeanReference(type = TestrayComponentPersistence.class)
	protected TestrayComponentPersistence testrayComponentPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayFactorLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayFactorLocalService
		testrayFactorLocalService;

	@BeanReference(type = TestrayFactorPersistence.class)
	protected TestrayFactorPersistence testrayFactorPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayFactorCategoryLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayFactorCategoryLocalService
		testrayFactorCategoryLocalService;

	@BeanReference(type = TestrayFactorCategoryPersistence.class)
	protected TestrayFactorCategoryPersistence testrayFactorCategoryPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayFactorOptionLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayFactorOptionLocalService
		testrayFactorOptionLocalService;

	@BeanReference(type = TestrayFactorOptionPersistence.class)
	protected TestrayFactorOptionPersistence testrayFactorOptionPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayIssueLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayIssueLocalService
		testrayIssueLocalService;

	@BeanReference(type = TestrayIssuePersistence.class)
	protected TestrayIssuePersistence testrayIssuePersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayProductVersionLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayProductVersionLocalService
		testrayProductVersionLocalService;

	@BeanReference(type = TestrayProductVersionPersistence.class)
	protected TestrayProductVersionPersistence testrayProductVersionPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayProjectLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayProjectLocalService
		testrayProjectLocalService;

	@BeanReference(type = TestrayProjectPersistence.class)
	protected TestrayProjectPersistence testrayProjectPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayRequirementLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayRequirementLocalService
		testrayRequirementLocalService;

	@BeanReference(type = TestrayRequirementPersistence.class)
	protected TestrayRequirementPersistence testrayRequirementPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayRoutineLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayRoutineLocalService
		testrayRoutineLocalService;

	@BeanReference(type = TestrayRoutinePersistence.class)
	protected TestrayRoutinePersistence testrayRoutinePersistence;

	@BeanReference(type = TestrayRunLocalService.class)
	protected TestrayRunLocalService testrayRunLocalService;

	@BeanReference(type = TestrayRunPersistence.class)
	protected TestrayRunPersistence testrayRunPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestraySubtaskLocalService.class
	)
	protected com.liferay.osb.testray.service.TestraySubtaskLocalService
		testraySubtaskLocalService;

	@BeanReference(type = TestraySubtaskPersistence.class)
	protected TestraySubtaskPersistence testraySubtaskPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestraySuiteLocalService.class
	)
	protected com.liferay.osb.testray.service.TestraySuiteLocalService
		testraySuiteLocalService;

	@BeanReference(type = TestraySuitePersistence.class)
	protected TestraySuitePersistence testraySuitePersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayTaskLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayTaskLocalService
		testrayTaskLocalService;

	@BeanReference(type = TestrayTaskPersistence.class)
	protected TestrayTaskPersistence testrayTaskPersistence;

	@BeanReference(
		type = com.liferay.osb.testray.service.TestrayTeamLocalService.class
	)
	protected com.liferay.osb.testray.service.TestrayTeamLocalService
		testrayTeamLocalService;

	@BeanReference(type = TestrayTeamPersistence.class)
	protected TestrayTeamPersistence testrayTeamPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		TestrayRunLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}