/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.reading.time.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.reading.time.model.ReadingTimeEntry;
import com.liferay.reading.time.service.ReadingTimeEntryService;
import com.liferay.reading.time.service.ReadingTimeEntryServiceUtil;
import com.liferay.reading.time.service.persistence.ReadingTimeEntryPersistence;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the reading time entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.reading.time.service.impl.ReadingTimeEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.reading.time.service.impl.ReadingTimeEntryServiceImpl
 * @generated
 */
public abstract class ReadingTimeEntryServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, ReadingTimeEntryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ReadingTimeEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ReadingTimeEntryServiceUtil</code>.
	 */

	/**
	 * Returns the reading time entry local service.
	 *
	 * @return the reading time entry local service
	 */
	public com.liferay.reading.time.service.ReadingTimeEntryLocalService
		getReadingTimeEntryLocalService() {

		return readingTimeEntryLocalService;
	}

	/**
	 * Sets the reading time entry local service.
	 *
	 * @param readingTimeEntryLocalService the reading time entry local service
	 */
	public void setReadingTimeEntryLocalService(
		com.liferay.reading.time.service.ReadingTimeEntryLocalService
			readingTimeEntryLocalService) {

		this.readingTimeEntryLocalService = readingTimeEntryLocalService;
	}

	/**
	 * Returns the reading time entry remote service.
	 *
	 * @return the reading time entry remote service
	 */
	public ReadingTimeEntryService getReadingTimeEntryService() {
		return readingTimeEntryService;
	}

	/**
	 * Sets the reading time entry remote service.
	 *
	 * @param readingTimeEntryService the reading time entry remote service
	 */
	public void setReadingTimeEntryService(
		ReadingTimeEntryService readingTimeEntryService) {

		this.readingTimeEntryService = readingTimeEntryService;
	}

	/**
	 * Returns the reading time entry persistence.
	 *
	 * @return the reading time entry persistence
	 */
	public ReadingTimeEntryPersistence getReadingTimeEntryPersistence() {
		return readingTimeEntryPersistence;
	}

	/**
	 * Sets the reading time entry persistence.
	 *
	 * @param readingTimeEntryPersistence the reading time entry persistence
	 */
	public void setReadingTimeEntryPersistence(
		ReadingTimeEntryPersistence readingTimeEntryPersistence) {

		this.readingTimeEntryPersistence = readingTimeEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		ReadingTimeEntryServiceUtil.setService(readingTimeEntryService);
	}

	public void destroy() {
		ReadingTimeEntryServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ReadingTimeEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ReadingTimeEntry.class;
	}

	protected String getModelClassName() {
		return ReadingTimeEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = readingTimeEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.reading.time.service.ReadingTimeEntryLocalService.class
	)
	protected com.liferay.reading.time.service.ReadingTimeEntryLocalService
		readingTimeEntryLocalService;

	@BeanReference(type = ReadingTimeEntryService.class)
	protected ReadingTimeEntryService readingTimeEntryService;

	@BeanReference(type = ReadingTimeEntryPersistence.class)
	protected ReadingTimeEntryPersistence readingTimeEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ReadingTimeEntryServiceBaseImpl.class);

}