dependencies {
	testIntegrationImplementation group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
}