/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.loop.asset.entry.set.service.base;

import com.liferay.osb.loop.asset.entry.set.model.AssetEntrySetLike;
import com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLikeLocalService;
import com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLikeLocalServiceUtil;
import com.liferay.osb.loop.asset.entry.set.service.persistence.AssetEntrySetFinder;
import com.liferay.osb.loop.asset.entry.set.service.persistence.AssetEntrySetLikeFinder;
import com.liferay.osb.loop.asset.entry.set.service.persistence.AssetEntrySetLikePK;
import com.liferay.osb.loop.asset.entry.set.service.persistence.AssetEntrySetLikePersistence;
import com.liferay.osb.loop.asset.entry.set.service.persistence.AssetEntrySetPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset entry set like local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.loop.asset.entry.set.service.impl.AssetEntrySetLikeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.loop.asset.entry.set.service.impl.AssetEntrySetLikeLocalServiceImpl
 * @generated
 */
public abstract class AssetEntrySetLikeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AssetEntrySetLikeLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetEntrySetLikeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AssetEntrySetLikeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the asset entry set like to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetEntrySetLikeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetEntrySetLike the asset entry set like
	 * @return the asset entry set like that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntrySetLike addAssetEntrySetLike(
		AssetEntrySetLike assetEntrySetLike) {

		assetEntrySetLike.setNew(true);

		return assetEntrySetLikePersistence.update(assetEntrySetLike);
	}

	/**
	 * Creates a new asset entry set like with the primary key. Does not add the asset entry set like to the database.
	 *
	 * @param assetEntrySetLikePK the primary key for the new asset entry set like
	 * @return the new asset entry set like
	 */
	@Override
	@Transactional(enabled = false)
	public AssetEntrySetLike createAssetEntrySetLike(
		AssetEntrySetLikePK assetEntrySetLikePK) {

		return assetEntrySetLikePersistence.create(assetEntrySetLikePK);
	}

	/**
	 * Deletes the asset entry set like with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetEntrySetLikeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetEntrySetLikePK the primary key of the asset entry set like
	 * @return the asset entry set like that was removed
	 * @throws PortalException if a asset entry set like with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntrySetLike deleteAssetEntrySetLike(
			AssetEntrySetLikePK assetEntrySetLikePK)
		throws PortalException {

		return assetEntrySetLikePersistence.remove(assetEntrySetLikePK);
	}

	/**
	 * Deletes the asset entry set like from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetEntrySetLikeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetEntrySetLike the asset entry set like
	 * @return the asset entry set like that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntrySetLike deleteAssetEntrySetLike(
		AssetEntrySetLike assetEntrySetLike) {

		return assetEntrySetLikePersistence.remove(assetEntrySetLike);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AssetEntrySetLike.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetEntrySetLikePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return assetEntrySetLikePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return assetEntrySetLikePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetEntrySetLikePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return assetEntrySetLikePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AssetEntrySetLike fetchAssetEntrySetLike(
		AssetEntrySetLikePK assetEntrySetLikePK) {

		return assetEntrySetLikePersistence.fetchByPrimaryKey(
			assetEntrySetLikePK);
	}

	/**
	 * Returns the asset entry set like with the primary key.
	 *
	 * @param assetEntrySetLikePK the primary key of the asset entry set like
	 * @return the asset entry set like
	 * @throws PortalException if a asset entry set like with the primary key could not be found
	 */
	@Override
	public AssetEntrySetLike getAssetEntrySetLike(
			AssetEntrySetLikePK assetEntrySetLikePK)
		throws PortalException {

		return assetEntrySetLikePersistence.findByPrimaryKey(
			assetEntrySetLikePK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			assetEntrySetLikeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntrySetLike.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.assetEntrySetId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			assetEntrySetLikeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AssetEntrySetLike.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.assetEntrySetId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			assetEntrySetLikeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntrySetLike.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.assetEntrySetId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return assetEntrySetLikeLocalService.deleteAssetEntrySetLike(
			(AssetEntrySetLike)persistedModel);
	}

	public BasePersistence<AssetEntrySetLike> getBasePersistence() {
		return assetEntrySetLikePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetEntrySetLikePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the asset entry set likes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset entry set likes
	 * @param end the upper bound of the range of asset entry set likes (not inclusive)
	 * @return the range of asset entry set likes
	 */
	@Override
	public List<AssetEntrySetLike> getAssetEntrySetLikes(int start, int end) {
		return assetEntrySetLikePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset entry set likes.
	 *
	 * @return the number of asset entry set likes
	 */
	@Override
	public int getAssetEntrySetLikesCount() {
		return assetEntrySetLikePersistence.countAll();
	}

	/**
	 * Updates the asset entry set like in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetEntrySetLikeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetEntrySetLike the asset entry set like
	 * @return the asset entry set like that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntrySetLike updateAssetEntrySetLike(
		AssetEntrySetLike assetEntrySetLike) {

		return assetEntrySetLikePersistence.update(assetEntrySetLike);
	}

	/**
	 * Returns the asset entry set local service.
	 *
	 * @return the asset entry set local service
	 */
	public
		com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLocalService
			getAssetEntrySetLocalService() {

		return assetEntrySetLocalService;
	}

	/**
	 * Sets the asset entry set local service.
	 *
	 * @param assetEntrySetLocalService the asset entry set local service
	 */
	public void setAssetEntrySetLocalService(
		com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLocalService
			assetEntrySetLocalService) {

		this.assetEntrySetLocalService = assetEntrySetLocalService;
	}

	/**
	 * Returns the asset entry set persistence.
	 *
	 * @return the asset entry set persistence
	 */
	public AssetEntrySetPersistence getAssetEntrySetPersistence() {
		return assetEntrySetPersistence;
	}

	/**
	 * Sets the asset entry set persistence.
	 *
	 * @param assetEntrySetPersistence the asset entry set persistence
	 */
	public void setAssetEntrySetPersistence(
		AssetEntrySetPersistence assetEntrySetPersistence) {

		this.assetEntrySetPersistence = assetEntrySetPersistence;
	}

	/**
	 * Returns the asset entry set finder.
	 *
	 * @return the asset entry set finder
	 */
	public AssetEntrySetFinder getAssetEntrySetFinder() {
		return assetEntrySetFinder;
	}

	/**
	 * Sets the asset entry set finder.
	 *
	 * @param assetEntrySetFinder the asset entry set finder
	 */
	public void setAssetEntrySetFinder(
		AssetEntrySetFinder assetEntrySetFinder) {

		this.assetEntrySetFinder = assetEntrySetFinder;
	}

	/**
	 * Returns the asset entry set like local service.
	 *
	 * @return the asset entry set like local service
	 */
	public AssetEntrySetLikeLocalService getAssetEntrySetLikeLocalService() {
		return assetEntrySetLikeLocalService;
	}

	/**
	 * Sets the asset entry set like local service.
	 *
	 * @param assetEntrySetLikeLocalService the asset entry set like local service
	 */
	public void setAssetEntrySetLikeLocalService(
		AssetEntrySetLikeLocalService assetEntrySetLikeLocalService) {

		this.assetEntrySetLikeLocalService = assetEntrySetLikeLocalService;
	}

	/**
	 * Returns the asset entry set like persistence.
	 *
	 * @return the asset entry set like persistence
	 */
	public AssetEntrySetLikePersistence getAssetEntrySetLikePersistence() {
		return assetEntrySetLikePersistence;
	}

	/**
	 * Sets the asset entry set like persistence.
	 *
	 * @param assetEntrySetLikePersistence the asset entry set like persistence
	 */
	public void setAssetEntrySetLikePersistence(
		AssetEntrySetLikePersistence assetEntrySetLikePersistence) {

		this.assetEntrySetLikePersistence = assetEntrySetLikePersistence;
	}

	/**
	 * Returns the asset entry set like finder.
	 *
	 * @return the asset entry set like finder
	 */
	public AssetEntrySetLikeFinder getAssetEntrySetLikeFinder() {
		return assetEntrySetLikeFinder;
	}

	/**
	 * Sets the asset entry set like finder.
	 *
	 * @param assetEntrySetLikeFinder the asset entry set like finder
	 */
	public void setAssetEntrySetLikeFinder(
		AssetEntrySetLikeFinder assetEntrySetLikeFinder) {

		this.assetEntrySetLikeFinder = assetEntrySetLikeFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.osb.loop.asset.entry.set.model.AssetEntrySetLike",
			assetEntrySetLikeLocalService);

		AssetEntrySetLikeLocalServiceUtil.setService(
			assetEntrySetLikeLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.osb.loop.asset.entry.set.model.AssetEntrySetLike");

		AssetEntrySetLikeLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetEntrySetLikeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetEntrySetLike.class;
	}

	protected String getModelClassName() {
		return AssetEntrySetLike.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = assetEntrySetLikePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLocalService.class
	)
	protected
		com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLocalService
			assetEntrySetLocalService;

	@BeanReference(type = AssetEntrySetPersistence.class)
	protected AssetEntrySetPersistence assetEntrySetPersistence;

	@BeanReference(type = AssetEntrySetFinder.class)
	protected AssetEntrySetFinder assetEntrySetFinder;

	@BeanReference(type = AssetEntrySetLikeLocalService.class)
	protected AssetEntrySetLikeLocalService assetEntrySetLikeLocalService;

	@BeanReference(type = AssetEntrySetLikePersistence.class)
	protected AssetEntrySetLikePersistence assetEntrySetLikePersistence;

	@BeanReference(type = AssetEntrySetLikeFinder.class)
	protected AssetEntrySetLikeFinder assetEntrySetLikeFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetEntrySetLikeLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}