/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.koroneiki.taproot.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.koroneiki.taproot.model.AccountField;
import com.liferay.osb.koroneiki.taproot.model.AccountFieldModel;
import com.liferay.osb.koroneiki.taproot.model.AccountFieldSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AccountField service. Represents a row in the &quot;Koroneiki_AccountField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AccountFieldModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountFieldImpl
 * @generated
 */
@JSON(strict = true)
public class AccountFieldModelImpl
	extends BaseModelImpl<AccountField> implements AccountFieldModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account field model instance should use the <code>AccountField</code> interface instead.
	 */
	public static final String TABLE_NAME = "Koroneiki_AccountField";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"accountFieldId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"accountId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accountFieldId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("accountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Koroneiki_AccountField (mvccVersion LONG default 0 not null,accountFieldId LONG not null primary key,companyId LONG,userId LONG,accountId LONG,name VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Koroneiki_AccountField";

	public static final String ORDER_BY_JPQL =
		" ORDER BY accountField.accountFieldId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Koroneiki_AccountField.accountFieldId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ACCOUNTID_COLUMN_BITMASK = 1L;

	public static final long ACCOUNTFIELDID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AccountField toModel(AccountFieldSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AccountField model = new AccountFieldImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setAccountFieldId(soapModel.getAccountFieldId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setAccountId(soapModel.getAccountId());
		model.setName(soapModel.getName());
		model.setValue(soapModel.getValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AccountField> toModels(AccountFieldSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AccountField> models = new ArrayList<AccountField>(
			soapModels.length);

		for (AccountFieldSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AccountFieldModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _accountFieldId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAccountFieldId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _accountFieldId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AccountField.class;
	}

	@Override
	public String getModelClassName() {
		return AccountField.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AccountField, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AccountField, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountField, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AccountField)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AccountField, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AccountField, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AccountField)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AccountField, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AccountField, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AccountField, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<AccountField, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AccountField, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", AccountField::getMvccVersion);
		attributeGetterFunctions.put(
			"accountFieldId", AccountField::getAccountFieldId);
		attributeGetterFunctions.put("companyId", AccountField::getCompanyId);
		attributeGetterFunctions.put("userId", AccountField::getUserId);
		attributeGetterFunctions.put("accountId", AccountField::getAccountId);
		attributeGetterFunctions.put("name", AccountField::getName);
		attributeGetterFunctions.put("value", AccountField::getValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<AccountField, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<AccountField, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AccountField, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<AccountField, Long>)AccountField::setMvccVersion);
		attributeSetterBiConsumers.put(
			"accountFieldId",
			(BiConsumer<AccountField, Long>)AccountField::setAccountFieldId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AccountField, Long>)AccountField::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<AccountField, Long>)AccountField::setUserId);
		attributeSetterBiConsumers.put(
			"accountId",
			(BiConsumer<AccountField, Long>)AccountField::setAccountId);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<AccountField, String>)AccountField::setName);
		attributeSetterBiConsumers.put(
			"value", (BiConsumer<AccountField, String>)AccountField::setValue);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getAccountFieldId() {
		return _accountFieldId;
	}

	@Override
	public void setAccountFieldId(long accountFieldId) {
		_accountFieldId = accountFieldId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getAccountId() {
		return _accountId;
	}

	@Override
	public void setAccountId(long accountId) {
		_columnBitmask |= ACCOUNTID_COLUMN_BITMASK;

		if (!_setOriginalAccountId) {
			_setOriginalAccountId = true;

			_originalAccountId = _accountId;
		}

		_accountId = accountId;
	}

	public long getOriginalAccountId() {
		return _originalAccountId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AccountField.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AccountField toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AccountField>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AccountFieldImpl accountFieldImpl = new AccountFieldImpl();

		accountFieldImpl.setMvccVersion(getMvccVersion());
		accountFieldImpl.setAccountFieldId(getAccountFieldId());
		accountFieldImpl.setCompanyId(getCompanyId());
		accountFieldImpl.setUserId(getUserId());
		accountFieldImpl.setAccountId(getAccountId());
		accountFieldImpl.setName(getName());
		accountFieldImpl.setValue(getValue());

		accountFieldImpl.resetOriginalValues();

		return accountFieldImpl;
	}

	@Override
	public int compareTo(AccountField accountField) {
		long primaryKey = accountField.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AccountField)) {
			return false;
		}

		AccountField accountField = (AccountField)object;

		long primaryKey = accountField.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalAccountId = _accountId;

		_setOriginalAccountId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AccountField> toCacheModel() {
		AccountFieldCacheModel accountFieldCacheModel =
			new AccountFieldCacheModel();

		accountFieldCacheModel.mvccVersion = getMvccVersion();

		accountFieldCacheModel.accountFieldId = getAccountFieldId();

		accountFieldCacheModel.companyId = getCompanyId();

		accountFieldCacheModel.userId = getUserId();

		accountFieldCacheModel.accountId = getAccountId();

		accountFieldCacheModel.name = getName();

		String name = accountFieldCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			accountFieldCacheModel.name = null;
		}

		accountFieldCacheModel.value = getValue();

		String value = accountFieldCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			accountFieldCacheModel.value = null;
		}

		return accountFieldCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AccountField, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AccountField, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountField, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AccountField)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AccountField, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AccountField, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountField, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AccountField)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AccountField>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AccountField.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private long _accountFieldId;
	private long _companyId;
	private long _userId;
	private long _accountId;
	private long _originalAccountId;
	private boolean _setOriginalAccountId;
	private String _name;
	private String _value;
	private long _columnBitmask;
	private AccountField _escapedModel;

}