dependencies {
	compileOnly project(":core:petra:petra-function")
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation project(":apps:comment:comment-page-comments-web")
	testIntegrationImplementation project(":apps:export-import:export-import-test-util")
	testIntegrationImplementation project(":apps:message-boards:message-boards-api")
}