enum AcquisitionType {
	CHANNEL
	REFERRER
	SOURCE_MEDIUM
}

enum AnalysisType {
	AVERAGE
	TOTAL
	UNIQUE
}

enum AssetType {
	BLOG
	DOCUMENT
	FORM
	JOURNAL
	PAGE
}

enum AttributeType {
	EVENT,
	INDIVIDUAL,
	USER_SESSION
}

enum DataControlTaskStatus {
	COMPLETED
	ERROR
	EXPIRED
	PENDING
	RUNNING
}

enum DataControlTaskType {
	ACCESS
	DELETE
	SUPPRESS
	UNSUPPRESS
}

enum DataSourceConfigurationStatus {
	CONFIGURED
	UNCONFIGURED
}

enum DateGrouping {
	DAY
	MONTH
	YEAR
}

enum EntityType {
	INDIVIDUAL
}

enum EventAttributeDefinitionDataType {
	BOOLEAN
	DATE
	DURATION
	NUMBER
	STRING
}

enum EventAttributeDefinitionType {
	ALL
	GLOBAL
	LOCAL
}

enum EventDefinitionType {
	ALL
	CUSTOM
	DEFAULT
}

enum JobRunStatus {
	COMPLETED
	FAILED
	PUBLISHED
	RUNNING
}

enum JobRunDataPeriod {
	LAST_7_DAYS
	LAST_30_DAYS
	LAST_180_DAYS
	LAST_365_DAYS
}

enum JobRunFrequency {
	EVERY_7_DAYS
	EVERY_14_DAYS
	EVERY_30_DAYS
	MANUAL
}

enum JobStatus {
	FAILED
	PENDING
	READY
	RUNNING
	SCHEDULED
}

enum JobType {
	COMMERCE_DEMAND_FORECAST_PRODUCT
	COMMERCE_PRODUCT_RECOMMENDATION_FREQUENT_PATTERN
	COMMERCE_PRODUCT_RECOMMENDATION_PRODUCT_CONTENT
	COMMERCE_PRODUCT_RECOMMENDATION_USER_INTERACTION
	COMMERCE_REVENUE_FORECAST_ACCOUNT
	COMMERCE_REVENUE_FORECAST_ACCOUNT_CATEGORY
	CONTENT_RECOMMENDATION_ITEM_SIMILARITY
}

enum SortType {
	ASC
	DESC
}

input DXPVariantSettings {
	control: Boolean!
	dxpVariantId: String!
	trafficSplit: Float!
}

input EventAnalysisBreakdownInput {
	attributeId: String!
	attributeType: AttributeType!
	binSize: Float
	dataType: EventAttributeDefinitionDataType!
	dateGrouping: DateGrouping
	description: String
	displayName: String!
	sortType: SortType
}

input EventAnalysisFilterInput {
	attributeId: String!
	attributeType: AttributeType!
	dataType: EventAttributeDefinitionDataType!
	description: String
	displayName: String!
	operator: String!
	values: [String]!
}

input ExperimentSettings {
	confidenceLevel: Float!
	dxpVariantsSettings: [DXPVariantSettings]!
}

input JobParameterInput {
	name: String!
	value: String!
}

input PropertyFilter {
	negate: Boolean!
	filter: String!
}

input Sort {
	column: String!
	type: SortType!
}

interface AssetMetric {
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	dataSourceId: String
	defaultMetric: Metric
	urls: [String]
}

schema {
	query: QueryType
	mutation: MutationType
}

type Activity {
	applicationId: String
	eventContext: String
	eventId: String
	eventProperties: String
	ownerId: String
	startTime: String
}

type ActivityBag {
	activities: [Activity]
	total: Int
}

type AssetMetricBag {
	assetMetrics: [AssetMetric]
	total: Int
}

type AudienceReport {
    anonymousUsersCount: Int
    knownUsersCount: Int
    nonsegmentedKnownUsersCount: Int
    segmentedAnonymousUsersCount: Int
    segmentedKnownUsersCount: Int
}

type BaseDXPEntity implements DXPEntity {
	dataSourceName: String
	id: String
	name: String
}

type BlockedCustomEventDefinition {
	hidden: Boolean
	id: String
	lastSeenDate: String
	lastSeenURL: String
	name: String
}

type BlockedCustomEventDefinitionBag {
	blockedCustomEventDefinitions: [BlockedCustomEventDefinition]
	total: Int
}

type BlogMetric implements AssetMetric {
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	canonicalUrls: [String]
	commentsMetric: Metric
	dataSourceId: String
	defaultMetric: Metric
	ratingsMetric: Metric
	readingTimeMetric: Metric
	urls: [String]
	viewsMetric: Metric
}

type BreakdownItem {
	breakdownItems: [BreakdownItem]
	leafNode: Boolean
	name: String
	previousValue: Float
	value: Float
}

type CohortHeatMapMetric {
	colDimension: String
	retention: Float
	rowDimension: String
	rowKey: String
	value: Float
}

type CohortMetric {
	anonymousCohortHeatMapMetrics: [CohortHeatMapMetric]
	knownCohortHeatMapMetrics: [CohortHeatMapMetric]
	visitorsCohortHeatMapMetrics: [CohortHeatMapMetric]
}

type Composition {
	name: String
	count: Int
}

type CompositionBag {
	compositions: [Composition]
	maxCount: Int
	total: Int
	totalCount: Int
}

type CurrencyValue {
	currencyCode: String,
	trend: Trend,
	value: String
}

type CustomAssetMetric implements AssetMetric {
	abandonmentsMetric: Metric
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	canonicalUrls: [String]
	clicksMetric: Metric
	completionTimeMetric: Metric
	dataSourceId: String
	defaultMetric: Metric
	downloadsMetric: Metric
	readingTimeMetric: Metric
	submissionsMetric: Metric
	urls: [String]
	viewsMetric: Metric
}

type Dashboard {
	assetId: String
	assetTitle: String
	category: String
	createDate: String
	definition: String
	id: String
	modifiedByUserName: String
	modifiedDate: String
}

type DashboardBag {
	dashboards: [Dashboard]
	total: Int
}

type DataControlTask {
	batchId: String
	completeDate: String
	createDate: String
	emailAddress: String
	id: String
	ownerId: String
	startDate: String
	status: String
	type: String
}

type DataControlTaskBag {
	dataControlTasks: [DataControlTask]
	total: Int
}

type DataSource {
	contactsSyncDetails: DataSourceSyncDetail
	id: String
	name: String
	sitesSyncDetails: DataSourceSyncDetail
	url: String
}

type DataSourceSyncDetail {
	count: Int
	lastSyncDate: String
	selected: Boolean
}

type DocumentMetric implements AssetMetric {
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	canonicalUrls: [String]
	commentsMetric: Metric
	dataSourceId: String
	defaultMetric: Metric
	downloadsMetric: Metric
	previewsMetric: Metric
	ratingsMetric: Metric
	urls: [String]
}

interface DXPEntity {
	dataSourceName: String
	id: String
	name: String
}

type DXPEntityBag {
	dxpEntities: [DXPEntity]
	total: Int
}

type Event {
	canonicalUrl: String,
	createDate: String,
	name: String,
	pageDescription: String,
	pageKeywords: String,
	pageTitle: String,
	referrer: String,
	url: String
}

type EventAnalysis {
	analysisType: AnalysisType
	channelId: String
	compareToPrevious: Boolean
	createDate: String
	createdByUserId: String
	createdByUserName: String
	eventAnalysisBreakdowns: [EventAnalysisBreakdown]
	eventAnalysisFilters: [EventAnalysisFilter]
	eventDefinitionId: String
	id: String
	modifiedDate: String
	modifiedByUserId: String
	modifiedByUserName: String
	name: String
	rangeEnd: String
	rangeKey: Int
	rangeStart: String
	referencedObjects: EventAnalysisReferencedObject
}

type EventAnalysisBag {
	eventAnalyses: [EventAnalysis]
	total: Int
}

type EventAnalysisBreakdown {
	attributeId: String
	attributeType: String
	binSize: Float
	dataType: String
	dateGrouping: String
	description: String
	displayName: String
	sortType: String
}

type EventAnalysisFilter {
	attributeId: String
	attributeType: String
	dataType: String
	description: String
	displayName: String
	operator: String
	values: [String]
}

type EventAnalysisReferencedObject {
	eventAttributeDefinitions: [EventAttributeDefinition]
	eventDefinition: EventDefinition
}

type EventAnalysisResult {
	breakdownItems: [BreakdownItem]
	count: Int
	page: Int
	previousValue: Float
	value: Float
}

type EventAttributeDefinition {
	dataType: EventAttributeDefinitionDataType
	description: String
	displayName: String
	id: String
	name: String
	recentValues: [EventAttributeValue]
	sampleValue: String
	type: EventAttributeDefinitionType
}

type EventAttributeDefinitionBag {
	eventAttributeDefinitions: [EventAttributeDefinition]
	total: Int
}

type EventAttributeValue {
	lastSeenDate: String
	value: String
}

type EventAttributeValueBag {
	eventAttributeValues: [String]
	total: Int
}

type EventDefinition {
	description: String
	displayName: String
	eventAttributeDefinitions: [EventAttributeDefinition]
	id: String
	hidden: Boolean
	name: String
	type: EventDefinitionType
}

type EventDefinitionBag {
	eventDefinitions: [EventDefinition]
	total: Int
}

type EventMetric {
	totalEventsMetric: Metric
	totalSessionsMetric: Metric
}

type EventsByUserSession {
	userSessions: [UserSession],
	totalEvents: Int
}

type Experiment {
	channelId: String
	createDate: String
	dataSourceId: String
	description: String
	dxpExperienceName: String
	dxpSegmentName: String
	dxpVariants: [ExperimentVariant]
	finishedDate: String
	goal: Goal
	id: String
	metrics: ExperimentMetric
	metricsHistogram: [ExperimentMetric]
	modifiedDate: String
	name: String
	pageURL: String
	publishable: Boolean
	publishedDXPVariantId: String
	sessions: Int
	sessionsHistogram: [HistogramMetric]
	startedDate: String
	status: String
	type: String
	winnerDXPVariantId: String
}

type ExperimentBag {
	experiments: [Experiment]
	total: Int
}

type ExperimentMetric {
	completion: Float
	confidenceLevel: Float
	elapsedDays: Int
	estimatedDaysLeft: Int
	processedDate: String
	variantMetrics: [ExperimentVariantMetric]
}

type ExperimentVariant {
	changes: Int
	control: Boolean
	dxpVariantId: String
	dxpVariantName: String
	sessionsHistogram: [HistogramMetric]
	trafficSplit: Float
	uniqueVisitors: Int
}

type ExperimentVariantMetric {
	confidenceInterval: [Float]
	dxpVariantId: String
	improvement: Float
	median: Float
	probabilityToWin: Float
}

type FormFieldMetric {
	fieldAbandonmentsMetric: Metric
	fieldEmptyMetric: Metric
	fieldInteractionDurationMetric: Metric
	fieldInteractionsMetric: Metric
	fieldName: String
	fieldRefilledMetric: Metric
}

type FormMetric implements AssetMetric {
	abandonmentsMetric: Metric
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	canonicalUrls: [String]
	completionTimeMetric: Metric
	dataSourceId: String
	defaultMetric: Metric
	formPageMetrics: [FormPageMetric]
	submissionsMetric: Metric
	urls: [String]
	viewsMetric: Metric
}

type FormPageMetric {
	formFieldMetrics: [FormFieldMetric]
	pageAbandonmentsMetric: Metric
	pageIndex: String
	pageName: String
	pageViewsMetric: Metric
}

type Goal {
	metric: String
	target: String
}

type HeatMapMetric {
	colDimension: String
	rowDimension: String
	value: Float
}

type HistogramMetric {
	key: String
	previousValue: Float
	previousValueKey: String
	trend: Trend
	value: Float
	valueKey: String
}

type HistogramMetricBag {
	asymmetricComparison: Boolean
	metrics: [HistogramMetric]
	total: Int
}

type Individual {
	email: String
	id: String
	name: String
}

type IndividualBag {
	individuals: [Individual],
	total: Int
}

type IndividualMetric {
	anonymousIndividualsMetric: Metric
	knownIndividualsMetric: Metric
	totalIndividualsMetric: Metric
}

type KeyValuePair {
	key: String
	value: String
}

type Keyword {
	type: String
	value: String
}

type Job {
	id: String
	name: String
	nextRunDate: String
	parameters: [JobParameter]
	status: JobStatus
	runDate: String
	runFrequency: JobRunFrequency
	runDataPeriod: JobRunDataPeriod
	type: JobType
}

type JobBag {
	jobs: [Job]
	total: Int
}

type JobParameter {
	name: String
	value: String
}

type JobRun {
	id: String
	completedDate: String
	context: [KeyValuePair]
	status: JobRunStatus
}

type JobRunBag {
	jobRuns: [JobRun]
	total: Int
}

type JobRunsMonthlyStatistics {
	availableJobRuns: Int
	completedJobRuns: Int
	failedJobRuns: Int
	publishedJobRuns: Int
	runningJobRuns: Int
	scheduledJobRuns: Int
}

type JournalMetric implements AssetMetric {
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	canonicalUrls: [String]
	dataSourceId: String
	defaultMetric: Metric
	urls: [String]
	viewsMetric: Metric
}

type Metric {
	anonymousUsersCount: Int
	audienceReport: AudienceReport
	browser: [Metric]
	cohortHeatMap: [CohortHeatMapMetric]
	device: [Metric]
	geolocation: [Metric]
	histogram: HistogramMetricBag
	individuals(keywords: String, size: Int!, start: Int!): IndividualBag
	knownUsersCount: Int
	metrics: [Metric]
	nonsegmentedKnownUsersCount: Int
	previousValue: Float
	previousValueKey: String
	segment: MetricBag
	segmentedAnonymousUsersCount: Int
	segmentedKnownUsersCount: Int
	trend: Trend
	value: Float
	valueKey: String
}

type MetricBag {
	metrics: [Metric]
	total: Int
}

type MutationType {
	blockCustomEventDefinitions(
		eventDefinitionIds: [String]!
	): [Boolean]

	createEventAnalysis(
		analysisType: AnalysisType!
		channelId: String!
		compareToPrevious: Boolean!
		eventAnalysisBreakdowns: [EventAnalysisBreakdownInput]
		eventAnalysisFilters: [EventAnalysisFilterInput]
		eventDefinitionId: String!
		name: String!
		rangeEnd: String
		rangeKey: Int
		rangeStart: String
		userId: String!
		userName: String!
	): EventAnalysis

	createJob(
		name: String!
		parameters: [JobParameterInput]
		runDataPeriod: JobRunDataPeriod
		runFrequency: JobRunFrequency
		runNow: Boolean
		type: JobType!
	): Job

	dashboard(
		dashboardId: String!
		definition: String!
		modifiedByUserId: String!
		modifiedByUserName: String!
	): Dashboard

	dataControlTasks(
		emailAddresses: [String]
		fileName: String
		ownerId: String!
		types: [DataControlTaskType]!
		userId: String!
		userName: String!
	): Boolean

	deleteEventAnalyses(
		eventAnalysisIds: [String]!
	): [Boolean]

	deleteExperiment(
		experimentId: String!
	): Boolean

	deleteJobs(
		jobIds: [String]!
	): [Boolean]

	experiment(
		experimentId: String!
		experimentSettings: ExperimentSettings
		publishedDXPVariantId: String
		status: String
	): Experiment

	hideBlockedEventDefinitions(
		blockedEventDefinitionIds: [String]!
	): [BlockedCustomEventDefinition]

	hideEventDefinitions(
		eventDefinitionIds: [String]!
	): [EventDefinition]

	preference(
		key: String!
		value: String!
	): Preference

	runJob(
		jobId: String!,
		runDataPeriod: JobRunDataPeriod!
	): Job

	timeZone(
		value: String!
	): String

	unblockCustomEventDefinitions(
		eventDefinitionIds: [String]!
	): [Boolean]

	unhideBlockedEventDefinitions(
		blockedEventDefinitionIds: [String]!
	): [BlockedCustomEventDefinition]

	unhideEventDefinitions(
		eventDefinitionIds: [String]!
	): [EventDefinition]

	updateEventAnalysis(
		analysisType: AnalysisType!
		channelId: String!
		compareToPrevious: Boolean!
		eventAnalysisBreakdowns: [EventAnalysisBreakdownInput]
		eventAnalysisFilters: [EventAnalysisFilterInput]
		eventAnalysisId: String!
		eventDefinitionId: String!
		name: String!
		rangeEnd: String
		rangeKey: Int
		rangeStart: String
		userId: String!
		userName: String!
	): EventAnalysis

	updateEventAttributeDefinition(
		dataType: EventAttributeDefinitionDataType
		description: String
		displayName: String
		eventAttributeDefinitionId: String!
	): EventAttributeDefinition

	updateEventDefinition(
		description: String
		displayName: String
		eventDefinitionId: String!
	): EventDefinition

	updateJob(
		jobId: String!
		name: String!
		parameters: [JobParameterInput]
		runDataPeriod: JobRunDataPeriod
		runFrequency: JobRunFrequency
		runNow: Boolean
	): Job
}

type Organization implements DXPEntity {
	dataSourceName: String
	id: String
	name: String
	parentName: String
	type: String
}

type PageAsset {
	canonicalUrl: String
	description: String
	keywords: [Keyword]
	id: String
	title: String
	url: String
}

type PageAssetBag {
	pageAssets: [PageAsset]
	total: Int
}

type PageMetric implements AssetMetric {
	assetId: String
	assetMetrics: [AssetMetric]
	assetTitle: String
	assetType: String
	avgTimeOnPageMetric: Metric
	bounceRateMetric: Metric
	defaultMetric: Metric
	directAccessMetric: Metric
	dataSourceId: String
	entrancesMetric: Metric
	exitRateMetric: Metric
	indirectAccessMetric: Metric
	urls: [String]
	visitorsMetric: Metric
	viewsMetric: Metric
}

type PagePathNode {
	canonicalUrl: String
	external: Boolean
	followingPagePathNodes: [PagePathNode]
	previousPagePathNodes: [PagePathNode]
	title: String
	views: Int
}

type Preference {
	key: String
	value: String
}

type QueryType {
	acquisitions(
		acquisitionType: AcquisitionType!,
		channelId: String,
		dataSourceId: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		start: Int!
	): CompositionBag

	activities(
		applicationId: String!
		eventId: String!
		eventContextPropertyFilters: [PropertyFilter]
		rangeKey: Int!
		size: Int!
		start: Int!
	): ActivityBag

	activityEventContextKeys: [String]

	assetPages(
		assetId: String!,
		assetType: AssetType!,
		channelId: String,
		country: String,
		deviceType: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String
	): [AssetMetric]

	assets(
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		url: String
	): [AssetMetric]

	blockedCustomEventDefinitions(
		keyword: String,
		page: Int!,
		size: Int!,
		sort: Sort!
	): BlockedCustomEventDefinitionBag

	blog(
		assetId: String!,
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String,
		url: String
	): BlogMetric

	blogs(
		channelId: String,
		keywords: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): AssetMetricBag

	cohort(
		channelId: String,
		interval: String!
	): CohortMetric

	custom(
		assetId: String!,
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String,
		url: String
	): CustomAssetMetric

	customEventLimitReached: Boolean

	dashboard(
		dashboardId: String!
	): Dashboard

	dashboards(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DashboardBag

	dataControlTasks(
		batchId: String,
		keywords: String,
		rangeKey: Int,
		size: Int!,
		sort: Sort!,
		start: Int!,
		statuses: [DataControlTaskStatus],
		types: [DataControlTaskType]
	): DataControlTaskBag

	dataSource(
		dataSourceId: String!,
	): DataSource

	dataSources(
		credentialsType: String,
		size: Int,
		sort: Sort,
		type: String
	): [DataSource]

	document(
		assetId: String!,
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String,
		url: String
	): DocumentMetric

	documents(
		channelId: String,
		keywords: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): AssetMetricBag

	eventAnalyses(
		channelId: String!,
		keywords: String,
		page: Int!,
		size: Int!,
		sort: Sort!
	): EventAnalysisBag

	eventAnalysis(
		eventAnalysisId: String!
	): EventAnalysis

	eventAnalysisResult(
		analysisType: AnalysisType!,
		channelId: String!,
		compareToPrevious: Boolean!,
		eventAnalysisBreakdowns: [EventAnalysisBreakdownInput],
		eventAnalysisFilters: [EventAnalysisFilterInput],
		eventDefinitionId: String!,
		page: Int!,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!
	): EventAnalysisResult

	eventAttributeDefinition(
		displayName: String,
		id: String
	): EventAttributeDefinition

	eventAttributeDefinitions(
		eventDefinitionId: String,
		keyword: String,
		page: Int!,
		size: Int!,
		sort: Sort!,
		type: EventAttributeDefinitionType!
	): EventAttributeDefinitionBag

	eventAttributeValues(
		channelId: String!,
		eventAttributeDefinitionId: String!,
		eventDefinitionId: String!,
		keywords: String!,
		size: Int!,
		start: Int!
	): EventAttributeValueBag

	eventDefinition(
		displayName: String,
		id: String
	): EventDefinition

	eventDefinitions(
		eventType: EventDefinitionType!,
		hidden: Boolean,
		keyword: String,
		page: Int!,
		size: Int!,
		sort: Sort!
	): EventDefinitionBag
	
	eventMetric(
		channelId: String,
		entityId: String!,
		entityType: EntityType!,
		interval: String,
		keywords: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String
	): EventMetric

	experiment(
		experimentId: String!
	): Experiment

	experimentEstimatedDaysDuration(
		experimentId: String!
		experimentSettings: ExperimentSettings!
	): Int

	experiments(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): ExperimentBag

	form(
		assetId: String!,
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String,
		url: String
	): FormMetric

	forms(
		channelId: String,
		keywords: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): AssetMetricBag

	globalEventAttributeDefinitions: [EventAttributeDefinition]

	groups(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DXPEntityBag

	individualInterests(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!
		start: Int!
	): CompositionBag

	individualMetric(
		active: Boolean,
		channelId: String,
		interval: String,
		rangeKey: Int
	): IndividualMetric

	individualSegmentInterests(
		active: Boolean,
		channelId: String,
		individualSegmentId: String!,
		keywords: String,
		size: Int!,
		sort: Sort!
		start: Int!
	): CompositionBag

	jobById(
		id: String!
	): Job

	jobByName(
		name: String!
	): Job

	jobRuns(
		jobId: String!
		size: Int!,
		sort: Sort!,
		start: Int!
	): JobRunBag

	jobRunsMonthlyStatistics(
		jobId: String!
	): JobRunsMonthlyStatistics

	jobs(
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): JobBag

	journal(
		assetId: String!,
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String,
		url: String
	): JournalMetric

	journals(
		channelId: String,
		keywords: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): AssetMetricBag

	orderAccountAverageCurrencyValues(
		channelId: String!,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String
	): [CurrencyValue]

	orderAverageCurrencyValues(
		channelId: String!,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String
	): [CurrencyValue]

	orderIncompleteCurrencyValues(
		channelId: String!,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String
	): [CurrencyValue]

	orderTotalCurrencyValues(
		channelId: String!,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String
	): [CurrencyValue]

	organizations(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DXPEntityBag

	page(
		canonicalUrl: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		title: String,
		url: String
	): PageMetric

	pageAssets(
		keywords: String
		propertyFilters: [PropertyFilter]
		size: Int!
		sort: Sort!
		start: Int!
	): PageAssetBag

	pages(
		channelId: String,
		dataSourceId: String,
		experimentId: String,
		keywords: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		sort: Sort!,
		start: Int!,
		terms: String,
		variantId: String
	): AssetMetricBag

	pagesCount(
		fromDate: String,
		toDate: String
	): Int

	pagePath(
		canonicalUrl: String,
        channelId: String,
        rangeEnd: String,
        rangeKey: Int,
        rangeStart: String,
        segmentId: String,
        title: String!
	): PagePathNode

	preference(
		key: String!
	): Preference

	roles(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DXPEntityBag

	searchTerms(
		channelId: String,
		dataSourceId: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		start: Int!
	): CompositionBag

	site(
		assetId: String,
		channelId: String,
		country: String,
		deviceType: String,
		includePrevious: Boolean,
		interval: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		timeZoneId: String
	): SiteMetric

	siteInterests(
		channelId: String,
		dataSourceId: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		size: Int!,
		start: Int!
	): CompositionBag

	siteVisitorHeatMap(
		assetId: String,
		channelId: String,
		rangeEnd: String,
		rangeKey: Int,
		rangeStart: String,
		timeZoneId: String
	): [HeatMapMetric]

	suppressions(
		keywords: String,
		size: Int!,
		sort: Sort!
		start: Int!
	): SuppressionBag

	teams(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DXPEntityBag

	timeRange: [TimeRange]

	userGroups(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DXPEntityBag
	
	eventsByUserSessions(
		channelId: String!
		entityId: String!
		entityType: EntityType!
		keywords: String
		page: Int!
		rangeEnd: String
		rangeKey: Int
		rangeStart: String
		size: Int!
	): EventsByUserSession

	users(
		channelId: String,
		keywords: String,
		size: Int!,
		sort: Sort!,
		start: Int!
	): DXPEntityBag
}

type SiteMetric {
	anonymousVisitorsMetric: Metric
	assetMetrics: [AssetMetric]
	bounceRateMetric: Metric
	knownVisitorsMetric: Metric
	sessionDurationMetric: Metric
	sessionsMetric: Metric
	sessionsPerVisitorMetric: Metric
	visitorsMetric: Metric
}

type Suppression {
	createDate: String
	dataControlTaskBatchId: String
	dataControlTaskCreateDate: String
	dataControlTaskStatus: String
	emailAddress: String
	id: String
}

type SuppressionBag {
	suppressions: [Suppression]
	total: Int
}

type TimeRange {
	default: Boolean
	endLocalDateTime: String
	key: String
	rangeKey: Int
	startLocalDateTime: String
}

type Trend {
	percentage: Float
	trendClassification: String
}

type User implements DXPEntity {
	dataSourceName: String
	id: String
	name: String
	screenName: String
}

type UserSession {
	browserName: String
	completeDate: String
	contentLanguageId: String
	createDate: String
	description: String
	devicePixelRatio: String
	deviceType: String
	events: [Event]
	keywords: String
	languageId: String
	screenHeight: String
	screenWidth: String
	timezoneOffset: String
	userAgent: String
}