dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "org.osgi", name: "org.osgi.service.cm", version: "1.5.0"
	testIntegrationImplementation project(":apps:asset:asset-list-api")
	testIntegrationImplementation project(":apps:asset:asset-list-service")
	testIntegrationImplementation project(":apps:asset:asset-test-util")
	testIntegrationImplementation project(":apps:journal:journal-api")
	testIntegrationImplementation project(":apps:journal:journal-test-util")
	testIntegrationImplementation project(":apps:portal-configuration:portal-configuration-test-util")
	testIntegrationImplementation project(":apps:segments:segments-api")
	testIntegrationImplementation project(":apps:segments:segments-test-util")
}