/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.loop.service.base;

import com.liferay.osb.loop.model.LoopJobTitle;
import com.liferay.osb.loop.service.LoopJobTitleLocalService;
import com.liferay.osb.loop.service.LoopJobTitleLocalServiceUtil;
import com.liferay.osb.loop.service.persistence.LoopAuditEntryPersistence;
import com.liferay.osb.loop.service.persistence.LoopDivisionPersistence;
import com.liferay.osb.loop.service.persistence.LoopDivisionRelPersistence;
import com.liferay.osb.loop.service.persistence.LoopExternalReferenceRelPersistence;
import com.liferay.osb.loop.service.persistence.LoopJobTitlePersistence;
import com.liferay.osb.loop.service.persistence.LoopParticipantAssignmentPersistence;
import com.liferay.osb.loop.service.persistence.LoopPersonPersistence;
import com.liferay.osb.loop.service.persistence.LoopPersonRelPersistence;
import com.liferay.osb.loop.service.persistence.LoopStatsEntryPersistence;
import com.liferay.osb.loop.service.persistence.LoopStreamEntryPersistence;
import com.liferay.osb.loop.service.persistence.LoopStreamPersistence;
import com.liferay.osb.loop.service.persistence.LoopTopicAssignmentPersistence;
import com.liferay.osb.loop.service.persistence.LoopTopicPersistence;
import com.liferay.osb.loop.service.persistence.LoopUserNotificationEventPersistence;
import com.liferay.osb.loop.service.persistence.LoopUserNotificationRecordPersistence;
import com.liferay.osb.loop.service.persistence.LoopUserNotificationSubscriptionPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the loop job title local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.loop.service.impl.LoopJobTitleLocalServiceImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see com.liferay.osb.loop.service.impl.LoopJobTitleLocalServiceImpl
 * @generated
 */
public abstract class LoopJobTitleLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, LoopJobTitleLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LoopJobTitleLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>LoopJobTitleLocalServiceUtil</code>.
	 */

	/**
	 * Adds the loop job title to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoopJobTitleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loopJobTitle the loop job title
	 * @return the loop job title that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LoopJobTitle addLoopJobTitle(LoopJobTitle loopJobTitle) {
		loopJobTitle.setNew(true);

		return loopJobTitlePersistence.update(loopJobTitle);
	}

	/**
	 * Creates a new loop job title with the primary key. Does not add the loop job title to the database.
	 *
	 * @param loopJobTitleId the primary key for the new loop job title
	 * @return the new loop job title
	 */
	@Override
	@Transactional(enabled = false)
	public LoopJobTitle createLoopJobTitle(long loopJobTitleId) {
		return loopJobTitlePersistence.create(loopJobTitleId);
	}

	/**
	 * Deletes the loop job title with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoopJobTitleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loopJobTitleId the primary key of the loop job title
	 * @return the loop job title that was removed
	 * @throws PortalException if a loop job title with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LoopJobTitle deleteLoopJobTitle(long loopJobTitleId)
		throws PortalException {

		return loopJobTitlePersistence.remove(loopJobTitleId);
	}

	/**
	 * Deletes the loop job title from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoopJobTitleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loopJobTitle the loop job title
	 * @return the loop job title that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LoopJobTitle deleteLoopJobTitle(LoopJobTitle loopJobTitle) {
		return loopJobTitlePersistence.remove(loopJobTitle);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LoopJobTitle.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return loopJobTitlePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.loop.model.impl.LoopJobTitleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return loopJobTitlePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.loop.model.impl.LoopJobTitleModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return loopJobTitlePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return loopJobTitlePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return loopJobTitlePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LoopJobTitle fetchLoopJobTitle(long loopJobTitleId) {
		return loopJobTitlePersistence.fetchByPrimaryKey(loopJobTitleId);
	}

	/**
	 * Returns the loop job title with the primary key.
	 *
	 * @param loopJobTitleId the primary key of the loop job title
	 * @return the loop job title
	 * @throws PortalException if a loop job title with the primary key could not be found
	 */
	@Override
	public LoopJobTitle getLoopJobTitle(long loopJobTitleId)
		throws PortalException {

		return loopJobTitlePersistence.findByPrimaryKey(loopJobTitleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(loopJobTitleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LoopJobTitle.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("loopJobTitleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			loopJobTitleLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LoopJobTitle.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"loopJobTitleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(loopJobTitleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LoopJobTitle.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("loopJobTitleId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return loopJobTitleLocalService.deleteLoopJobTitle(
			(LoopJobTitle)persistedModel);
	}

	public BasePersistence<LoopJobTitle> getBasePersistence() {
		return loopJobTitlePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return loopJobTitlePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the loop job titles.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.loop.model.impl.LoopJobTitleModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of loop job titles
	 * @param end the upper bound of the range of loop job titles (not inclusive)
	 * @return the range of loop job titles
	 */
	@Override
	public List<LoopJobTitle> getLoopJobTitles(int start, int end) {
		return loopJobTitlePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of loop job titles.
	 *
	 * @return the number of loop job titles
	 */
	@Override
	public int getLoopJobTitlesCount() {
		return loopJobTitlePersistence.countAll();
	}

	/**
	 * Updates the loop job title in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoopJobTitleLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loopJobTitle the loop job title
	 * @return the loop job title that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LoopJobTitle updateLoopJobTitle(LoopJobTitle loopJobTitle) {
		return loopJobTitlePersistence.update(loopJobTitle);
	}

	/**
	 * Returns the loop audit entry local service.
	 *
	 * @return the loop audit entry local service
	 */
	public com.liferay.osb.loop.service.LoopAuditEntryLocalService
		getLoopAuditEntryLocalService() {

		return loopAuditEntryLocalService;
	}

	/**
	 * Sets the loop audit entry local service.
	 *
	 * @param loopAuditEntryLocalService the loop audit entry local service
	 */
	public void setLoopAuditEntryLocalService(
		com.liferay.osb.loop.service.LoopAuditEntryLocalService
			loopAuditEntryLocalService) {

		this.loopAuditEntryLocalService = loopAuditEntryLocalService;
	}

	/**
	 * Returns the loop audit entry persistence.
	 *
	 * @return the loop audit entry persistence
	 */
	public LoopAuditEntryPersistence getLoopAuditEntryPersistence() {
		return loopAuditEntryPersistence;
	}

	/**
	 * Sets the loop audit entry persistence.
	 *
	 * @param loopAuditEntryPersistence the loop audit entry persistence
	 */
	public void setLoopAuditEntryPersistence(
		LoopAuditEntryPersistence loopAuditEntryPersistence) {

		this.loopAuditEntryPersistence = loopAuditEntryPersistence;
	}

	/**
	 * Returns the loop division local service.
	 *
	 * @return the loop division local service
	 */
	public com.liferay.osb.loop.service.LoopDivisionLocalService
		getLoopDivisionLocalService() {

		return loopDivisionLocalService;
	}

	/**
	 * Sets the loop division local service.
	 *
	 * @param loopDivisionLocalService the loop division local service
	 */
	public void setLoopDivisionLocalService(
		com.liferay.osb.loop.service.LoopDivisionLocalService
			loopDivisionLocalService) {

		this.loopDivisionLocalService = loopDivisionLocalService;
	}

	/**
	 * Returns the loop division persistence.
	 *
	 * @return the loop division persistence
	 */
	public LoopDivisionPersistence getLoopDivisionPersistence() {
		return loopDivisionPersistence;
	}

	/**
	 * Sets the loop division persistence.
	 *
	 * @param loopDivisionPersistence the loop division persistence
	 */
	public void setLoopDivisionPersistence(
		LoopDivisionPersistence loopDivisionPersistence) {

		this.loopDivisionPersistence = loopDivisionPersistence;
	}

	/**
	 * Returns the loop division rel local service.
	 *
	 * @return the loop division rel local service
	 */
	public com.liferay.osb.loop.service.LoopDivisionRelLocalService
		getLoopDivisionRelLocalService() {

		return loopDivisionRelLocalService;
	}

	/**
	 * Sets the loop division rel local service.
	 *
	 * @param loopDivisionRelLocalService the loop division rel local service
	 */
	public void setLoopDivisionRelLocalService(
		com.liferay.osb.loop.service.LoopDivisionRelLocalService
			loopDivisionRelLocalService) {

		this.loopDivisionRelLocalService = loopDivisionRelLocalService;
	}

	/**
	 * Returns the loop division rel persistence.
	 *
	 * @return the loop division rel persistence
	 */
	public LoopDivisionRelPersistence getLoopDivisionRelPersistence() {
		return loopDivisionRelPersistence;
	}

	/**
	 * Sets the loop division rel persistence.
	 *
	 * @param loopDivisionRelPersistence the loop division rel persistence
	 */
	public void setLoopDivisionRelPersistence(
		LoopDivisionRelPersistence loopDivisionRelPersistence) {

		this.loopDivisionRelPersistence = loopDivisionRelPersistence;
	}

	/**
	 * Returns the loop external reference rel local service.
	 *
	 * @return the loop external reference rel local service
	 */
	public com.liferay.osb.loop.service.LoopExternalReferenceRelLocalService
		getLoopExternalReferenceRelLocalService() {

		return loopExternalReferenceRelLocalService;
	}

	/**
	 * Sets the loop external reference rel local service.
	 *
	 * @param loopExternalReferenceRelLocalService the loop external reference rel local service
	 */
	public void setLoopExternalReferenceRelLocalService(
		com.liferay.osb.loop.service.LoopExternalReferenceRelLocalService
			loopExternalReferenceRelLocalService) {

		this.loopExternalReferenceRelLocalService =
			loopExternalReferenceRelLocalService;
	}

	/**
	 * Returns the loop external reference rel persistence.
	 *
	 * @return the loop external reference rel persistence
	 */
	public LoopExternalReferenceRelPersistence
		getLoopExternalReferenceRelPersistence() {

		return loopExternalReferenceRelPersistence;
	}

	/**
	 * Sets the loop external reference rel persistence.
	 *
	 * @param loopExternalReferenceRelPersistence the loop external reference rel persistence
	 */
	public void setLoopExternalReferenceRelPersistence(
		LoopExternalReferenceRelPersistence
			loopExternalReferenceRelPersistence) {

		this.loopExternalReferenceRelPersistence =
			loopExternalReferenceRelPersistence;
	}

	/**
	 * Returns the loop job title local service.
	 *
	 * @return the loop job title local service
	 */
	public LoopJobTitleLocalService getLoopJobTitleLocalService() {
		return loopJobTitleLocalService;
	}

	/**
	 * Sets the loop job title local service.
	 *
	 * @param loopJobTitleLocalService the loop job title local service
	 */
	public void setLoopJobTitleLocalService(
		LoopJobTitleLocalService loopJobTitleLocalService) {

		this.loopJobTitleLocalService = loopJobTitleLocalService;
	}

	/**
	 * Returns the loop job title persistence.
	 *
	 * @return the loop job title persistence
	 */
	public LoopJobTitlePersistence getLoopJobTitlePersistence() {
		return loopJobTitlePersistence;
	}

	/**
	 * Sets the loop job title persistence.
	 *
	 * @param loopJobTitlePersistence the loop job title persistence
	 */
	public void setLoopJobTitlePersistence(
		LoopJobTitlePersistence loopJobTitlePersistence) {

		this.loopJobTitlePersistence = loopJobTitlePersistence;
	}

	/**
	 * Returns the loop participant assignment local service.
	 *
	 * @return the loop participant assignment local service
	 */
	public com.liferay.osb.loop.service.LoopParticipantAssignmentLocalService
		getLoopParticipantAssignmentLocalService() {

		return loopParticipantAssignmentLocalService;
	}

	/**
	 * Sets the loop participant assignment local service.
	 *
	 * @param loopParticipantAssignmentLocalService the loop participant assignment local service
	 */
	public void setLoopParticipantAssignmentLocalService(
		com.liferay.osb.loop.service.LoopParticipantAssignmentLocalService
			loopParticipantAssignmentLocalService) {

		this.loopParticipantAssignmentLocalService =
			loopParticipantAssignmentLocalService;
	}

	/**
	 * Returns the loop participant assignment persistence.
	 *
	 * @return the loop participant assignment persistence
	 */
	public LoopParticipantAssignmentPersistence
		getLoopParticipantAssignmentPersistence() {

		return loopParticipantAssignmentPersistence;
	}

	/**
	 * Sets the loop participant assignment persistence.
	 *
	 * @param loopParticipantAssignmentPersistence the loop participant assignment persistence
	 */
	public void setLoopParticipantAssignmentPersistence(
		LoopParticipantAssignmentPersistence
			loopParticipantAssignmentPersistence) {

		this.loopParticipantAssignmentPersistence =
			loopParticipantAssignmentPersistence;
	}

	/**
	 * Returns the loop person local service.
	 *
	 * @return the loop person local service
	 */
	public com.liferay.osb.loop.service.LoopPersonLocalService
		getLoopPersonLocalService() {

		return loopPersonLocalService;
	}

	/**
	 * Sets the loop person local service.
	 *
	 * @param loopPersonLocalService the loop person local service
	 */
	public void setLoopPersonLocalService(
		com.liferay.osb.loop.service.LoopPersonLocalService
			loopPersonLocalService) {

		this.loopPersonLocalService = loopPersonLocalService;
	}

	/**
	 * Returns the loop person persistence.
	 *
	 * @return the loop person persistence
	 */
	public LoopPersonPersistence getLoopPersonPersistence() {
		return loopPersonPersistence;
	}

	/**
	 * Sets the loop person persistence.
	 *
	 * @param loopPersonPersistence the loop person persistence
	 */
	public void setLoopPersonPersistence(
		LoopPersonPersistence loopPersonPersistence) {

		this.loopPersonPersistence = loopPersonPersistence;
	}

	/**
	 * Returns the loop person rel local service.
	 *
	 * @return the loop person rel local service
	 */
	public com.liferay.osb.loop.service.LoopPersonRelLocalService
		getLoopPersonRelLocalService() {

		return loopPersonRelLocalService;
	}

	/**
	 * Sets the loop person rel local service.
	 *
	 * @param loopPersonRelLocalService the loop person rel local service
	 */
	public void setLoopPersonRelLocalService(
		com.liferay.osb.loop.service.LoopPersonRelLocalService
			loopPersonRelLocalService) {

		this.loopPersonRelLocalService = loopPersonRelLocalService;
	}

	/**
	 * Returns the loop person rel persistence.
	 *
	 * @return the loop person rel persistence
	 */
	public LoopPersonRelPersistence getLoopPersonRelPersistence() {
		return loopPersonRelPersistence;
	}

	/**
	 * Sets the loop person rel persistence.
	 *
	 * @param loopPersonRelPersistence the loop person rel persistence
	 */
	public void setLoopPersonRelPersistence(
		LoopPersonRelPersistence loopPersonRelPersistence) {

		this.loopPersonRelPersistence = loopPersonRelPersistence;
	}

	/**
	 * Returns the loop stats entry local service.
	 *
	 * @return the loop stats entry local service
	 */
	public com.liferay.osb.loop.service.LoopStatsEntryLocalService
		getLoopStatsEntryLocalService() {

		return loopStatsEntryLocalService;
	}

	/**
	 * Sets the loop stats entry local service.
	 *
	 * @param loopStatsEntryLocalService the loop stats entry local service
	 */
	public void setLoopStatsEntryLocalService(
		com.liferay.osb.loop.service.LoopStatsEntryLocalService
			loopStatsEntryLocalService) {

		this.loopStatsEntryLocalService = loopStatsEntryLocalService;
	}

	/**
	 * Returns the loop stats entry persistence.
	 *
	 * @return the loop stats entry persistence
	 */
	public LoopStatsEntryPersistence getLoopStatsEntryPersistence() {
		return loopStatsEntryPersistence;
	}

	/**
	 * Sets the loop stats entry persistence.
	 *
	 * @param loopStatsEntryPersistence the loop stats entry persistence
	 */
	public void setLoopStatsEntryPersistence(
		LoopStatsEntryPersistence loopStatsEntryPersistence) {

		this.loopStatsEntryPersistence = loopStatsEntryPersistence;
	}

	/**
	 * Returns the loop stream local service.
	 *
	 * @return the loop stream local service
	 */
	public com.liferay.osb.loop.service.LoopStreamLocalService
		getLoopStreamLocalService() {

		return loopStreamLocalService;
	}

	/**
	 * Sets the loop stream local service.
	 *
	 * @param loopStreamLocalService the loop stream local service
	 */
	public void setLoopStreamLocalService(
		com.liferay.osb.loop.service.LoopStreamLocalService
			loopStreamLocalService) {

		this.loopStreamLocalService = loopStreamLocalService;
	}

	/**
	 * Returns the loop stream persistence.
	 *
	 * @return the loop stream persistence
	 */
	public LoopStreamPersistence getLoopStreamPersistence() {
		return loopStreamPersistence;
	}

	/**
	 * Sets the loop stream persistence.
	 *
	 * @param loopStreamPersistence the loop stream persistence
	 */
	public void setLoopStreamPersistence(
		LoopStreamPersistence loopStreamPersistence) {

		this.loopStreamPersistence = loopStreamPersistence;
	}

	/**
	 * Returns the loop stream entry local service.
	 *
	 * @return the loop stream entry local service
	 */
	public com.liferay.osb.loop.service.LoopStreamEntryLocalService
		getLoopStreamEntryLocalService() {

		return loopStreamEntryLocalService;
	}

	/**
	 * Sets the loop stream entry local service.
	 *
	 * @param loopStreamEntryLocalService the loop stream entry local service
	 */
	public void setLoopStreamEntryLocalService(
		com.liferay.osb.loop.service.LoopStreamEntryLocalService
			loopStreamEntryLocalService) {

		this.loopStreamEntryLocalService = loopStreamEntryLocalService;
	}

	/**
	 * Returns the loop stream entry persistence.
	 *
	 * @return the loop stream entry persistence
	 */
	public LoopStreamEntryPersistence getLoopStreamEntryPersistence() {
		return loopStreamEntryPersistence;
	}

	/**
	 * Sets the loop stream entry persistence.
	 *
	 * @param loopStreamEntryPersistence the loop stream entry persistence
	 */
	public void setLoopStreamEntryPersistence(
		LoopStreamEntryPersistence loopStreamEntryPersistence) {

		this.loopStreamEntryPersistence = loopStreamEntryPersistence;
	}

	/**
	 * Returns the loop topic local service.
	 *
	 * @return the loop topic local service
	 */
	public com.liferay.osb.loop.service.LoopTopicLocalService
		getLoopTopicLocalService() {

		return loopTopicLocalService;
	}

	/**
	 * Sets the loop topic local service.
	 *
	 * @param loopTopicLocalService the loop topic local service
	 */
	public void setLoopTopicLocalService(
		com.liferay.osb.loop.service.LoopTopicLocalService
			loopTopicLocalService) {

		this.loopTopicLocalService = loopTopicLocalService;
	}

	/**
	 * Returns the loop topic persistence.
	 *
	 * @return the loop topic persistence
	 */
	public LoopTopicPersistence getLoopTopicPersistence() {
		return loopTopicPersistence;
	}

	/**
	 * Sets the loop topic persistence.
	 *
	 * @param loopTopicPersistence the loop topic persistence
	 */
	public void setLoopTopicPersistence(
		LoopTopicPersistence loopTopicPersistence) {

		this.loopTopicPersistence = loopTopicPersistence;
	}

	/**
	 * Returns the loop topic assignment local service.
	 *
	 * @return the loop topic assignment local service
	 */
	public com.liferay.osb.loop.service.LoopTopicAssignmentLocalService
		getLoopTopicAssignmentLocalService() {

		return loopTopicAssignmentLocalService;
	}

	/**
	 * Sets the loop topic assignment local service.
	 *
	 * @param loopTopicAssignmentLocalService the loop topic assignment local service
	 */
	public void setLoopTopicAssignmentLocalService(
		com.liferay.osb.loop.service.LoopTopicAssignmentLocalService
			loopTopicAssignmentLocalService) {

		this.loopTopicAssignmentLocalService = loopTopicAssignmentLocalService;
	}

	/**
	 * Returns the loop topic assignment persistence.
	 *
	 * @return the loop topic assignment persistence
	 */
	public LoopTopicAssignmentPersistence getLoopTopicAssignmentPersistence() {
		return loopTopicAssignmentPersistence;
	}

	/**
	 * Sets the loop topic assignment persistence.
	 *
	 * @param loopTopicAssignmentPersistence the loop topic assignment persistence
	 */
	public void setLoopTopicAssignmentPersistence(
		LoopTopicAssignmentPersistence loopTopicAssignmentPersistence) {

		this.loopTopicAssignmentPersistence = loopTopicAssignmentPersistence;
	}

	/**
	 * Returns the loop user notification event local service.
	 *
	 * @return the loop user notification event local service
	 */
	public com.liferay.osb.loop.service.LoopUserNotificationEventLocalService
		getLoopUserNotificationEventLocalService() {

		return loopUserNotificationEventLocalService;
	}

	/**
	 * Sets the loop user notification event local service.
	 *
	 * @param loopUserNotificationEventLocalService the loop user notification event local service
	 */
	public void setLoopUserNotificationEventLocalService(
		com.liferay.osb.loop.service.LoopUserNotificationEventLocalService
			loopUserNotificationEventLocalService) {

		this.loopUserNotificationEventLocalService =
			loopUserNotificationEventLocalService;
	}

	/**
	 * Returns the loop user notification event persistence.
	 *
	 * @return the loop user notification event persistence
	 */
	public LoopUserNotificationEventPersistence
		getLoopUserNotificationEventPersistence() {

		return loopUserNotificationEventPersistence;
	}

	/**
	 * Sets the loop user notification event persistence.
	 *
	 * @param loopUserNotificationEventPersistence the loop user notification event persistence
	 */
	public void setLoopUserNotificationEventPersistence(
		LoopUserNotificationEventPersistence
			loopUserNotificationEventPersistence) {

		this.loopUserNotificationEventPersistence =
			loopUserNotificationEventPersistence;
	}

	/**
	 * Returns the loop user notification record local service.
	 *
	 * @return the loop user notification record local service
	 */
	public com.liferay.osb.loop.service.LoopUserNotificationRecordLocalService
		getLoopUserNotificationRecordLocalService() {

		return loopUserNotificationRecordLocalService;
	}

	/**
	 * Sets the loop user notification record local service.
	 *
	 * @param loopUserNotificationRecordLocalService the loop user notification record local service
	 */
	public void setLoopUserNotificationRecordLocalService(
		com.liferay.osb.loop.service.LoopUserNotificationRecordLocalService
			loopUserNotificationRecordLocalService) {

		this.loopUserNotificationRecordLocalService =
			loopUserNotificationRecordLocalService;
	}

	/**
	 * Returns the loop user notification record persistence.
	 *
	 * @return the loop user notification record persistence
	 */
	public LoopUserNotificationRecordPersistence
		getLoopUserNotificationRecordPersistence() {

		return loopUserNotificationRecordPersistence;
	}

	/**
	 * Sets the loop user notification record persistence.
	 *
	 * @param loopUserNotificationRecordPersistence the loop user notification record persistence
	 */
	public void setLoopUserNotificationRecordPersistence(
		LoopUserNotificationRecordPersistence
			loopUserNotificationRecordPersistence) {

		this.loopUserNotificationRecordPersistence =
			loopUserNotificationRecordPersistence;
	}

	/**
	 * Returns the loop user notification subscription local service.
	 *
	 * @return the loop user notification subscription local service
	 */
	public
		com.liferay.osb.loop.service.
			LoopUserNotificationSubscriptionLocalService
				getLoopUserNotificationSubscriptionLocalService() {

		return loopUserNotificationSubscriptionLocalService;
	}

	/**
	 * Sets the loop user notification subscription local service.
	 *
	 * @param loopUserNotificationSubscriptionLocalService the loop user notification subscription local service
	 */
	public void setLoopUserNotificationSubscriptionLocalService(
		com.liferay.osb.loop.service.
			LoopUserNotificationSubscriptionLocalService
				loopUserNotificationSubscriptionLocalService) {

		this.loopUserNotificationSubscriptionLocalService =
			loopUserNotificationSubscriptionLocalService;
	}

	/**
	 * Returns the loop user notification subscription persistence.
	 *
	 * @return the loop user notification subscription persistence
	 */
	public LoopUserNotificationSubscriptionPersistence
		getLoopUserNotificationSubscriptionPersistence() {

		return loopUserNotificationSubscriptionPersistence;
	}

	/**
	 * Sets the loop user notification subscription persistence.
	 *
	 * @param loopUserNotificationSubscriptionPersistence the loop user notification subscription persistence
	 */
	public void setLoopUserNotificationSubscriptionPersistence(
		LoopUserNotificationSubscriptionPersistence
			loopUserNotificationSubscriptionPersistence) {

		this.loopUserNotificationSubscriptionPersistence =
			loopUserNotificationSubscriptionPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.osb.loop.model.LoopJobTitle",
			loopJobTitleLocalService);

		LoopJobTitleLocalServiceUtil.setService(loopJobTitleLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.osb.loop.model.LoopJobTitle");

		LoopJobTitleLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LoopJobTitleLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LoopJobTitle.class;
	}

	protected String getModelClassName() {
		return LoopJobTitle.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = loopJobTitlePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopAuditEntryLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopAuditEntryLocalService
		loopAuditEntryLocalService;

	@BeanReference(type = LoopAuditEntryPersistence.class)
	protected LoopAuditEntryPersistence loopAuditEntryPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopDivisionLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopDivisionLocalService
		loopDivisionLocalService;

	@BeanReference(type = LoopDivisionPersistence.class)
	protected LoopDivisionPersistence loopDivisionPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopDivisionRelLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopDivisionRelLocalService
		loopDivisionRelLocalService;

	@BeanReference(type = LoopDivisionRelPersistence.class)
	protected LoopDivisionRelPersistence loopDivisionRelPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopExternalReferenceRelLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopExternalReferenceRelLocalService
		loopExternalReferenceRelLocalService;

	@BeanReference(type = LoopExternalReferenceRelPersistence.class)
	protected LoopExternalReferenceRelPersistence
		loopExternalReferenceRelPersistence;

	@BeanReference(type = LoopJobTitleLocalService.class)
	protected LoopJobTitleLocalService loopJobTitleLocalService;

	@BeanReference(type = LoopJobTitlePersistence.class)
	protected LoopJobTitlePersistence loopJobTitlePersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopParticipantAssignmentLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopParticipantAssignmentLocalService
		loopParticipantAssignmentLocalService;

	@BeanReference(type = LoopParticipantAssignmentPersistence.class)
	protected LoopParticipantAssignmentPersistence
		loopParticipantAssignmentPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopPersonLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopPersonLocalService
		loopPersonLocalService;

	@BeanReference(type = LoopPersonPersistence.class)
	protected LoopPersonPersistence loopPersonPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopPersonRelLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopPersonRelLocalService
		loopPersonRelLocalService;

	@BeanReference(type = LoopPersonRelPersistence.class)
	protected LoopPersonRelPersistence loopPersonRelPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopStatsEntryLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopStatsEntryLocalService
		loopStatsEntryLocalService;

	@BeanReference(type = LoopStatsEntryPersistence.class)
	protected LoopStatsEntryPersistence loopStatsEntryPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopStreamLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopStreamLocalService
		loopStreamLocalService;

	@BeanReference(type = LoopStreamPersistence.class)
	protected LoopStreamPersistence loopStreamPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopStreamEntryLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopStreamEntryLocalService
		loopStreamEntryLocalService;

	@BeanReference(type = LoopStreamEntryPersistence.class)
	protected LoopStreamEntryPersistence loopStreamEntryPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopTopicLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopTopicLocalService
		loopTopicLocalService;

	@BeanReference(type = LoopTopicPersistence.class)
	protected LoopTopicPersistence loopTopicPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopTopicAssignmentLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopTopicAssignmentLocalService
		loopTopicAssignmentLocalService;

	@BeanReference(type = LoopTopicAssignmentPersistence.class)
	protected LoopTopicAssignmentPersistence loopTopicAssignmentPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopUserNotificationEventLocalService.class
	)
	protected com.liferay.osb.loop.service.LoopUserNotificationEventLocalService
		loopUserNotificationEventLocalService;

	@BeanReference(type = LoopUserNotificationEventPersistence.class)
	protected LoopUserNotificationEventPersistence
		loopUserNotificationEventPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopUserNotificationRecordLocalService.class
	)
	protected
		com.liferay.osb.loop.service.LoopUserNotificationRecordLocalService
			loopUserNotificationRecordLocalService;

	@BeanReference(type = LoopUserNotificationRecordPersistence.class)
	protected LoopUserNotificationRecordPersistence
		loopUserNotificationRecordPersistence;

	@BeanReference(
		type = com.liferay.osb.loop.service.LoopUserNotificationSubscriptionLocalService.class
	)
	protected
		com.liferay.osb.loop.service.
			LoopUserNotificationSubscriptionLocalService
				loopUserNotificationSubscriptionLocalService;

	@BeanReference(type = LoopUserNotificationSubscriptionPersistence.class)
	protected LoopUserNotificationSubscriptionPersistence
		loopUserNotificationSubscriptionPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		LoopJobTitleLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}