CREATE INDEX IF NOT EXISTS IX_DXPENTITY_FGID ON DXPEntity USING HASH ((fields->>'groupId'));

CREATE INDEX IF NOT EXISTS IX_DXPENTITY_FOID ON DXPEntity USING HASH ((fields->>'organizationId'));

CREATE INDEX IF NOT EXISTS IX_DXPENTITY_FRID ON DXPEntity USING HASH ((fields->>'roleId'));

CREATE INDEX IF NOT EXISTS IX_DXPENTITY_FTID ON DXPEntity USING HASH ((fields->>'teamId'));

CREATE INDEX IF NOT EXISTS IX_DXPENTITY_FUGID ON DXPEntity USING HASH ((fields->>'userGroupId'));

CREATE INDEX IF NOT EXISTS IX_DXPENTITY_FUID ON DXPEntity USING HASH ((fields->>'userId'));

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTEDEFINITION_NAME ON EventAttributeDefinition (name);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_NAME ON EventDefinition (name);

CREATE UNIQUE INDEX IF NOT EXISTS IX_EVENTANALYSIS_CIN ON EventAnalysis (channelId, name);

CREATE INDEX IF NOT EXISTS IX_INDIVIDUALACTIVITY_EDII ON IndividualActivity (eventDate, individualId);