dependencies {
	compileInclude group: "org.json", name: "json", version: "20171018"
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.5.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.61.0"
	compileOnly group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	compileOnly group: "org.jsoup", name: "jsoup", version: "1.15.3"
}