modules.includes.required.functional[relevant]=apps/headless

modules.includes.required.test.batch.class.names.includes[relevant]=\
    apps/portal-vulcan/**/*Test.java

testray.main.component.name=Headless