#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.osb.koroneiki.phloem.rest.dto.v1_0.OktaUser
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Koroneiki.REST)
osgi.jaxrs.resource=true