dependencies {
	compileOnly project(":core:petra:petra-memory")
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testImplementation project(":core:petra:petra-lang")
	testImplementation project(":core:petra:petra-reflect")
	testImplementation project(":core:petra:petra-string")
}

liferay {
	deployDir = appServerLibGlobalDir
}