/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.fragment.service.base;

import com.liferay.fragment.model.FragmentEntry;
import com.liferay.fragment.service.FragmentEntryService;
import com.liferay.fragment.service.FragmentEntryServiceUtil;
import com.liferay.fragment.service.persistence.FragmentEntryLinkFinder;
import com.liferay.fragment.service.persistence.FragmentEntryLinkPersistence;
import com.liferay.fragment.service.persistence.FragmentEntryPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.sql.Connection;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the fragment entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.fragment.service.impl.FragmentEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.fragment.service.impl.FragmentEntryServiceImpl
 * @generated
 */
public abstract class FragmentEntryServiceBaseImpl
	extends BaseServiceImpl
	implements FragmentEntryService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FragmentEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FragmentEntryServiceUtil</code>.
	 */

	/**
	 * Returns the fragment entry local service.
	 *
	 * @return the fragment entry local service
	 */
	public com.liferay.fragment.service.FragmentEntryLocalService
		getFragmentEntryLocalService() {

		return fragmentEntryLocalService;
	}

	/**
	 * Sets the fragment entry local service.
	 *
	 * @param fragmentEntryLocalService the fragment entry local service
	 */
	public void setFragmentEntryLocalService(
		com.liferay.fragment.service.FragmentEntryLocalService
			fragmentEntryLocalService) {

		this.fragmentEntryLocalService = fragmentEntryLocalService;
	}

	/**
	 * Returns the fragment entry remote service.
	 *
	 * @return the fragment entry remote service
	 */
	public FragmentEntryService getFragmentEntryService() {
		return fragmentEntryService;
	}

	/**
	 * Sets the fragment entry remote service.
	 *
	 * @param fragmentEntryService the fragment entry remote service
	 */
	public void setFragmentEntryService(
		FragmentEntryService fragmentEntryService) {

		this.fragmentEntryService = fragmentEntryService;
	}

	/**
	 * Returns the fragment entry persistence.
	 *
	 * @return the fragment entry persistence
	 */
	public FragmentEntryPersistence getFragmentEntryPersistence() {
		return fragmentEntryPersistence;
	}

	/**
	 * Sets the fragment entry persistence.
	 *
	 * @param fragmentEntryPersistence the fragment entry persistence
	 */
	public void setFragmentEntryPersistence(
		FragmentEntryPersistence fragmentEntryPersistence) {

		this.fragmentEntryPersistence = fragmentEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the fragment entry link local service.
	 *
	 * @return the fragment entry link local service
	 */
	public com.liferay.fragment.service.FragmentEntryLinkLocalService
		getFragmentEntryLinkLocalService() {

		return fragmentEntryLinkLocalService;
	}

	/**
	 * Sets the fragment entry link local service.
	 *
	 * @param fragmentEntryLinkLocalService the fragment entry link local service
	 */
	public void setFragmentEntryLinkLocalService(
		com.liferay.fragment.service.FragmentEntryLinkLocalService
			fragmentEntryLinkLocalService) {

		this.fragmentEntryLinkLocalService = fragmentEntryLinkLocalService;
	}

	/**
	 * Returns the fragment entry link persistence.
	 *
	 * @return the fragment entry link persistence
	 */
	public FragmentEntryLinkPersistence getFragmentEntryLinkPersistence() {
		return fragmentEntryLinkPersistence;
	}

	/**
	 * Sets the fragment entry link persistence.
	 *
	 * @param fragmentEntryLinkPersistence the fragment entry link persistence
	 */
	public void setFragmentEntryLinkPersistence(
		FragmentEntryLinkPersistence fragmentEntryLinkPersistence) {

		this.fragmentEntryLinkPersistence = fragmentEntryLinkPersistence;
	}

	/**
	 * Returns the fragment entry link finder.
	 *
	 * @return the fragment entry link finder
	 */
	public FragmentEntryLinkFinder getFragmentEntryLinkFinder() {
		return fragmentEntryLinkFinder;
	}

	/**
	 * Sets the fragment entry link finder.
	 *
	 * @param fragmentEntryLinkFinder the fragment entry link finder
	 */
	public void setFragmentEntryLinkFinder(
		FragmentEntryLinkFinder fragmentEntryLinkFinder) {

		this.fragmentEntryLinkFinder = fragmentEntryLinkFinder;
	}

	public void afterPropertiesSet() {
		FragmentEntryServiceUtil.setService(fragmentEntryService);
	}

	public void destroy() {
		FragmentEntryServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FragmentEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FragmentEntry.class;
	}

	protected String getModelClassName() {
		return FragmentEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = fragmentEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.fragment.service.FragmentEntryLocalService.class
	)
	protected com.liferay.fragment.service.FragmentEntryLocalService
		fragmentEntryLocalService;

	@BeanReference(type = FragmentEntryService.class)
	protected FragmentEntryService fragmentEntryService;

	@BeanReference(type = FragmentEntryPersistence.class)
	protected FragmentEntryPersistence fragmentEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@BeanReference(
		type = com.liferay.fragment.service.FragmentEntryLinkLocalService.class
	)
	protected com.liferay.fragment.service.FragmentEntryLinkLocalService
		fragmentEntryLinkLocalService;

	@BeanReference(type = FragmentEntryLinkPersistence.class)
	protected FragmentEntryLinkPersistence fragmentEntryLinkPersistence;

	@BeanReference(type = FragmentEntryLinkFinder.class)
	protected FragmentEntryLinkFinder fragmentEntryLinkFinder;

	private static final Log _log = LogFactoryUtil.getLog(
		FragmentEntryServiceBaseImpl.class);

}